export const breadcrumb = {}
export const footer = {
  'zh-CN': [{
    "label": "长度",
    "value": "../Length"
  }, {
    "label": "面积",
    "value": "../Area"
  }, {
    "label": "质量",
    "value": "../Mass"
  }, {
    "label": "体积",
    "value": "../Volume"
  }, {
    "label": "体积流量",
    "value": "../VolumeFlowRate"
  }, {
    "label": "温度",
    "value": "../Temperature"
  }, {
    "label": "时间",
    "value": "../Time"
  }, {
    "label": "频率",
    "value": "../Frequency"
  }, {
    "label": "速度",
    "value": "../Speed"
  }, {
    "label": "力矩",
    "value": "../Torque"
  }, {
    "label": "配速",
    "value": "../Pace"
  }, {
    "label": "压力",
    "value": "../Pressure"
  }, {
    "label": "数字",
    "value": "../Digital"
  }, {
    "label": "照度",
    "value": "../Illuminance"
  }, {
    "label": "百分比",
    "value": "../PartsPer"
  }, {
    "label": "电压",
    "value": "../Voltage"
  }, {
    "label": "电流",
    "value": "../Current"
  }, {
    "label": "功率",
    "value": "../Power"
  }, {
    "label": "视在功率",
    "value": "../ApparentPower"
  }, {
    "label": "无功功率",
    "value": "../ReactivePower"
  }, {
    "label": "能量",
    "value": "../Energy"
  }, {
    "label": "无功电能",
    "value": "../ReactiveEnergy"
  }, {
    "label": "角度",
    "value": "../Angle"
  }, {
    "label": "电荷",
    "value": "../Charge"
  }, {
    "label": "力学",
    "value": "../Force"
  }, {
    "label": "加速度",
    "value": "../Acceleration"
  }]
}