export const footer = {
  'zh-CN': [{
    "label": "长度单位换算",
    "value": "../Length/index"
  }, {
    "label": "面积换算",
    "value": "../Area/index"
  }, {
    "label": "质量换算",
    "value": "../Mass/index"
  }, {
    "label": "体积换算",
    "value": "../Volume/index"
  }, {
    "label": "体积流量换算",
    "value": "../VolumeFlowRate/index"
  }, {
    "label": "温度换算",
    "value": "../Temperature/index"
  }, {
    "label": "时间换算",
    "value": "../Time/index"
  }, {
    "label": "频率换算",
    "value": "../Frequency/index"
  }, {
    "label": "速度换算",
    "value": "../Speed/index"
  }, {
    "label": "力矩换算",
    "value": "../Torque/index"
  }, {
    "label": "配速换算",
    "value": "../Pace/index"
  }, {
    "label": "压力换算",
    "value": "../Pressure/index"
  }, {
    "label": "数字换算",
    "value": "../Digital/index"
  }, {
    "label": "照度换算",
    "value": "../Illuminance/index"
  }, {
    "label": "百分比换算",
    "value": "../PartsPer/index"
  }, {
    "label": "电压换算",
    "value": "../Voltage/index"
  }, {
    "label": "电流换算",
    "value": "../Current/index"
  }, {
    "label": "功率换算",
    "value": "../Power/index"
  }, {
    "label": "视在功率换算",
    "value": "../ApparentPower/index"
  }, {
    "label": "无功功率换算",
    "value": "../ReactivePower/index"
  }, {
    "label": "能量换算",
    "value": "../Energy/index"
  }, {
    "label": "无功电能换算",
    "value": "../ReactiveEnergy/index"
  }, {
    "label": "角度换算",
    "value": "../Angle/index"
  }, {
    "label": "电荷换算",
    "value": "../Charge/index"
  }, {
    "label": "力学换算",
    "value": "../Force/index"
  }, {
    "label": "加速度换算",
    "value": "../Acceleration/index"
  }]
}