export const Time = [
  { name: 'Day to Hour', path: './Day-to-Hour' },
  { name: 'Day to Microsecond', path: './Day-to-Microsecond' },
  { name: 'Day to Millisecond', path: './Day-to-Millisecond' },
  { name: 'Day to Minute', path: './Day-to-Minute' },
  { name: 'Day to Month', path: './Day-to-Month' },
  { name: 'Day to Nanosecond', path: './Day-to-Nanosecond' },
  { name: 'Day to Second', path: './Day-to-Second' },
  { name: 'Day to Week', path: './Day-to-Week' },
  { name: 'Day to Year', path: './Day-to-Year' },
  { name: 'Hour to Day', path: './Hour-to-Day' },
  { name: 'Hour to Microsecond', path: './Hour-to-Microsecond' },
  { name: 'Hour to Millisecond', path: './Hour-to-Millisecond' },
  { name: 'Hour to Minute', path: './Hour-to-Minute' },
  { name: 'Hour to Month', path: './Hour-to-Month' },
  { name: 'Hour to Nanosecond', path: './Hour-to-Nanosecond' },
  { name: 'Hour to Second', path: './Hour-to-Second' },
  { name: 'Hour to Week', path: './Hour-to-Week' },
  { name: 'Hour to Year', path: './Hour-to-Year' },
  { name: 'Microsecond to Day', path: './Microsecond-to-Day' },
  { name: 'Microsecond to Hour', path: './Microsecond-to-Hour' },
  { name: 'Microsecond to Millisecond', path: './Microsecond-to-Millisecond' },
  { name: 'Microsecond to Minute', path: './Microsecond-to-Minute' },
  { name: 'Microsecond to Month', path: './Microsecond-to-Month' },
  { name: 'Microsecond to Nanosecond', path: './Microsecond-to-Nanosecond' },
  { name: 'Microsecond to Second', path: './Microsecond-to-Second' },
  { name: 'Microsecond to Week', path: './Microsecond-to-Week' },
  { name: 'Microsecond to Year', path: './Microsecond-to-Year' },
  { name: 'Millisecond to Day', path: './Millisecond-to-Day' },
  { name: 'Millisecond to Hour', path: './Millisecond-to-Hour' },
  { name: 'Millisecond to Microsecond', path: './Millisecond-to-Microsecond' },
  { name: 'Millisecond to Minute', path: './Millisecond-to-Minute' },
  { name: 'Millisecond to Month', path: './Millisecond-to-Month' },
  { name: 'Millisecond to Nanosecond', path: './Millisecond-to-Nanosecond' },
  { name: 'Millisecond to Second', path: './Millisecond-to-Second' },
  { name: 'Millisecond to Week', path: './Millisecond-to-Week' },
  { name: 'Millisecond to Year', path: './Millisecond-to-Year' },
  { name: 'Minute to Day', path: './Minute-to-Day' },
  { name: 'Minute to Hour', path: './Minute-to-Hour' },
  { name: 'Minute to Microsecond', path: './Minute-to-Microsecond' },
  { name: 'Minute to Millisecond', path: './Minute-to-Millisecond' },
  { name: 'Minute to Month', path: './Minute-to-Month' },
  { name: 'Minute to Nanosecond', path: './Minute-to-Nanosecond' },
  { name: 'Minute to Second', path: './Minute-to-Second' },
  { name: 'Minute to Week', path: './Minute-to-Week' },
  { name: 'Minute to Year', path: './Minute-to-Year' },
  { name: 'Month to Microsecond', path: './Month-to-Microsecond' },
  { name: 'Month to Nanosecond', path: './Month-to-Nanosecond' },
  { name: 'Nanosecond to Day', path: './Nanosecond-to-Day' },
  { name: 'Nanosecond to Hour', path: './Nanosecond-to-Hour' },
  { name: 'Nanosecond to Microsecond', path: './Nanosecond-to-Microsecond' },
  { name: 'Nanosecond to Millisecond', path: './Nanosecond-to-Millisecond' },
  { name: 'Nanosecond to Minute', path: './Nanosecond-to-Minute' },
  { name: 'Nanosecond to Month', path: './Nanosecond-to-Month' },
  { name: 'Nanosecond to Second', path: './Nanosecond-to-Second' },
  { name: 'Nanosecond to Week', path: './Nanosecond-to-Week' },
  { name: 'Nanosecond to Year', path: './Nanosecond-to-Year' },
  { name: 'Second to Day', path: './Second-to-Day' },
  { name: 'Second to Hour', path: './Second-to-Hour' },
  { name: 'Second to Microsecond', path: './Second-to-Microsecond' },
  { name: 'Second to Millisecond', path: './Second-to-Millisecond' },
  { name: 'Second to Minute', path: './Second-to-Minute' },
  { name: 'Second to Month', path: './Second-to-Month' },
  { name: 'Second to Nanosecond', path: './Second-to-Nanosecond' },
  { name: 'Second to Week', path: './Second-to-Week' },
  { name: 'Second to Year', path: './Second-to-Year' },
  { name: 'Week to Day', path: './Week-to-Day' },
  { name: 'Week to Hour', path: './Week-to-Hour' },
  { name: 'Week to Microsecond', path: './Week-to-Microsecond' },
  { name: 'Week to Millisecond', path: './Week-to-Millisecond' },
  { name: 'Week to Minute', path: './Week-to-Minute' },
  { name: 'Week to Month', path: './Week-to-Month' },
  { name: 'Week to Nanosecond', path: './Week-to-Nanosecond' },
  { name: 'Week to Second', path: './Week-to-Second' },
  { name: 'Week to Year', path: './Week-to-Year' },
  { name: 'Year to Day', path: './Year-to-Day' },
  { name: 'Year to Hour', path: './Year-to-Hour' },
  { name: 'Year to Microsecond', path: './Year-to-Microsecond' },
  { name: 'Year to Millisecond', path: './Year-to-Millisecond' },
  { name: 'Year to Minute', path: './Year-to-Minute' },
  { name: 'Year to Month', path: './Year-to-Month' },
  { name: 'Year to Nanosecond', path: './Year-to-Nanosecond' },
  { name: 'Year to Second', path: './Year-to-Second' },
  { name: 'Year to Week', path: './Year-to-Week' }
];
export const Mass = [
  { name: 'Microgram (mcg) to Milligram (mg)', path: './mcg-to-mg' },
  { name: 'Microgram (mcg) to Gram (g)', path: './mcg-to-g' },
  { name: 'Microgram (mcg) to Kilogram (kg)', path: './mcg-to-kg' },
  { name: 'Microgram (mcg) to Ounce (oz)', path: './mcg-to-oz' },
  { name: 'Microgram (mcg) to Pound (lb)', path: './mcg-to-lb' },
  { name: 'Microgram (mcg) to Metric Ton (mt)', path: './mcg-to-mt' },
  { name: 'Microgram (mcg) to Short Ton (st)', path: './mcg-to-st' },
  { name: 'Microgram (mcg) to Long Ton (t)', path: './mcg-to-t' },
  { name: 'Milligram (mg) to Microgram (mcg)', path: './mg-to-mcg' },
  { name: 'Milligram (mg) to Gram (g)', path: './mg-to-g' },
  { name: 'Milligram (mg) to Kilogram (kg)', path: './mg-to-kg' },
  { name: 'Milligram (mg) to Ounce (oz)', path: './mg-to-oz' },
  { name: 'Milligram (mg) to Pound (lb)', path: './mg-to-lb' },
  { name: 'Milligram (mg) to Metric Ton (mt)', path: './mg-to-mt' },
  { name: 'Milligram (mg) to Short Ton (st)', path: './mg-to-st' },
  { name: 'Milligram (mg) to Long Ton (t)', path: './mg-to-t' },
  { name: 'Gram (g) to Microgram (mcg)', path: './g-to-mcg' },
  { name: 'Gram (g) to Milligram (mg)', path: './g-to-mg' },
  { name: 'Gram (g) to Kilogram (kg)', path: './g-to-kg' },
  { name: 'Gram (g) to Ounce (oz)', path: './g-to-oz' },
  { name: 'Gram (g) to Pound (lb)', path: './g-to-lb' },
  { name: 'Gram (g) to Metric Ton (mt)', path: './g-to-mt' },
  { name: 'Gram (g) to Short Ton (st)', path: './g-to-st' },
  { name: 'Gram (g) to Long Ton (t)', path: './g-to-t' },
  { name: 'Kilogram (kg) to Microgram (mcg)', path: './kg-to-mcg' },
  { name: 'Kilogram (kg) to Milligram (mg)', path: './kg-to-mg' },
  { name: 'Kilogram (kg) to Gram (g)', path: './kg-to-g' },
  { name: 'Kilogram (kg) to Ounce (oz)', path: './kg-to-oz' },
  { name: 'Kilogram (kg) to Pound (lb)', path: './kg-to-lb' },
  { name: 'Kilogram (kg) to Metric Ton (mt)', path: './kg-to-mt' },
  { name: 'Kilogram (kg) to Short Ton (st)', path: './kg-to-st' },
  { name: 'Kilogram (kg) to Long Ton (t)', path: './kg-to-t' },
  { name: 'Ounce (oz) to Microgram (mcg)', path: './oz-to-mcg' },
  { name: 'Ounce (oz) to Milligram (mg)', path: './oz-to-mg' },
  { name: 'Ounce (oz) to Gram (g)', path: './oz-to-g' },
  { name: 'Ounce (oz) to Kilogram (kg)', path: './oz-to-kg' },
  { name: 'Ounce (oz) to Pound (lb)', path: './oz-to-lb' },
  { name: 'Ounce (oz) to Metric Ton (mt)', path: './oz-to-mt' },
  { name: 'Ounce (oz) to Short Ton (st)', path: './oz-to-st' },
  { name: 'Ounce (oz) to Long Ton (t)', path: './oz-to-t' },
  { name: 'Pound (lb) to Microgram (mcg)', path: './lb-to-mcg' },
  { name: 'Pound (lb) to Milligram (mg)', path: './lb-to-mg' },
  { name: 'Pound (lb) to Gram (g)', path: './lb-to-g' },
  { name: 'Pound (lb) to Kilogram (kg)', path: './lb-to-kg' },
  { name: 'Pound (lb) to Ounce (oz)', path: './lb-to-oz' },
  { name: 'Pound (lb) to Metric Ton (mt)', path: './lb-to-mt' },
  { name: 'Pound (lb) to Short Ton (st)', path: './lb-to-st' },
  { name: 'Pound (lb) to Long Ton (t)', path: './lb-to-t' },
  { name: 'Metric Ton (mt) to Microgram (mcg)', path: './mt-to-mcg' },
  { name: 'Metric Ton (mt) to Milligram (mg)', path: './mt-to-mg' },
  { name: 'Metric Ton (mt) to Gram (g)', path: './mt-to-g' },
  { name: 'Metric Ton (mt) to Kilogram (kg)', path: './mt-to-kg' },
  { name: 'Metric Ton (mt) to Ounce (oz)', path: './mt-to-oz' },
  { name: 'Metric Ton (mt) to Pound (lb)', path: './mt-to-lb' },
  { name: 'Metric Ton (mt) to Short Ton (st)', path: './mt-to-st' },
  { name: 'Metric Ton (mt) to Long Ton (t)', path: './mt-to-t' },
  { name: 'Short Ton (st) to Microgram (mcg)', path: './st-to-mcg' },
  { name: 'Short Ton (st) to Milligram (mg)', path: './st-to-mg' },
  { name: 'Short Ton (st) to Gram (g)', path: './st-to-g' },
  { name: 'Short Ton (st) to Kilogram (kg)', path: './st-to-kg' },
  { name: 'Short Ton (st) to Ounce (oz)', path: './st-to-oz' },
  { name: 'Short Ton (st) to Pound (lb)', path: './st-to-lb' },
  { name: 'Short Ton (st) to Metric Ton (mt)', path: './st-to-mt' },
  { name: 'Short Ton (st) to Long Ton (t)', path: './st-to-t' },
  { name: 'Long Ton (t) to Microgram (mcg)', path: './t-to-mcg' },
  { name: 'Long Ton (t) to Milligram (mg)', path: './t-to-mg' },
  { name: 'Long Ton (t) to Gram (g)', path: './t-to-g' },
  { name: 'Long Ton (t) to Kilogram (kg)', path: './t-to-kg' },
  { name: 'Long Ton (t) to Ounce (oz)', path: './t-to-oz' },
  { name: 'Long Ton (t) to Pound (lb)', path: './t-to-lb' },
  { name: 'Long Ton (t) to Metric Ton (mt)', path: './t-to-mt' },
  { name: 'Long Ton (t) to Short Ton (st)', path: './t-to-st' }
];
export const Area = [
  { name: 'Square Millimeter (mm²) to Square Centimeter (cm²)', path: './SquareMillimeter-to-SquareCentimeter' },
  { name: 'Square Millimeter (mm²) to Square Meter (m²)', path: './SquareMillimeter-to-SquareMeter' },
  { name: 'Square Millimeter (mm²) to Hectare (ha)', path: './SquareMillimeter-to-Hectare' },
  { name: 'Square Millimeter (mm²) to Square Kilometer (km²)', path: './SquareMillimeter-to-SquareKilometer' },
  { name: 'Square Millimeter (mm²) to Square Inch (in²)', path: './SquareMillimeter-to-SquareInch' },
  { name: 'Square Millimeter (mm²) to Square Foot (ft²)', path: './SquareMillimeter-to-SquareFoot' },
  { name: 'Square Millimeter (mm²) to Acre (ac)', path: './SquareMillimeter-to-Acre' },
  { name: 'Square Millimeter (mm²) to Square Mile (mi²)', path: './SquareMillimeter-to-SquareMile' },

  { name: 'Square Centimeter (cm²) to Square Millimeter (mm²)', path: './SquareCentimeter-to-SquareMillimeter' },
  { name: 'Square Centimeter (cm²) to Square Meter (m²)', path: './SquareCentimeter-to-SquareMeter' },
  { name: 'Square Centimeter (cm²) to Hectare (ha)', path: './SquareCentimeter-to-Hectare' },
  { name: 'Square Centimeter (cm²) to Square Kilometer (km²)', path: './SquareCentimeter-to-SquareKilometer' },
  { name: 'Square Centimeter (cm²) to Square Inch (in²)', path: './SquareCentimeter-to-SquareInch' },
  { name: 'Square Centimeter (cm²) to Square Foot (ft²)', path: './SquareCentimeter-to-SquareFoot' },
  { name: 'Square Centimeter (cm²) to Acre (ac)', path: './SquareCentimeter-to-Acre' },
  { name: 'Square Centimeter (cm²) to Square Mile (mi²)', path: './SquareCentimeter-to-SquareMile' },

  { name: 'Square Meter (m²) to Square Millimeter (mm²)', path: './SquareMeter-to-SquareMillimeter' },
  { name: 'Square Meter (m²) to Square Centimeter (cm²)', path: './SquareMeter-to-SquareCentimeter' },
  { name: 'Square Meter (m²) to Hectare (ha)', path: './SquareMeter-to-Hectare' },
  { name: 'Square Meter (m²) to Square Kilometer (km²)', path: './SquareMeter-to-SquareKilometer' },
  { name: 'Square Meter (m²) to Square Inch (in²)', path: './SquareMeter-to-SquareInch' },
  { name: 'Square Meter (m²) to Square Foot (ft²)', path: './SquareMeter-to-SquareFoot' },
  { name: 'Square Meter (m²) to Acre (ac)', path: './SquareMeter-to-Acre' },
  { name: 'Square Meter (m²) to Square Mile (mi²)', path: './SquareMeter-to-SquareMile' },

  { name: 'Hectare (ha) to Square Millimeter (mm²)', path: './Hectare-to-SquareMillimeter' },
  { name: 'Hectare (ha) to Square Centimeter (cm²)', path: './Hectare-to-SquareCentimeter' },
  { name: 'Hectare (ha) to Square Meter (m²)', path: './Hectare-to-SquareMeter' },
  { name: 'Hectare (ha) to Square Kilometer (km²)', path: './Hectare-to-SquareKilometer' },
  { name: 'Hectare (ha) to Square Inch (in²)', path: './Hectare-to-SquareInch' },
  { name: 'Hectare (ha) to Square Foot (ft²)', path: './Hectare-to-SquareFoot' },
  { name: 'Hectare (ha) to Acre (ac)', path: './Hectare-to-Acre' },
  { name: 'Hectare (ha) to Square Mile (mi²)', path: './Hectare-to-SquareMile' },

  { name: 'Square Kilometer (km²) to Square Millimeter (mm²)', path: './SquareKilometer-to-SquareMillimeter' },
  { name: 'Square Kilometer (km²) to Square Centimeter (cm²)', path: './SquareKilometer-to-SquareCentimeter' },
  { name: 'Square Kilometer (km²) to Square Meter (m²)', path: './SquareKilometer-to-SquareMeter' },
  { name: 'Square Kilometer (km²) to Hectare (ha)', path: './SquareKilometer-to-Hectare' },
  { name: 'Square Kilometer (km²) to Square Inch (in²)', path: './SquareKilometer-to-SquareInch' },
  { name: 'Square Kilometer (km²) to Square Foot (ft²)', path: './SquareKilometer-to-SquareFoot' },
  { name: 'Square Kilometer (km²) to Acre (ac)', path: './SquareKilometer-to-Acre' },
  { name: 'Square Kilometer (km²) to Square Mile (mi²)', path: './SquareKilometer-to-SquareMile' },

  { name: 'Square Inch (in²) to Square Millimeter (mm²)', path: './SquareInch-to-SquareMillimeter' },
  { name: 'Square Inch (in²) to Square Centimeter (cm²)', path: './SquareInch-to-SquareCentimeter' },
  { name: 'Square Inch (in²) to Square Meter (m²)', path: './SquareInch-to-SquareMeter' },
  { name: 'Square Inch (in²) to Hectare (ha)', path: './SquareInch-to-Hectare' },
  { name: 'Square Inch (in²) to Square Kilometer (km²)', path: './SquareInch-to-SquareKilometer' },
  { name: 'Square Inch (in²) to Square Foot (ft²)', path: './SquareInch-to-SquareFoot' },
  { name: 'Square Inch (in²) to Acre (ac)', path: './SquareInch-to-Acre' },
  { name: 'Square Inch (in²) to Square Mile (mi²)', path: './SquareInch-to-SquareMile' },

  { name: 'Square Foot (ft²) to Square Millimeter (mm²)', path: './SquareFoot-to-SquareMillimeter' },
  { name: 'Square Foot (ft²) to Square Centimeter (cm²)', path: './SquareFoot-to-SquareCentimeter' },
  { name: 'Square Foot (ft²) to Square Meter (m²)', path: './SquareFoot-to-SquareMeter' },
  { name: 'Square Foot (ft²) to Hectare (ha)', path: './SquareFoot-to-Hectare' },
  { name: 'Square Foot (ft²) to Square Kilometer (km²)', path: './SquareFoot-to-SquareKilometer' },
  { name: 'Square Foot (ft²) to Square Inch (in²)', path: './SquareFoot-to-SquareInch' },
  { name: 'Square Foot (ft²) to Acre (ac)', path: './SquareFoot-to-Acre' },
  { name: 'Square Foot (ft²) to Square Mile (mi²)', path: './SquareFoot-to-SquareMile' },

  { name: 'Acre (ac) to Square Millimeter (mm²)', path: './Acre-to-SquareMillimeter' },
  { name: 'Acre (ac) to Square Centimeter (cm²)', path: './Acre-to-SquareCentimeter' },
  { name: 'Acre (ac) to Square Meter (m²)', path: './Acre-to-SquareMeter' },
  { name: 'Acre (ac) to Hectare (ha)', path: './Acre-to-Hectare' },
  { name: 'Acre (ac) to Square Kilometer (km²)', path: './Acre-to-SquareKilometer' },
  { name: 'Acre (ac) to Square Inch (in²)', path: './Acre-to-SquareInch' },
  { name: 'Acre (ac) to Square Foot (ft²)', path: './Acre-to-SquareFoot' },
  { name: 'Acre (ac) to Square Mile (mi²)', path: './Acre-to-SquareMile' },

  { name: 'Square Mile (mi²) to Square Millimeter (mm²)', path: './SquareMile-to-SquareMillimeter' },
  { name: 'Square Mile (mi²) to Square Centimeter (cm²)', path: './SquareMile-to-SquareCentimeter' },
  { name: 'Square Mile (mi²) to Square Meter (m²)', path: './SquareMile-to-SquareMeter' },
  { name: 'Square Mile (mi²) to Hectare (ha)', path: './SquareMile-to-Hectare' },
  { name: 'Square Mile (mi²) to Square Kilometer (km²)', path: './SquareMile-to-SquareKilometer' },
  { name: 'Square Mile (mi²) to Square Inch (in²)', path: './SquareMile-to-SquareInch' },
  { name: 'Square Mile (mi²) to Square Foot (ft²)', path: './SquareMile-to-SquareFoot' },
  { name: 'Square Mile (mi²) to Acre (ac)', path: './SquareMile-to-Acre' }
];
export const Temperature = [
  { name: 'Celsius (°C) to Kelvin (K)', path: './Celsius-to-Kelvin' },
  { name: 'Celsius (°C) to Fahrenheit (°F)', path: './Celsius-to-Fahrenheit' },
  { name: 'Celsius (°C) to Rankine (R)', path: './Celsius-to-Rankine' },
  { name: 'Kelvin (K) to Celsius (°C)', path: './Kelvin-to-Celsius' },
  { name: 'Kelvin (K) to Fahrenheit (°F)', path: './Kelvin-to-Fahrenheit' },
  { name: 'Kelvin (K) to Rankine (R)', path: './Kelvin-to-Rankine' },
  { name: 'Fahrenheit (°F) to Celsius (°C)', path: './Fahrenheit-to-Celsius' },
  { name: 'Fahrenheit (°F) to Kelvin (K)', path: './Fahrenheit-to-Kelvin' },
  { name: 'Fahrenheit (°F) to Rankine (R)', path: './Fahrenheit-to-Rankine' },
  { name: 'Rankine (R) to Celsius (°C)', path: './Rankine-to-Celsius' },
  { name: 'Rankine (R) to Kelvin (K)', path: './Rankine-to-Kelvin' },
  { name: 'Rankine (R) to Fahrenheit (°F)', path: './Rankine-to-Fahrenheit' }
];
export const Volume = [
  { name: 'Cubic Millimeter (mm³) to Cubic Centimeter (cm³)', path: './mm3-to-cm3' },
  { name: 'Cubic Millimeter (mm³) to Milliliter (ml)', path: './mm3-to-ml' },
  { name: 'Cubic Millimeter (mm³) to Liter (l)', path: './mm3-to-l' },
  { name: 'Cubic Millimeter (mm³) to Kiloliter (kl)', path: './mm3-to-kl' },
  { name: 'Cubic Millimeter (mm³) to Megaliter (Ml)', path: './mm3-to-Ml' },
  { name: 'Cubic Millimeter (mm³) to Gigaliter (Gl)', path: './mm3-to-Gl' },
  { name: 'Cubic Millimeter (mm³) to Cubic Meter (m³)', path: './mm3-to-m3' },
  { name: 'Cubic Millimeter (mm³) to Cubic Kilometer (km³)', path: './mm3-to-km3' },
  { name: 'Cubic Centimeter (cm³) to Cubic Millimeter (mm³)', path: './cm3-to-mm3' },
  { name: 'Cubic Centimeter (cm³) to Milliliter (ml)', path: './cm3-to-ml' },
  { name: 'Cubic Centimeter (cm³) to Liter (l)', path: './cm3-to-l' },
  { name: 'Cubic Centimeter (cm³) to Kiloliter (kl)', path: './cm3-to-kl' },
  { name: 'Cubic Centimeter (cm³) to Megaliter (Ml)', path: './cm3-to-Ml' },
  { name: 'Cubic Centimeter (cm³) to Gigaliter (Gl)', path: './cm3-to-Gl' },
  { name: 'Cubic Centimeter (cm³) to Cubic Meter (m³)', path: './cm3-to-m3' },
  { name: 'Cubic Centimeter (cm³) to Cubic Kilometer (km³)', path: './cm3-to-km3' },
  { name: 'Milliliter (ml) to Cubic Millimeter (mm³)', path: './ml-to-mm3' },
  { name: 'Milliliter (ml) to Cubic Centimeter (cm³)', path: './ml-to-cm3' },
  { name: 'Milliliter (ml) to Liter (l)', path: './ml-to-l' },
  { name: 'Milliliter (ml) to Kiloliter (kl)', path: './ml-to-kl' },
  { name: 'Milliliter (ml) to Megaliter (Ml)', path: './ml-to-Ml' },
  { name: 'Milliliter (ml) to Gigaliter (Gl)', path: './ml-to-Gl' },
  { name: 'Milliliter (ml) to Cubic Meter (m³)', path: './ml-to-m3' },
  { name: 'Milliliter (ml) to Cubic Kilometer (km³)', path: './ml-to-km3' },
  { name: 'Liter (l) to Cubic Millimeter (mm³)', path: './l-to-mm3' },
  { name: 'Liter (l) to Cubic Centimeter (cm³)', path: './l-to-cm3' },
  { name: 'Liter (l) to Milliliter (ml)', path: './l-to-ml' },
  { name: 'Liter (l) to Kiloliter (kl)', path: './l-to-kl' },
  { name: 'Liter (l) to Megaliter (Ml)', path: './l-to-Ml' },
  { name: 'Liter (l) to Gigaliter (Gl)', path: './l-to-Gl' },
  { name: 'Liter (l) to Cubic Meter (m³)', path: './l-to-m3' },
  { name: 'Liter (l) to Cubic Kilometer (km³)', path: './l-to-km3' },
  { name: 'Kiloliter (kl) to Cubic Millimeter (mm³)', path: './kl-to-mm3' },
  { name: 'Kiloliter (kl) to Cubic Centimeter (cm³)', path: './kl-to-cm3' },
  { name: 'Kiloliter (kl) to Milliliter (ml)', path: './kl-to-ml' },
  { name: 'Kiloliter (kl) to Liter (l)', path: './kl-to-l' },
  { name: 'Kiloliter (kl) to Megaliter (Ml)', path: './kl-to-Ml' },
  { name: 'Kiloliter (kl) to Gigaliter (Gl)', path: './kl-to-Gl' },
  { name: 'Kiloliter (kl) to Cubic Meter (m³)', path: './kl-to-m3' },
  { name: 'Kiloliter (kl) to Cubic Kilometer (km³)', path: './kl-to-km3' },
  { name: 'Megaliter (Ml) to Cubic Millimeter (mm³)', path: './Ml-to-mm3' },
  { name: 'Megaliter (Ml) to Cubic Centimeter (cm³)', path: './Ml-to-cm3' },
  { name: 'Megaliter (Ml) to Milliliter (ml)', path: './Ml-to-ml' },
  { name: 'Megaliter (Ml) to Liter (l)', path: './Ml-to-l' },
  { name: 'Megaliter (Ml) to Kiloliter (kl)', path: './Ml-to-kl' },
  { name: 'Megaliter (Ml) to Gigaliter (Gl)', path: './Ml-to-Gl' },
  { name: 'Megaliter (Ml) to Cubic Meter (m³)', path: './Ml-to-m3' },
  { name: 'Megaliter (Ml) to Cubic Kilometer (km³)', path: './Ml-to-km3' },
  { name: 'Gigaliter (Gl) to Cubic Millimeter (mm³)', path: './Gl-to-mm3' },
  { name: 'Gigaliter (Gl) to Cubic Centimeter (cm³)', path: './Gl-to-cm3' },
  { name: 'Gigaliter (Gl) to Milliliter (ml)', path: './Gl-to-ml' },
  { name: 'Gigaliter (Gl) to Liter (l)', path: './Gl-to-l' },
  { name: 'Gigaliter (Gl) to Kiloliter (kl)', path: './Gl-to-kl' },
  { name: 'Gigaliter (Gl) to Megaliter (Ml)', path: './Gl-to-Ml' },
  { name: 'Gigaliter (Gl) to Cubic Meter (m³)', path: './Gl-to-m3' },
  { name: 'Gigaliter (Gl) to Cubic Kilometer (km³)', path: './Gl-to-km3' },
  { name: 'Cubic Meter (m³) to Cubic Millimeter (mm³)', path: './m3-to-mm3' },
  { name: 'Cubic Meter (m³) to Cubic Centimeter (cm³)', path: './m3-to-cm3' },
  { name: 'Cubic Meter (m³) to Milliliter (ml)', path: './m3-to-ml' },
  { name: 'Cubic Meter (m³) to Liter (l)', path: './m3-to-l' },
  { name: 'Cubic Meter (m³) to Kiloliter (kl)', path: './m3-to-kl' },
  { name: 'Cubic Meter (m³) to Megaliter (Ml)', path: './m3-to-Ml' },
  { name: 'Cubic Meter (m³) to Gigaliter (Gl)', path: './m3-to-Gl' },
  { name: 'Cubic Meter (m³) to Cubic Kilometer (km³)', path: './m3-to-km3' },
  { name: 'Cubic Kilometer (km³) to Cubic Millimeter (mm³)', path: './km3-to-mm3' },
  { name: 'Cubic Kilometer (km³) to Cubic Centimeter (cm³)', path: './km3-to-cm3' },
  { name: 'Cubic Kilometer (km³) to Milliliter (ml)', path: './km3-to-ml' },
  { name: 'Cubic Kilometer (km³) to Liter (l)', path: './km3-to-l' },
  { name: 'Cubic Kilometer (km³) to Kiloliter (kl)', path: './km3-to-kl' },
  { name: 'Cubic Kilometer (km³) to Megaliter (Ml)', path: './km3-to-Ml' },
  { name: 'Cubic Kilometer (km³) to Gigaliter (Gl)', path: './km3-to-Gl' },
  { name: 'Cubic Kilometer (km³) to Cubic Meter (m³)', path: './km3-to-m3' },
  { name: 'Teaspoon (tsp) to Cubic Millimeter (mm³)', path: './tsp-to-mm3' },
  { name: 'Teaspoon (tsp) to Cubic Centimeter (cm³)', path: './tsp-to-cm3' },
  { name: 'Teaspoon (tsp) to Milliliter (ml)', path: './tsp-to-ml' },
  { name: 'Teaspoon (tsp) to Liter (l)', path: './tsp-to-l' },
  { name: 'Teaspoon (tsp) to Kiloliter (kl)', path: './tsp-to-kl' },
  { name: 'Teaspoon (tsp) to Megaliter (Ml)', path: './tsp-to-Ml' },
  { name: 'Teaspoon (tsp) to Gigaliter (Gl)', path: './tsp-to-Gl' },
  { name: 'Teaspoon (tsp) to Cubic Meter (m³)', path: './tsp-to-m3' },
  { name: 'Teaspoon (tsp) to Cubic Kilometer (km³)', path: './tsp-to-km3' },
  { name: 'Tablespoon (Tbs) to Cubic Millimeter (mm³)', path: './Tbs-to-mm3' },
  { name: 'Tablespoon (Tbs) to Cubic Centimeter (cm³)', path: './Tbs-to-cm3' },
  { name: 'Tablespoon (Tbs) to Milliliter (ml)', path: './Tbs-to-ml' },
  { name: 'Tablespoon (Tbs) to Liter (l)', path: './Tbs-to-l' },
  { name: 'Tablespoon (Tbs) to Kiloliter (kl)', path: './Tbs-to-kl' },
  { name: 'Tablespoon (Tbs) to Megaliter (Ml)', path: './Tbs-to-Ml' },
  { name: 'Tablespoon (Tbs) to Gigaliter (Gl)', path: './Tbs-to-Gl' },
  { name: 'Tablespoon (Tbs) to Cubic Meter (m³)', path: './Tbs-to-m3' },
  { name: 'Tablespoon (Tbs) to Cubic Kilometer (km³)', path: './Tbs-to-km3' },
  { name: 'Cubic Inch (in3) to Cubic Millimeter (mm³)', path: './in3-to-mm3' },
  { name: 'Cubic Inch (in3) to Cubic Centimeter (cm³)', path: './in3-to-cm3' },
  { name: 'Cubic Inch (in3) to Milliliter (ml)', path: './in3-to-ml' },
  { name: 'Cubic Inch (in3) to Liter (l)', path: './in3-to-l' },
  { name: 'Cubic Inch (in3) to Kiloliter (kl)', path: './in3-to-kl' },
  { name: 'Cubic Inch (in3) to Megaliter (Ml)', path: './in3-to-Ml' },
  { name: 'Cubic Inch (in3) to Gigaliter (Gl)', path: './in3-to-Gl' },
  { name: 'Cubic Inch (in3) to Cubic Meter (m³)', path: './in3-to-m3' },
  { name: 'Cubic Inch (in3) to Cubic Kilometer (km³)', path: './in3-to-km3' },
  { name: 'Fluid Ounce (fl-oz) to Cubic Millimeter (mm³)', path: './fl-oz-to-mm3' },
  { name: 'Fluid Ounce (fl-oz) to Cubic Centimeter (cm³)', path: './fl-oz-to-cm3' },
  { name: 'Fluid Ounce (fl-oz) to Milliliter (ml)', path: './fl-oz-to-ml' },
  { name: 'Fluid Ounce (fl-oz) to Liter (l)', path: './fl-oz-to-l' },
  { name: 'Fluid Ounce (fl-oz) to Kiloliter (kl)', path: './fl-oz-to-kl' },
  { name: 'Fluid Ounce (fl-oz) to Megaliter (Ml)', path: './fl-oz-to-Ml' },
  { name: 'Fluid Ounce (fl-oz) to Gigaliter (Gl)', path: './fl-oz-to-Gl' },
  { name: 'Fluid Ounce (fl-oz) to Cubic Meter (m³)', path: './fl-oz-to-m3' },
  { name: 'Fluid Ounce (fl-oz) to Cubic Kilometer (km³)', path: './fl-oz-to-km3' },
  { name: 'Cup (cup) to Cubic Millimeter (mm³)', path: './cup-to-mm3' },
  { name: 'Cup (cup) to Cubic Centimeter (cm³)', path: './cup-to-cm3' },
  { name: 'Cup (cup) to Milliliter (ml)', path: './cup-to-ml' },
  { name: 'Cup (cup) to Liter (l)', path: './cup-to-l' },
  { name: 'Cup (cup) to Kiloliter (kl)', path: './cup-to-kl' },
  { name: 'Cup (cup) to Megaliter (Ml)', path: './cup-to-Ml' },
  { name: 'Cup (cup) to Gigaliter (Gl)', path: './cup-to-Gl' },
  { name: 'Cup (cup) to Cubic Meter (m³)', path: './cup-to-m3' },
  { name: 'Cup (cup) to Cubic Kilometer (km³)', path: './cup-to-km3' },
  { name: 'Pint (pnt) to Cubic Millimeter (mm³)', path: './pnt-to-mm3' },
  { name: 'Pint (pnt) to Cubic Centimeter (cm³)', path: './pnt-to-cm3' },
  { name: 'Pint (pnt) to Milliliter (ml)', path: './pnt-to-ml' },
  { name: 'Pint (pnt) to Liter (l)', path: './pnt-to-l' },
  { name: 'Pint (pnt) to Kiloliter (kl)', path: './pnt-to-kl' },
  { name: 'Pint (pnt) to Megaliter (Ml)', path: './pnt-to-Ml' },
  { name: 'Pint (pnt) to Gigaliter (Gl)', path: './pnt-to-Gl' },
  { name: 'Pint (pnt) to Cubic Meter (m³)', path: './pnt-to-m3' },
  { name: 'Pint (pnt) to Cubic Kilometer (km³)', path: './pnt-to-km3' },
  { name: 'Quart (qt) to Cubic Millimeter (mm³)', path: './qt-to-mm3' },
  { name: 'Quart (qt) to Cubic Centimeter (cm³)', path: './qt-to-cm3' },
  { name: 'Quart (qt) to Milliliter (ml)', path: './qt-to-ml' },
  { name: 'Quart (qt) to Liter (l)', path: './qt-to-l' },
  { name: 'Quart (qt) to Kiloliter (kl)', path: './qt-to-kl' },
  { name: 'Quart (qt) to Megaliter (Ml)', path: './qt-to-Ml' },
  { name: 'Quart (qt) to Gigaliter (Gl)', path: './qt-to-Gl' },
  { name: 'Quart (qt) to Cubic Meter (m³)', path: './qt-to-m3' },
  { name: 'Quart (qt) to Cubic Kilometer (km³)', path: './qt-to-km3' },
  { name: 'Gallon (gal) to Cubic Millimeter (mm³)', path: './gal-to-mm3' },
  { name: 'Gallon (gal) to Cubic Centimeter (cm³)', path: './gal-to-cm3' },
  { name: 'Gallon (gal) to Milliliter (ml)', path: './gal-to-ml' },
  { name: 'Gallon (gal) to Liter (l)', path: './gal-to-l' },
  { name: 'Gallon (gal) to Kiloliter (kl)', path: './gal-to-kl' },
  { name: 'Gallon (gal) to Megaliter (Ml)', path: './gal-to-Ml' },
  { name: 'Gallon (gal) to Gigaliter (Gl)', path: './gal-to-Gl' },
  { name: 'Gallon (gal) to Cubic Meter (m³)', path: './gal-to-m3' },
  { name: 'Gallon (gal) to Cubic Kilometer (km³)', path: './gal-to-km3' },
  { name: 'Cubic Foot (ft3) to Cubic Millimeter (mm³)', path: './ft3-to-mm3' },
  { name: 'Cubic Foot (ft3) to Cubic Centimeter (cm³)', path: './ft3-to-cm3' },
  { name: 'Cubic Foot (ft3) to Milliliter (ml)', path: './ft3-to-ml' },
  { name: 'Cubic Foot (ft3) to Liter (l)', path: './ft3-to-l' },
  { name: 'Cubic Foot (ft3) to Kiloliter (kl)', path: './ft3-to-kl' },
  { name: 'Cubic Foot (ft3) to Megaliter (Ml)', path: './ft3-to-Ml' },
  { name: 'Cubic Foot (ft3) to Gigaliter (Gl)', path: './ft3-to-Gl' },
  { name: 'Cubic Foot (ft3) to Cubic Meter (m³)', path: './ft3-to-m3' },
  { name: 'Cubic Foot (ft3) to Cubic Kilometer (km³)', path: './ft3-to-km3' },
  { name: 'Cubic Yard (yd3) to Cubic Millimeter (mm³)', path: './yd3-to-mm3' },
  { name: 'Cubic Yard (yd3) to Cubic Centimeter (cm³)', path: './yd3-to-cm3' },
  { name: 'Cubic Yard (yd3) to Milliliter (ml)', path: './yd3-to-ml' },
  { name: 'Cubic Yard (yd3) to Liter (l)', path: './yd3-to-l' },
  { name: 'Cubic Yard (yd3) to Kiloliter (kl)', path: './yd3-to-kl' },
  { name: 'Cubic Yard (yd3) to Megaliter (Ml)', path: './yd3-to-Ml' },
  { name: 'Cubic Yard (yd3) to Gigaliter (Gl)', path: './yd3-to-Gl' },
  { name: 'Cubic Yard (yd3) to Cubic Meter (m³)', path: './yd3-to-m3' },
  { name: 'Cubic Yard (yd3) to Cubic Kilometer (km³)', path: './yd3-to-km3' }
];
export const Length = [
  { "name": "Nanometer (nm) to Micrometer (μm)", "path": "./Nanometer-to-Micrometer" },
  { "name": "Nanometer (nm) to Millimeter (mm)", "path": "./Nanometer-to-Millimeter" },
  { "name": "Nanometer (nm) to Centimeter (cm)", "path": "./Nanometer-to-Centimeter" },
  { "name": "Nanometer (nm) to Meter (m)", "path": "./Nanometer-to-Meter" },
  { "name": "Nanometer (nm) to Kilometer (km)", "path": "./Nanometer-to-Kilometer" },
  { "name": "Micrometer (μm) to Millimeter (mm)", "path": "./Micrometer-to-Millimeter" },
  { "name": "Micrometer (μm) to Centimeter (cm)", "path": "./Micrometer-to-Centimeter" },
  { "name": "Micrometer (μm) to Meter (m)", "path": "./Micrometer-to-Meter" },
  { "name": "Micrometer (μm) to Kilometer (km)", "path": "./Micrometer-to-Kilometer" },
  { "name": "Millimeter (mm) to Centimeter (cm)", "path": "./Millimeter-to-Centimeter" },
  { "name": "Millimeter (mm) to Meter (m)", "path": "./Millimeter-to-Meter" },
  { "name": "Millimeter (mm) to Kilometer (km)", "path": "./Millimeter-to-Kilometer" },
  { "name": "Centimeter (cm) to Meter (m)", "path": "./Centimeter-to-Meter" },
  { "name": "Centimeter (cm) to Kilometer (km)", "path": "./Centimeter-to-Kilometer" },
  { "name": "Meter (m) to Kilometer (km)", "path": "./Meter-to-Kilometer" },
  { "name": "Nanometer (nm) to Inch (in)", "path": "./Nanometer-to-Inch" },
  { "name": "Nanometer (nm) to Yard (yd)", "path": "./Nanometer-to-Yard" },
  { "name": "Nanometer (nm) to Foot (US) (ft)", "path": "./Nanometer-to-Foot-us" },
  { "name": "Nanometer (nm) to Foot (ft)", "path": "./Nanometer-to-Foot" },
  { "name": "Nanometer (nm) to Fathom (fm)", "path": "./Nanometer-to-Fathom" },
  { "name": "Nanometer (nm) to Mile (mi)", "path": "./Nanometer-to-Mile" },
  { "name": "Nanometer (nm) to Nautical Mile (nmi)", "path": "./Nanometer-to-Nautical-mile" },
  { "name": "Micrometer (μm) to Inch (in)", "path": "./Micrometer-to-Inch" },
  { "name": "Micrometer (μm) to Yard (yd)", "path": "./Micrometer-to-Yard" },
  { "name": "Micrometer (μm) to Foot (US) (ft)", "path": "./Micrometer-to-Foot-us" },
  { "name": "Micrometer (μm) to Foot (ft)", "path": "./Micrometer-to-Foot" },
  { "name": "Micrometer (μm) to Fathom (fm)", "path": "./Micrometer-to-Fathom" },
  { "name": "Micrometer (μm) to Mile (mi)", "path": "./Micrometer-to-Mile" },
  { "name": "Micrometer (μm) to Nautical Mile (nmi)", "path": "./Micrometer-to-Nautical-mile" },
  { "name": "Millimeter (mm) to Inch (in)", "path": "./Millimeter-to-Inch" },
  { "name": "Millimeter (mm) to Yard (yd)", "path": "./Millimeter-to-Yard" },
  { "name": "Millimeter (mm) to Foot (US) (ft)", "path": "./Millimeter-to-Foot-us" },
  { "name": "Millimeter (mm) to Foot (ft)", "path": "./Millimeter-to-Foot" },
  { "name": "Millimeter (mm) to Fathom (fm)", "path": "./Millimeter-to-Fathom" },
  { "name": "Millimeter (mm) to Mile (mi)", "path": "./Millimeter-to-Mile" },
  { "name": "Millimeter (mm) to Nautical Mile (nmi)", "path": "./Millimeter-to-Nautical-mile" },
  { "name": "Centimeter (cm) to Inch (in)", "path": "./Centimeter-to-Inch" },
  { "name": "Centimeter (cm) to Yard (yd)", "path": "./Centimeter-to-Yard" },
  { "name": "Centimeter (cm) to Foot (US) (ft)", "path": "./Centimeter-to-Foot-us" },
  { "name": "Centimeter (cm) to Foot (ft)", "path": "./Centimeter-to-Foot" },
  { "name": "Centimeter (cm) to Fathom (fm)", "path": "./Centimeter-to-Fathom" },
  { "name": "Centimeter (cm) to Mile (mi)", "path": "./Centimeter-to-Mile" },
  { "name": "Centimeter (cm) to Nautical Mile (nmi)", "path": "./Centimeter-to-Nautical-mile" },
  { "name": "Meter (m) to Inch (in)", "path": "./Meter-to-Inch" },
  { "name": "Meter (m) to Yard (yd)", "path": "./Meter-to-Yard" },
  { "name": "Meter (m) to Foot (US) (ft)", "path": "./Meter-to-Foot-us" },
  { "name": "Meter (m) to Foot (ft)", "path": "./Meter-to-Foot" },
  { "name": "Meter (m) to Fathom (fm)", "path": "./Meter-to-Fathom" },
  { "name": "Meter (m) to Mile (mi)", "path": "./Meter-to-Mile" },
  { "name": "Meter (m) to Nautical Mile (nmi)", "path": "./Meter-to-Nautical-mile" },
  { "name": "Kilometer (km) to Inch (in)", "path": "./Kilometer-to-Inch" },
  { "name": "Kilometer (km) to Yard (yd)", "path": "./Kilometer-to-Yard" },
  { "name": "Kilometer (km) to Foot (US) (ft)", "path": "./Kilometer-to-Foot-us" },
  { "name": "Kilometer (km) to Foot (ft)", "path": "./Kilometer-to-Foot" },
  { "name": "Kilometer (km) to Fathom (fm)", "path": "./Kilometer-to-Fathom" },
  { "name": "Kilometer (km) to Mile (mi)", "path": "./Kilometer-to-Mile" },
  { "name": "Kilometer (km) to Nautical Mile (nmi)", "path": "./Kilometer-to-Nautical-mile" },
  { "name": "Inch (in) to Yard (yd)", "path": "./Inch-to-Yard" },
  { "name": "Inch (in) to Foot (US) (ft)", "path": "./Inch-to-Foot-us" },
  { "name": "Inch (in) to Foot (ft)", "path": "./Inch-to-Foot" },
  { "name": "Inch (in) to Fathom (fm)", "path": "./Inch-to-Fathom" },
  { "name": "Inch (in) to Mile (mi)", "path": "./Inch-to-Mile" },
  { "name": "Inch (in) to Nautical Mile (nmi)", "path": "./Inch-to-Nautical-mile" },
  { "name": "Yard (yd) to Foot (US) (ft)", "path": "./Yard-to-Foot-us" },
  { "name": "Yard (yd) to Foot (ft)", "path": "./Yard-to-Foot" },
  { "name": "Yard (yd) to Fathom (fm)", "path": "./Yard-to-Fathom" },
  { "name": "Yard (yd) to Mile (mi)", "path": "./Yard-to-Mile" },
  { "name": "Yard (yd) to Nautical Mile (nmi)", "path": "./Yard-to-Nautical-mile" },
  { "name": "Foot (US) (ft) to Foot (ft)", "path": "./Foot-us-to-Foot" },
  { "name": "Foot (US) (ft) to Fathom (fm)", "path": "./Foot-us-to-Fathom" },
  { "name": "Foot (US) (ft) to Mile (mi)", "path": "./Foot-us-to-Mile" },
  { "name": "Foot (US) (ft) to Nautical Mile (nmi)", "path": "./Foot-us-to-Nautical-mile" },
  { "name": "Foot (ft) to Fathom (fm)", "path": "./Foot-to-Fathom" },
  { "name": "Foot (ft) to Mile (mi)", "path": "./Foot-to-Mile" },
  { "name": "Foot (ft) to Nautical Mile (nmi)", "path": "./Foot-to-Nautical-mile" },
  { "name": "Fathom (fm) to Mile (mi)", "path": "./Fathom-to-Mile" },
  { "name": "Fathom (fm) to Nautical Mile (nmi)", "path": "./Fathom-to-Nautical-mile" },
  { "name": "Mile (mi) to Nautical Mile (nmi)", "path": "./Mile-to-Nautical-mile" }
]
export const Speed = [
  { name: 'Meter per Second (m/s) to Kilometer per Hour (km/h)', path: './m_s-to-km_h' },
  { name: 'Meter per Second (m/s) to Mile per Hour (mph)', path: './m_s-to-mph' },
  { name: 'Meter per Second (m/s) to Knot', path: './m_s-to-knot' },
  { name: 'Meter per Second (m/s) to Foot per Second (ft/s)', path: './m_s-to-ft_s' },
  { name: 'Meter per Second (m/s) to Inch per Hour (in/h)', path: './m_s-to-in_h' },
  { name: 'Meter per Second (m/s) to Millimeter per Hour (mm/h)', path: './m_s-to-mm_h' },
  { name: 'Kilometer per Hour (km/h) to Meter per Second (m/s)', path: './km_h-to-m_s' },
  { name: 'Kilometer per Hour (km/h) to Mile per Hour (mph)', path: './km_h-to-mph' },
  { name: 'Kilometer per Hour (km/h) to Knot', path: './km_h-to-knot' },
  { name: 'Kilometer per Hour (km/h) to Foot per Second (ft/s)', path: './km_h-to-ft_s' },
  { name: 'Kilometer per Hour (km/h) to Inch per Hour (in/h)', path: './km_h-to-in_h' },
  { name: 'Kilometer per Hour (km/h) to Millimeter per Hour (mm/h)', path: './km_h-to-mm_h' },
  { name: 'Mile per Hour (mph) to Meter per Second (m/s)', path: './mph-to-m_s' },
  { name: 'Mile per Hour (mph) to Kilometer per Hour (km/h)', path: './mph-to-km_h' },
  { name: 'Mile per Hour (mph) to Knot', path: './mph-to-knot' },
  { name: 'Mile per Hour (mph) to Foot per Second (ft/s)', path: './mph-to-ft_s' },
  { name: 'Mile per Hour (mph) to Inch per Hour (in/h)', path: './mph-to-in_h' },
  { name: 'Mile per Hour (mph) to Millimeter per Hour (mm/h)', path: './mph-to-mm_h' },
  { name: 'Knot to Meter per Second (m/s)', path: './knot-to-m_s' },
  { name: 'Knot to Kilometer per Hour (km/h)', path: './knot-to-km_h' },
  { name: 'Knot to Mile per Hour (mph)', path: './knot-to-mph' },
  { name: 'Knot to Foot per Second (ft/s)', path: './knot-to-ft_s' },
  { name: 'Knot to Inch per Hour (in/h)', path: './knot-to-in_h' },
  { name: 'Knot to Millimeter per Hour (mm/h)', path: './knot-to-mm_h' },
  { name: 'Foot per Second (ft/s) to Meter per Second (m/s)', path: './ft_s-to-m_s' },
  { name: 'Foot per Second (ft/s) to Kilometer per Hour (km/h)', path: './ft_s-to-km_h' },
  { name: 'Foot per Second (ft/s) to Mile per Hour (mph)', path: './ft_s-to-mph' },
  { name: 'Foot per Second (ft/s) to Knot', path: './ft_s-to-knot' },
  { name: 'Foot per Second (ft/s) to Inch per Hour (in/h)', path: './ft_s-to-in_h' },
  { name: 'Foot per Second (ft/s) to Millimeter per Hour (mm/h)', path: './ft_s-to-mm_h' },
  { name: 'Inch per Hour (in/h) to Meter per Second (m/s)', path: './in_h-to-m_s' },
  { name: 'Inch per Hour (in/h) to Kilometer per Hour (km/h)', path: './in_h-to-km_h' },
  { name: 'Inch per Hour (in/h) to Mile per Hour (mph)', path: './in_h-to-mph' },
  { name: 'Inch per Hour (in/h) to Knot', path: './in_h-to-knot' },
  { name: 'Inch per Hour (in/h) to Foot per Second (ft/s)', path: './in_h-to-ft_s' },
  { name: 'Inch per Hour (in/h) to Millimeter per Hour (mm/h)', path: './in_h-to-mm_h' },
  { name: 'Millimeter per Hour (mm/h) to Meter per Second (m/s)', path: './mm_h-to-m_s' },
  { name: 'Millimeter per Hour (mm/h) to Kilometer per Hour (km/h)', path: './mm_h-to-km_h' },
  { name: 'Millimeter per Hour (mm/h) to Mile per Hour (mph)', path: './mm_h-to-mph' },
  { name: 'Millimeter per Hour (mm/h) to Knot', path: './mm_h-to-knot' },
  { name: 'Millimeter per Hour (mm/h) to Foot per Second (ft/s)', path: './mm_h-to-ft_s' },
  { name: 'Millimeter per Hour (mm/h) to Inch per Hour (in/h)', path: './mm_h-to-in_h' }
];
export const Pressure = [
  { name: 'Pascal (Pa) to Hectopascal (hPa)', path: './Pa-to-hPa' },
  { name: 'Pascal (Pa) to Kilopascal (kPa)', path: './Pa-to-kPa' },
  { name: 'Pascal (Pa) to Megapascal (MPa)', path: './Pa-to-MPa' },
  { name: 'Pascal (Pa) to Bar', path: './Pa-to-bar' },
  { name: 'Pascal (Pa) to Torr', path: './Pa-to-torr' },
  { name: 'Pascal (Pa) to Meter of Water (mH2O)', path: './Pa-to-mH2O' },
  { name: 'Pascal (Pa) to Millimeter of Mercury (mmHg)', path: './Pa-to-mmHg' },
  { name: 'Pascal (Pa) to Pound per Square Inch (psi)', path: './Pa-to-psi' },
  { name: 'Pascal (Pa) to Kilopound per Square Inch (ksi)', path: './Pa-to-ksi' },
  { name: 'Hectopascal (hPa) to Pascal (Pa)', path: './hPa-to-Pa' },
  { name: 'Hectopascal (hPa) to Kilopascal (kPa)', path: './hPa-to-kPa' },
  { name: 'Hectopascal (hPa) to Megapascal (MPa)', path: './hPa-to-MPa' },
  { name: 'Hectopascal (hPa) to Bar', path: './hPa-to-bar' },
  { name: 'Hectopascal (hPa) to Torr', path: './hPa-to-torr' },
  { name: 'Hectopascal (hPa) to Meter of Water (mH2O)', path: './hPa-to-mH2O' },
  { name: 'Hectopascal (hPa) to Millimeter of Mercury (mmHg)', path: './hPa-to-mmHg' },
  { name: 'Hectopascal (hPa) to Pound per Square Inch (psi)', path: './hPa-to-psi' },
  { name: 'Hectopascal (hPa) to Kilopound per Square Inch (ksi)', path: './hPa-to-ksi' },
  { name: 'Kilopascal (kPa) to Pascal (Pa)', path: './kPa-to-Pa' },
  { name: 'Kilopascal (kPa) to Hectopascal (hPa)', path: './kPa-to-hPa' },
  { name: 'Kilopascal (kPa) to Megapascal (MPa)', path: './kPa-to-MPa' },
  { name: 'Kilopascal (kPa) to Bar', path: './kPa-to-bar' },
  { name: 'Kilopascal (kPa) to Torr', path: './kPa-to-torr' },
  { name: 'Kilopascal (kPa) to Meter of Water (mH2O)', path: './kPa-to-mH2O' },
  { name: 'Kilopascal (kPa) to Millimeter of Mercury (mmHg)', path: './kPa-to-mmHg' },
  { name: 'Kilopascal (kPa) to Pound per Square Inch (psi)', path: './kPa-to-psi' },
  { name: 'Kilopascal (kPa) to Kilopound per Square Inch (ksi)', path: './kPa-to-ksi' },
  { name: 'Megapascal (MPa) to Pascal (Pa)', path: './MPa-to-Pa' },
  { name: 'Megapascal (MPa) to Hectopascal (hPa)', path: './MPa-to-hPa' },
  { name: 'Megapascal (MPa) to Kilopascal (kPa)', path: './MPa-to-kPa' },
  { name: 'Megapascal (MPa) to Bar', path: './MPa-to-bar' },
  { name: 'Megapascal (MPa) to Torr', path: './MPa-to-torr' },
  { name: 'Megapascal (MPa) to Meter of Water (mH2O)', path: './MPa-to-mH2O' },
  { name: 'Megapascal (MPa) to Millimeter of Mercury (mmHg)', path: './MPa-to-mmHg' },
  { name: 'Megapascal (MPa) to Pound per Square Inch (psi)', path: './MPa-to-psi' },
  { name: 'Megapascal (MPa) to Kilopound per Square Inch (ksi)', path: './MPa-to-ksi' },
  { name: 'Bar to Pascal (Pa)', path: './bar-to-Pa' },
  { name: 'Bar to Hectopascal (hPa)', path: './bar-to-hPa' },
  { name: 'Bar to Kilopascal (kPa)', path: './bar-to-kPa' },
  { name: 'Bar to Megapascal (MPa)', path: './bar-to-MPa' },
  { name: 'Bar to Torr', path: './bar-to-torr' },
  { name: 'Bar to Meter of Water (mH2O)', path: './bar-to-mH2O' },
  { name: 'Bar to Millimeter of Mercury (mmHg)', path: './bar-to-mmHg' },
  { name: 'Bar to Pound per Square Inch (psi)', path: './bar-to-psi' },
  { name: 'Bar to Kilopound per Square Inch (ksi)', path: './bar-to-ksi' },
  { name: 'Torr to Pascal (Pa)', path: './torr-to-Pa' },
  { name: 'Torr to Hectopascal (hPa)', path: './torr-to-hPa' },
  { name: 'Torr to Kilopascal (kPa)', path: './torr-to-kPa' },
  { name: 'Torr to Megapascal (MPa)', path: './torr-to-MPa' },
  { name: 'Torr to Bar', path: './torr-to-bar' },
  { name: 'Torr to Meter of Water (mH2O)', path: './torr-to-mH2O' },
  { name: 'Torr to Millimeter of Mercury (mmHg)', path: './torr-to-mmHg' },
  { name: 'Torr to Pound per Square Inch (psi)', path: './torr-to-psi' },
  { name: 'Torr to Kilopound per Square Inch (ksi)', path: './torr-to-ksi' },
  { name: 'Meter of Water (mH2O) to Pascal (Pa)', path: './mH2O-to-Pa' },
  { name: 'Meter of Water (mH2O) to Hectopascal (hPa)', path: './mH2O-to-hPa' },
  { name: 'Meter of Water (mH2O) to Kilopascal (kPa)', path: './mH2O-to-kPa' },
  { name: 'Meter of Water (mH2O) to Megapascal (MPa)', path: './mH2O-to-MPa' },
  { name: 'Meter of Water (mH2O) to Bar', path: './mH2O-to-bar' },
  { name: 'Meter of Water (mH2O) to Torr', path: './mH2O-to-torr' },
  { name: 'Meter of Water (mH2O) to Millimeter of Mercury (mmHg)', path: './mH2O-to-mmHg' },
  { name: 'Meter of Water (mH2O) to Pound per Square Inch (psi)', path: './mH2O-to-psi' },
  { name: 'Meter of Water (mH2O) to Kilopound per Square Inch (ksi)', path: './mH2O-to-ksi' },
  { name: 'Millimeter of Mercury (mmHg) to Pascal (Pa)', path: './mmHg-to-Pa' },
  { name: 'Millimeter of Mercury (mmHg) to Hectopascal (hPa)', path: './mmHg-to-hPa' },
  { name: 'Millimeter of Mercury (mmHg) to Kilopascal (kPa)', path: './mmHg-to-kPa' },
  { name: 'Millimeter of Mercury (mmHg) to Megapascal (MPa)', path: './mmHg-to-MPa' },
  { name: 'Millimeter of Mercury (mmHg) to Bar', path: './mmHg-to-bar' },
  { name: 'Millimeter of Mercury (mmHg) to Torr', path: './mmHg-to-torr' },
  { name: 'Millimeter of Mercury (mmHg) to Meter of Water (mH2O)', path: './mmHg-to-mH2O' },
  { name: 'Millimeter of Mercury (mmHg) to Pound per Square Inch (psi)', path: './mmHg-to-psi' },
  { name: 'Millimeter of Mercury (mmHg) to Kilopound per Square Inch (ksi)', path: './mmHg-to-ksi' },
  { name: 'Pound per Square Inch (psi) to Pascal (Pa)', path: './psi-to-Pa' },
  { name: 'Pound per Square Inch (psi) to Hectopascal (hPa)', path: './psi-to-hPa' },
  { name: 'Pound per Square Inch (psi) to Kilopascal (kPa)', path: './psi-to-kPa' },
  { name: 'Pound per Square Inch (psi) to Megapascal (MPa)', path: './psi-to-MPa' },
  { name: 'Pound per Square Inch (psi) to Bar', path: './psi-to-bar' },
  { name: 'Pound per Square Inch (psi) to Torr', path: './psi-to-torr' },
  { name: 'Pound per Square Inch (psi) to Meter of Water (mH2O)', path: './psi-to-mH2O' },
  { name: 'Pound per Square Inch (psi) to Millimeter of Mercury (mmHg)', path: './psi-to-mmHg' },
  { name: 'Pound per Square Inch (psi) to Kilopound per Square Inch (ksi)', path: './psi-to-ksi' },
  { name: 'Kilopound per Square Inch (ksi) to Pascal (Pa)', path: './ksi-to-Pa' },
  { name: 'Kilopound per Square Inch (ksi) to Hectopascal (hPa)', path: './ksi-to-hPa' },
  { name: 'Kilopound per Square Inch (ksi) to Kilopascal (kPa)', path: './ksi-to-kPa' },
  { name: 'Kilopound per Square Inch (ksi) to Megapascal (MPa)', path: './ksi-to-MPa' },
  { name: 'Kilopound per Square Inch (ksi) to Bar', path: './ksi-to-bar' },
  { name: 'Kilopound per Square Inch (ksi) to Torr', path: './ksi-to-torr' },
  { name: 'Kilopound per Square Inch (ksi) to Meter of Water (mH2O)', path: './ksi-to-mH2O' },
  { name: 'Kilopound per Square Inch (ksi) to Millimeter of Mercury (mmHg)', path: './ksi-to-mmHg' },
  { name: 'Kilopound per Square Inch (ksi) to Pound per Square Inch (psi)', path: './ksi-to-psi' }
];
export const Digital = [
  { name: 'Bit to Byte', path: './bit-to-byte' },
  { name: 'Bit to Kilobit (kb)', path: './bit-to-kb' },
  { name: 'Bit to Megabit (Mb)', path: './bit-to-Mb' },
  { name: 'Bit to Gigabit (Gb)', path: './bit-to-Gb' },
  { name: 'Bit to Terabit (Tb)', path: './bit-to-Tb' },
  { name: 'Bit to Kilobyte (kB)', path: './bit-to-kB' },
  { name: 'Bit to Megabyte (MB)', path: './bit-to-MB' },
  { name: 'Bit to Gigabyte (GB)', path: './bit-to-GB' },
  { name: 'Bit to Terabyte (TB)', path: './bit-to-TB' },
  { name: 'Bit to Kibibyte (KiB)', path: './bit-to-KiB' },
  { name: 'Bit to Mebibyte (MiB)', path: './bit-to-MiB' },
  { name: 'Bit to Gibibyte (GiB)', path: './bit-to-GiB' },
  { name: 'Bit to Tebibyte (TiB)', path: './bit-to-TiB' },
  { name: 'Byte to Bit', path: './byte-to-bit' },
  { name: 'Byte to Kilobit (kb)', path: './byte-to-kb' },
  { name: 'Byte to Megabit (Mb)', path: './byte-to-Mb' },
  { name: 'Byte to Gigabit (Gb)', path: './byte-to-Gb' },
  { name: 'Byte to Terabit (Tb)', path: './byte-to-Tb' },
  { name: 'Byte to Kilobyte (kB)', path: './byte-to-kB' },
  { name: 'Byte to Megabyte (MB)', path: './byte-to-MB' },
  { name: 'Byte to Gigabyte (GB)', path: './byte-to-GB' },
  { name: 'Byte to Terabyte (TB)', path: './byte-to-TB' },
  { name: 'Byte to Kibibyte (KiB)', path: './byte-to-KiB' },
  { name: 'Byte to Mebibyte (MiB)', path: './byte-to-MiB' },
  { name: 'Byte to Gibibyte (GiB)', path: './byte-to-GiB' },
  { name: 'Byte to Tebibyte (TiB)', path: './byte-to-TiB' },
  { name: 'Kilobit (kb) to Bit', path: './kb-to-bit' },
  { name: 'Kilobit (kb) to Byte', path: './kb-to-byte' },
  { name: 'Kilobit (kb) to Megabit (Mb)', path: './kb-to-Mb' },
  { name: 'Kilobit (kb) to Gigabit (Gb)', path: './kb-to-Gb' },
  { name: 'Kilobit (kb) to Terabit (Tb)', path: './kb-to-Tb' },
  { name: 'Kilobit (kb) to Kilobyte (kB)', path: './kb-to-kB' },
  { name: 'Kilobit (kb) to Megabyte (MB)', path: './kb-to-MB' },
  { name: 'Kilobit (kb) to Gigabyte (GB)', path: './kb-to-GB' },
  { name: 'Kilobit (kb) to Terabyte (TB)', path: './kb-to-TB' },
  { name: 'Kilobit (kb) to Kibibyte (KiB)', path: './kb-to-KiB' },
  { name: 'Kilobit (kb) to Mebibyte (MiB)', path: './kb-to-MiB' },
  { name: 'Kilobit (kb) to Gibibyte (GiB)', path: './kb-to-GiB' },
  { name: 'Kilobit (kb) to Tebibyte (TiB)', path: './kb-to-TiB' },
  { name: 'Megabit (Mb) to Bit', path: './Mb-to-bit' },
  { name: 'Megabit (Mb) to Byte', path: './Mb-to-byte' },
  { name: 'Megabit (Mb) to Kilobit (kb)', path: './Mb-to-kb' },
  { name: 'Megabit (Mb) to Gigabit (Gb)', path: './Mb-to-Gb' },
  { name: 'Megabit (Mb) to Terabit (Tb)', path: './Mb-to-Tb' },
  { name: 'Megabit (Mb) to Kilobyte (kB)', path: './Mb-to-kB' },
  { name: 'Megabit (Mb) to Megabyte (MB)', path: './Mb-to-MB' },
  { name: 'Megabit (Mb) to Gigabyte (GB)', path: './Mb-to-GB' },
  { name: 'Megabit (Mb) to Terabyte (TB)', path: './Mb-to-TB' },
  { name: 'Megabit (Mb) to Kibibyte (KiB)', path: './Mb-to-KiB' },
  { name: 'Megabit (Mb) to Mebibyte (MiB)', path: './Mb-to-MiB' },
  { name: 'Megabit (Mb) to Gibibyte (GiB)', path: './Mb-to-GiB' },
  { name: 'Megabit (Mb) to Tebibyte (TiB)', path: './Mb-to-TiB' },
  { name: 'Gigabit (Gb) to Bit', path: './Gb-to-bit' },
  { name: 'Gigabit (Gb) to Byte', path: './Gb-to-byte' },
  { name: 'Gigabit (Gb) to Kilobit (kb)', path: './Gb-to-kb' },
  { name: 'Gigabit (Gb) to Megabit (Mb)', path: './Gb-to-Mb' },
  { name: 'Gigabit (Gb) to Terabit (Tb)', path: './Gb-to-Tb' },
  { name: 'Gigabit (Gb) to Kilobyte (kB)', path: './Gb-to-kB' },
  { name: 'Gigabit (Gb) to Megabyte (MB)', path: './Gb-to-MB' },
  { name: 'Gigabit (Gb) to Gigabyte (GB)', path: './Gb-to-GB' },
  { name: 'Gigabit (Gb) to Terabyte (TB)', path: './Gb-to-TB' },
  { name: 'Gigabit (Gb) to Kibibyte (KiB)', path: './Gb-to-KiB' },
  { name: 'Gigabit (Gb) to Mebibyte (MiB)', path: './Gb-to-MiB' },
  { name: 'Gigabit (Gb) to Gibibyte (GiB)', path: './Gb-to-GiB' },
  { name: 'Gigabit (Gb) to Tebibyte (TiB)', path: './Gb-to-TiB' },
  { name: 'Terabit (Tb) to Bit', path: './Tb-to-bit' },
  { name: 'Terabit (Tb) to Byte', path: './Tb-to-byte' },
  { name: 'Terabit (Tb) to Kilobit (kb)', path: './Tb-to-kb' },
  { name: 'Terabit (Tb) to Megabit (Mb)', path: './Tb-to-Mb' },
  { name: 'Terabit (Tb) to Gigabit (Gb)', path: './Tb-to-Gb' },
  { name: 'Terabit (Tb) to Kilobyte (kB)', path: './Tb-to-kB' },
  { name: 'Terabit (Tb) to Megabyte (MB)', path: './Tb-to-MB' },
  { name: 'Terabit (Tb) to Gigabyte (GB)', path: './Tb-to-GB' },
  { name: 'Terabit (Tb) to Terabyte (TB)', path: './Tb-to-TB' },
  { name: 'Terabit (Tb) to Kibibyte (KiB)', path: './Tb-to-KiB' },
  { name: 'Terabit (Tb) to Mebibyte (MiB)', path: './Tb-to-MiB' },
  { name: 'Terabit (Tb) to Gibibyte (GiB)', path: './Tb-to-GiB' },
  { name: 'Terabit (Tb) to Tebibyte (TiB)', path: './Tb-to-TiB' },
  { name: 'Kilobyte (kB) to Bit', path: './kB-to-bit' },
  { name: 'Kilobyte (kB) to Byte', path: './kB-to-byte' },
  { name: 'Kilobyte (kB) to Kilobit (kb)', path: './kB-to-kb' },
  { name: 'Kilobyte (kB) to Megabit (Mb)', path: './kB-to-Mb' },
  { name: 'Kilobyte (kB) to Gigabit (Gb)', path: './kB-to-Gb' },
  { name: 'Kilobyte (kB) to Terabit (Tb)', path: './kB-to-Tb' },
  { name: 'Kilobyte (kB) to Megabyte (MB)', path: './kB-to-MB' },
  { name: 'Kilobyte (kB) to Gigabyte (GB)', path: './kB-to-GB' },
  { name: 'Kilobyte (kB) to Terabyte (TB)', path: './kB-to-TB' },
  { name: 'Kilobyte (kB) to Kibibyte (KiB)', path: './kB-to-KiB' },
  { name: 'Kilobyte (kB) to Mebibyte (MiB)', path: './kB-to-MiB' },
  { name: 'Kilobyte (kB) to Gibibyte (GiB)', path: './kB-to-GiB' },
  { name: 'Kilobyte (kB) to Tebibyte (TiB)', path: './kB-to-TiB' },
  { name: 'Megabyte (MB) to Bit', path: './MB-to-bit' },
  { name: 'Megabyte (MB) to Byte', path: './MB-to-byte' },
  { name: 'Megabyte (MB) to Kilobit (kb)', path: './MB-to-kb' },
  { name: 'Megabyte (MB) to Megabit (Mb)', path: './MB-to-Mb' },
  { name: 'Megabyte (MB) to Gigabit (Gb)', path: './MB-to-Gb' },
  { name: 'Megabyte (MB) to Terabit (Tb)', path: './MB-to-Tb' },
  { name: 'Megabyte (MB) to Kilobyte (kB)', path: './MB-to-kB' },
  { name: 'Megabyte (MB) to Gigabyte (GB)', path: './MB-to-GB' },
  { name: 'Megabyte (MB) to Terabyte (TB)', path: './MB-to-TB' },
  { name: 'Megabyte (MB) to Kibibyte (KiB)', path: './MB-to-KiB' },
  { name: 'Megabyte (MB) to Mebibyte (MiB)', path: './MB-to-MiB' },
  { name: 'Megabyte (MB) to Gibibyte (GiB)', path: './MB-to-GiB' },
  { name: 'Megabyte (MB) to Tebibyte (TiB)', path: './MB-to-TiB' },
  { name: 'Gigabyte (GB) to Bit', path: './GB-to-bit' },
  { name: 'Gigabyte (GB) to Byte', path: './GB-to-byte' },
  { name: 'Gigabyte (GB) to Kilobit (kb)', path: './GB-to-kb' },
  { name: 'Gigabyte (GB) to Megabit (Mb)', path: './GB-to-Mb' },
  { name: 'Gigabyte (GB) to Gigabit (Gb)', path: './GB-to-Gb' },
  { name: 'Gigabyte (GB) to Terabit (Tb)', path: './GB-to-Tb' },
  { name: 'Gigabyte (GB) to Kilobyte (kB)', path: './GB-to-kB' },
  { name: 'Gigabyte (GB) to Megabyte (MB)', path: './GB-to-MB' },
  { name: 'Gigabyte (GB) to Terabyte (TB)', path: './GB-to-TB' },
  { name: 'Gigabyte (GB) to Kibibyte (KiB)', path: './GB-to-KiB' },
  { name: 'Gigabyte (GB) to Mebibyte (MiB)', path: './GB-to-MiB' },
  { name: 'Gigabyte (GB) to Gibibyte (GiB)', path: './GB-to-GiB' },
  { name: 'Gigabyte (GB) to Tebibyte (TiB)', path: './GB-to-TiB' },
  { name: 'Terabyte (TB) to Bit', path: './TB-to-bit' },
  { name: 'Terabyte (TB) to Byte', path: './TB-to-byte' },
  { name: 'Terabyte (TB) to Kilobit (kb)', path: './TB-to-kb' },
  { name: 'Terabyte (TB) to Megabit (Mb)', path: './TB-to-Mb' },
  { name: 'Terabyte (TB) to Gigabit (Gb)', path: './TB-to-Gb' },
  { name: 'Terabyte (TB) to Terabit (Tb)', path: './TB-to-Tb' },
  { name: 'Terabyte (TB) to Kilobyte (kB)', path: './TB-to-kB' },
  { name: 'Terabyte (TB) to Megabyte (MB)', path: './TB-to-MB' },
  { name: 'Terabyte (TB) to Gigabyte (GB)', path: './TB-to-GB' },
  { name: 'Terabyte (TB) to Kibibyte (KiB)', path: './TB-to-KiB' },
  { name: 'Terabyte (TB) to Mebibyte (MiB)', path: './TB-to-MiB' },
  { name: 'Terabyte (TB) to Gibibyte (GiB)', path: './TB-to-GiB' },
  { name: 'Terabyte (TB) to Tebibyte (TiB)', path: './TB-to-TiB' },
  { name: 'Kibibyte (KiB) to Bit', path: './KiB-to-bit' },
  { name: 'Kibibyte (KiB) to Byte', path: './KiB-to-byte' },
  { name: 'Kibibyte (KiB) to Kilobit (kb)', path: './KiB-to-kb' },
  { name: 'Kibibyte (KiB) to Megabit (Mb)', path: './KiB-to-Mb' },
  { name: 'Kibibyte (KiB) to Gigabit (Gb)', path: './KiB-to-Gb' },
  { name: 'Kibibyte (KiB) to Terabit (Tb)', path: './KiB-to-Tb' },
  { name: 'Kibibyte (KiB) to Kilobyte (kB)', path: './KiB-to-kB' },
  { name: 'Kibibyte (KiB) to Megabyte (MB)', path: './KiB-to-MB' },
  { name: 'Kibibyte (KiB) to Gigabyte (GB)', path: './KiB-to-GB' },
  { name: 'Kibibyte (KiB) to Terabyte (TB)', path: './KiB-to-TB' },
  { name: 'Kibibyte (KiB) to Mebibyte (MiB)', path: './KiB-to-MiB' },
  { name: 'Kibibyte (KiB) to Gibibyte (GiB)', path: './KiB-to-GiB' },
  { name: 'Kibibyte (KiB) to Tebibyte (TiB)', path: './KiB-to-TiB' },
  { name: 'Mebibyte (MiB) to Bit', path: './MiB-to-bit' },
  { name: 'Mebibyte (MiB) to Byte', path: './MiB-to-byte' },
  { name: 'Mebibyte (MiB) to Kilobit (kb)', path: './MiB-to-kb' },
  { name: 'Mebibyte (MiB) to Megabit (Mb)', path: './MiB-to-Mb' },
  { name: 'Mebibyte (MiB) to Gigabit (Gb)', path: './MiB-to-Gb' },
  { name: 'Mebibyte (MiB) to Terabit (Tb)', path: './MiB-to-Tb' },
  { name: 'Mebibyte (MiB) to Kilobyte (kB)', path: './MiB-to-kB' },
  { name: 'Mebibyte (MiB) to Megabyte (MB)', path: './MiB-to-MB' },
  { name: 'Mebibyte (MiB) to Gigabyte (GB)', path: './MiB-to-GB' },
  { name: 'Mebibyte (MiB) to Terabyte (TB)', path: './MiB-to-TB' },
  { name: 'Mebibyte (MiB) to Kibibyte (KiB)', path: './MiB-to-KiB' },
  { name: 'Mebibyte (MiB) to Gibibyte (GiB)', path: './MiB-to-GiB' },
  { name: 'Mebibyte (MiB) to Tebibyte (TiB)', path: './MiB-to-TiB' },
  { name: 'Gibibyte (GiB) to Bit', path: './GiB-to-bit' },
  { name: 'Gibibyte (GiB) to Byte', path: './GiB-to-byte' },
  { name: 'Gibibyte (GiB) to Kilobit (kb)', path: './GiB-to-kb' },
  { name: 'Gibibyte (GiB) to Megabit (Mb)', path: './GiB-to-Mb' },
  { name: 'Gibibyte (GiB) to Gigabit (Gb)', path: './GiB-to-Gb' },
  { name: 'Gibibyte (GiB) to Terabit (Tb)', path: './GiB-to-Tb' },
  { name: 'Gibibyte (GiB) to Kilobyte (kB)', path: './GiB-to-kB' },
  { name: 'Gibibyte (GiB) to Megabyte (MB)', path: './GiB-to-MB' },
  { name: 'Gibibyte (GiB) to Gigabyte (GB)', path: './GiB-to-GB' },
  { name: 'Gibibyte (GiB) to Terabyte (TB)', path: './GiB-to-TB' },
  { name: 'Gibibyte (GiB) to Kibibyte (KiB)', path: './GiB-to-KiB' },
  { name: 'Gibibyte (GiB) to Mebibyte (MiB)', path: './GiB-to-MiB' },
  { name: 'Gibibyte (GiB) to Tebibyte (TiB)', path: './GiB-to-TiB' },
  { name: 'Tebibyte (TiB) to Bit', path: './TiB-to-bit' },
  { name: 'Tebibyte (TiB) to Byte', path: './TiB-to-byte' },
  { name: 'Tebibyte (TiB) to Kilobit (kb)', path: './TiB-to-kb' },
  { name: 'Tebibyte (TiB) to Megabit (Mb)', path: './TiB-to-Mb' },
  { name: 'Tebibyte (TiB) to Gigabit (Gb)', path: './TiB-to-Gb' },
  { name: 'Tebibyte (TiB) to Terabit (Tb)', path: './TiB-to-Tb' },
  { name: 'Tebibyte (TiB) to Kilobyte (kB)', path: './TiB-to-kB' },
  { name: 'Tebibyte (TiB) to Megabyte (MB)', path: './TiB-to-MB' },
  { name: 'Tebibyte (TiB) to Gigabyte (GB)', path: './TiB-to-GB' },
  { name: 'Tebibyte (TiB) to Terabyte (TB)', path: './TiB-to-TB' },
  { name: 'Tebibyte (TiB) to Kibibyte (KiB)', path: './TiB-to-KiB' },
  { name: 'Tebibyte (TiB) to Mebibyte (MiB)', path: './TiB-to-MiB' },
  { name: 'Tebibyte (TiB) to Gibibyte (GiB)', path: './TiB-to-GiB' }
];
export const Voltage = [
  { name: 'Volt (V) to Millivolt (mV)', path: './V-to-mV' },
  { name: 'Volt (V) to Kilovolt (kV)', path: './V-to-kV' },
  { name: 'Millivolt (mV) to Volt (V)', path: './mV-to-V' },
  { name: 'Millivolt (mV) to Kilovolt (kV)', path: './mV-to-kV' },
  { name: 'Kilovolt (kV) to Volt (V)', path: './kV-to-V' },
  { name: 'Kilovolt (kV) to Millivolt (mV)', path: './kV-to-mV' }
];
export const Current = [
  { name: 'Ampere (A) to Milliampere (mA)', path: './A-to-mA' },
  { name: 'Ampere (A) to Kiloampere (kA)', path: './A-to-kA' },
  { name: 'Milliampere (mA) to Ampere (A)', path: './mA-to-A' },
  { name: 'Milliampere (mA) to Kiloampere (kA)', path: './mA-to-kA' },
  { name: 'Kiloampere (kA) to Ampere (A)', path: './kA-to-A' },
  { name: 'Kiloampere (kA) to Milliampere (mA)', path: './kA-to-mA' }
];
export const Power = [
  { name: 'Watt (W) to Milliwatt (mW)', path: './W-to-mW' },
  { name: 'Watt (W) to Kilowatt (kW)', path: './W-to-kW' },
  { name: 'Watt (W) to Megawatt (MW)', path: './W-to-MW' },
  { name: 'Watt (W) to Gigawatt (GW)', path: './W-to-GW' },
  { name: 'Watt (W) to Horsepower (PS)', path: './W-to-PS' },
  { name: 'Watt (W) to BTU per Second (Btu/s)', path: './W-to-Btu_s' },
  { name: 'Watt (W) to Foot-pound per Second (ft-lb/s)', path: './W-to-ft-lb_s' },
  { name: 'Watt (W) to Horsepower (hp)', path: './W-to-hp' },
  { name: 'Milliwatt (mW) to Watt (W)', path: './mW-to-W' },
  { name: 'Milliwatt (mW) to Kilowatt (kW)', path: './mW-to-kW' },
  { name: 'Milliwatt (mW) to Megawatt (MW)', path: './mW-to-MW' },
  { name: 'Milliwatt (mW) to Gigawatt (GW)', path: './mW-to-GW' },
  { name: 'Milliwatt (mW) to Horsepower (PS)', path: './mW-to-PS' },
  { name: 'Milliwatt (mW) to BTU per Second (Btu/s)', path: './mW-to-Btu_s' },
  { name: 'Milliwatt (mW) to Foot-pound per Second (ft-lb/s)', path: './mW-to-ft-lb_s' },
  { name: 'Milliwatt (mW) to Horsepower (hp)', path: './mW-to-hp' },
  { name: 'Kilowatt (kW) to Watt (W)', path: './kW-to-W' },
  { name: 'Kilowatt (kW) to Milliwatt (mW)', path: './kW-to-mW' },
  { name: 'Kilowatt (kW) to Megawatt (MW)', path: './kW-to-MW' },
  { name: 'Kilowatt (kW) to Gigawatt (GW)', path: './kW-to-GW' },
  { name: 'Kilowatt (kW) to Horsepower (PS)', path: './kW-to-PS' },
  { name: 'Kilowatt (kW) to BTU per Second (Btu/s)', path: './kW-to-Btu_s' },
  { name: 'Kilowatt (kW) to Foot-pound per Second (ft-lb/s)', path: './kW-to-ft-lb_s' },
  { name: 'Kilowatt (kW) to Horsepower (hp)', path: './kW-to-hp' },
  { name: 'Megawatt (MW) to Watt (W)', path: './MW-to-W' },
  { name: 'Megawatt (MW) to Milliwatt (mW)', path: './MW-to-mW' },
  { name: 'Megawatt (MW) to Kilowatt (kW)', path: './MW-to-kW' },
  { name: 'Megawatt (MW) to Gigawatt (GW)', path: './MW-to-GW' },
  { name: 'Megawatt (MW) to Horsepower (PS)', path: './MW-to-PS' },
  { name: 'Megawatt (MW) to BTU per Second (Btu/s)', path: './MW-to-Btu_s' },
  { name: 'Megawatt (MW) to Foot-pound per Second (ft-lb/s)', path: './MW-to-ft-lb_s' },
  { name: 'Megawatt (MW) to Horsepower (hp)', path: './MW-to-hp' },
  { name: 'Gigawatt (GW) to Watt (W)', path: './GW-to-W' },
  { name: 'Gigawatt (GW) to Milliwatt (mW)', path: './GW-to-mW' },
  { name: 'Gigawatt (GW) to Kilowatt (kW)', path: './GW-to-kW' },
  { name: 'Gigawatt (GW) to Megawatt (MW)', path: './GW-to-MW' },
  { name: 'Gigawatt (GW) to Horsepower (PS)', path: './GW-to-PS' },
  { name: 'Gigawatt (GW) to BTU per Second (Btu/s)', path: './GW-to-Btu_s' },
  { name: 'Gigawatt (GW) to Foot-pound per Second (ft-lb/s)', path: './GW-to-ft-lb_s' },
  { name: 'Gigawatt (GW) to Horsepower (hp)', path: './GW-to-hp' },
  { name: 'Horsepower (PS) to Watt (W)', path: './PS-to-W' },
  { name: 'Horsepower (PS) to Milliwatt (mW)', path: './PS-to-mW' },
  { name: 'Horsepower (PS) to Kilowatt (kW)', path: './PS-to-kW' },
  { name: 'Horsepower (PS) to Megawatt (MW)', path: './PS-to-MW' },
  { name: 'Horsepower (PS) to Gigawatt (GW)', path: './PS-to-GW' },
  { name: 'Horsepower (PS) to BTU per Second (Btu/s)', path: './PS-to-Btu_s' },
  { name: 'Horsepower (PS) to Foot-pound per Second (ft-lb/s)', path: './PS-to-ft-lb_s' },
  { name: 'Horsepower (PS) to Horsepower (hp)', path: './PS-to-hp' },
  { name: 'BTU per Second (Btu/s) to Watt (W)', path: './Btu_s-to-W' },
  { name: 'BTU per Second (Btu/s) to Milliwatt (mW)', path: './Btu_s-to-mW' },
  { name: 'BTU per Second (Btu/s) to Kilowatt (kW)', path: './Btu_s-to-kW' },
  { name: 'BTU per Second (Btu/s) to Megawatt (MW)', path: './Btu_s-to-MW' },
  { name: 'BTU per Second (Btu/s) to Gigawatt (GW)', path: './Btu_s-to-GW' },
  { name: 'BTU per Second (Btu/s) to Horsepower (PS)', path: './Btu_s-to-PS' },
  { name: 'BTU per Second (Btu/s) to Foot-pound per Second (ft-lb/s)', path: './Btu_s-to-ft-lb_s' },
  { name: 'BTU per Second (Btu/s) to Horsepower (hp)', path: './Btu_s-to-hp' },
  { name: 'Foot-pound per Second (ft-lb/s) to Watt (W)', path: './ft-lb_s-to-W' },
  { name: 'Foot-pound per Second (ft-lb/s) to Milliwatt (mW)', path: './ft-lb_s-to-mW' },
  { name: 'Foot-pound per Second (ft-lb/s) to Kilowatt (kW)', path: './ft-lb_s-to-kW' },
  { name: 'Foot-pound per Second (ft-lb/s) to Megawatt (MW)', path: './ft-lb_s-to-MW' },
  { name: 'Foot-pound per Second (ft-lb/s) to Gigawatt (GW)', path: './ft-lb_s-to-GW' },
  { name: 'Foot-pound per Second (ft-lb/s) to Horsepower (PS)', path: './ft-lb_s-to-PS' },
  { name: 'Foot-pound per Second (ft-lb/s) to BTU per Second (Btu/s)', path: './ft-lb_s-to-Btu_s' },
  { name: 'Foot-pound per Second (ft-lb/s) to Horsepower (hp)', path: './ft-lb_s-to-hp' },
  { name: 'Horsepower (hp) to Watt (W)', path: './hp-to-W' },
  { name: 'Horsepower (hp) to Milliwatt (mW)', path: './hp-to-mW' },
  { name: 'Horsepower (hp) to Kilowatt (kW)', path: './hp-to-kW' },
  { name: 'Horsepower (hp) to Megawatt (MW)', path: './hp-to-MW' },
  { name: 'Horsepower (hp) to Gigawatt (GW)', path: './hp-to-GW' },
  { name: 'Horsepower (hp) to Horsepower (PS)', path: './hp-to-PS' },
  { name: 'Horsepower (hp) to BTU per Second (Btu/s)', path: './hp-to-Btu_s' },
  { name: 'Horsepower (hp) to Foot-pound per Second (ft-lb/s)', path: './hp-to-ft-lb_s' }
];
export const Energy = [
  { name: 'Watt-second (Ws) to Watt-minute (Wm)', path: './Ws-to-Wm' },
  { name: 'Watt-second (Ws) to Watt-hour (Wh)', path: './Ws-to-Wh' },
  { name: 'Watt-second (Ws) to Milliwatt-hour (mWh)', path: './Ws-to-mWh' },
  { name: 'Watt-second (Ws) to Kilowatt-hour (kWh)', path: './Ws-to-kWh' },
  { name: 'Watt-second (Ws) to Megawatt-hour (MWh)', path: './Ws-to-MWh' },
  { name: 'Watt-second (Ws) to Gigawatt-hour (GWh)', path: './Ws-to-GWh' },
  { name: 'Watt-second (Ws) to Joule (J)', path: './Ws-to-J' },
  { name: 'Watt-second (Ws) to Kilojoule (kJ)', path: './Ws-to-kJ' },
  { name: 'Watt-second (Ws) to Megajoule (MJ)', path: './Ws-to-MJ' },
  { name: 'Watt-second (Ws) to Gigajoule (GJ)', path: './Ws-to-GJ' },
  { name: 'Watt-minute (Wm) to Watt-second (Ws)', path: './Wm-to-Ws' },
  { name: 'Watt-minute (Wm) to Watt-hour (Wh)', path: './Wm-to-Wh' },
  { name: 'Watt-minute (Wm) to Milliwatt-hour (mWh)', path: './Wm-to-mWh' },
  { name: 'Watt-minute (Wm) to Kilowatt-hour (kWh)', path: './Wm-to-kWh' },
  { name: 'Watt-minute (Wm) to Megawatt-hour (MWh)', path: './Wm-to-MWh' },
  { name: 'Watt-minute (Wm) to Gigawatt-hour (GWh)', path: './Wm-to-GWh' },
  { name: 'Watt-minute (Wm) to Joule (J)', path: './Wm-to-J' },
  { name: 'Watt-minute (Wm) to Kilojoule (kJ)', path: './Wm-to-kJ' },
  { name: 'Watt-minute (Wm) to Megajoule (MJ)', path: './Wm-to-MJ' },
  { name: 'Watt-minute (Wm) to Gigajoule (GJ)', path: './Wm-to-GJ' },
  { name: 'Watt-hour (Wh) to Watt-second (Ws)', path: './Wh-to-Ws' },
  { name: 'Watt-hour (Wh) to Watt-minute (Wm)', path: './Wh-to-Wm' },
  { name: 'Watt-hour (Wh) to Milliwatt-hour (mWh)', path: './Wh-to-mWh' },
  { name: 'Watt-hour (Wh) to Kilowatt-hour (kWh)', path: './Wh-to-kWh' },
  { name: 'Watt-hour (Wh) to Megawatt-hour (MWh)', path: './Wh-to-MWh' },
  { name: 'Watt-hour (Wh) to Gigawatt-hour (GWh)', path: './Wh-to-GWh' },
  { name: 'Watt-hour (Wh) to Joule (J)', path: './Wh-to-J' },
  { name: 'Watt-hour (Wh) to Kilojoule (kJ)', path: './Wh-to-kJ' },
  { name: 'Watt-hour (Wh) to Megajoule (MJ)', path: './Wh-to-MJ' },
  { name: 'Watt-hour (Wh) to Gigajoule (GJ)', path: './Wh-to-GJ' },
  { name: 'Milliwatt-hour (mWh) to Watt-second (Ws)', path: './mWh-to-Ws' },
  { name: 'Milliwatt-hour (mWh) to Watt-minute (Wm)', path: './mWh-to-Wm' },
  { name: 'Milliwatt-hour (mWh) to Watt-hour (Wh)', path: './mWh-to-Wh' },
  { name: 'Milliwatt-hour (mWh) to Kilowatt-hour (kWh)', path: './mWh-to-kWh' },
  { name: 'Milliwatt-hour (mWh) to Megawatt-hour (MWh)', path: './mWh-to-MWh' },
  { name: 'Milliwatt-hour (mWh) to Gigawatt-hour (GWh)', path: './mWh-to-GWh' },
  { name: 'Milliwatt-hour (mWh) to Joule (J)', path: './mWh-to-J' },
  { name: 'Milliwatt-hour (mWh) to Kilojoule (kJ)', path: './mWh-to-kJ' },
  { name: 'Milliwatt-hour (mWh) to Megajoule (MJ)', path: './mWh-to-MJ' },
  { name: 'Milliwatt-hour (mWh) to Gigajoule (GJ)', path: './mWh-to-GJ' },
  { name: 'Kilowatt-hour (kWh) to Watt-second (Ws)', path: './kWh-to-Ws' },
  { name: 'Kilowatt-hour (kWh) to Watt-minute (Wm)', path: './kWh-to-Wm' },
  { name: 'Kilowatt-hour (kWh) to Watt-hour (Wh)', path: './kWh-to-Wh' },
  { name: 'Kilowatt-hour (kWh) to Milliwatt-hour (mWh)', path: './kWh-to-mWh' },
  { name: 'Kilowatt-hour (kWh) to Megawatt-hour (MWh)', path: './kWh-to-MWh' },
  { name: 'Kilowatt-hour (kWh) to Gigawatt-hour (GWh)', path: './kWh-to-GWh' },
  { name: 'Kilowatt-hour (kWh) to Joule (J)', path: './kWh-to-J' },
  { name: 'Kilowatt-hour (kWh) to Kilojoule (kJ)', path: './kWh-to-kJ' },
  { name: 'Kilowatt-hour (kWh) to Megajoule (MJ)', path: './kWh-to-MJ' },
  { name: 'Kilowatt-hour (kWh) to Gigajoule (GJ)', path: './kWh-to-GJ' },
  { name: 'Megawatt-hour (MWh) to Watt-second (Ws)', path: './MWh-to-Ws' },
  { name: 'Megawatt-hour (MWh) to Watt-minute (Wm)', path: './MWh-to-Wm' },
  { name: 'Megawatt-hour (MWh) to Watt-hour (Wh)', path: './MWh-to-Wh' },
  { name: 'Megawatt-hour (MWh) to Milliwatt-hour (mWh)', path: './MWh-to-mWh' },
  { name: 'Megawatt-hour (MWh) to Kilowatt-hour (kWh)', path: './MWh-to-kWh' },
  { name: 'Megawatt-hour (MWh) to Gigawatt-hour (GWh)', path: './MWh-to-GWh' },
  { name: 'Megawatt-hour (MWh) to Joule (J)', path: './MWh-to-J' },
  { name: 'Megawatt-hour (MWh) to Kilojoule (kJ)', path: './MWh-to-kJ' },
  { name: 'Megawatt-hour (MWh) to Megajoule (MJ)', path: './MWh-to-MJ' },
  { name: 'Megawatt-hour (MWh) to Gigajoule (GJ)', path: './MWh-to-GJ' },
  { name: 'Gigawatt-hour (GWh) to Watt-second (Ws)', path: './GWh-to-Ws' },
  { name: 'Gigawatt-hour (GWh) to Watt-minute (Wm)', path: './GWh-to-Wm' },
  { name: 'Gigawatt-hour (GWh) to Watt-hour (Wh)', path: './GWh-to-Wh' },
  { name: 'Gigawatt-hour (GWh) to Milliwatt-hour (mWh)', path: './GWh-to-mWh' },
  { name: 'Gigawatt-hour (GWh) to Kilowatt-hour (kWh)', path: './GWh-to-kWh' },
  { name: 'Gigawatt-hour (GWh) to Megawatt-hour (MWh)', path: './GWh-to-MWh' },
  { name: 'Gigawatt-hour (GWh) to Joule (J)', path: './GWh-to-J' },
  { name: 'Gigawatt-hour (GWh) to Kilojoule (kJ)', path: './GWh-to-kJ' },
  { name: 'Gigawatt-hour (GWh) to Megajoule (MJ)', path: './GWh-to-MJ' },
  { name: 'Gigawatt-hour (GWh) to Gigajoule (GJ)', path: './GWh-to-GJ' },
  { name: 'Joule (J) to Watt-second (Ws)', path: './J-to-Ws' },
  { name: 'Joule (J) to Watt-minute (Wm)', path: './J-to-Wm' },
  { name: 'Joule (J) to Watt-hour (Wh)', path: './J-to-Wh' },
  { name: 'Joule (J) to Milliwatt-hour (mWh)', path: './J-to-mWh' },
  { name: 'Joule (J) to Kilowatt-hour (kWh)', path: './J-to-kWh' },
  { name: 'Joule (J) to Megawatt-hour (MWh)', path: './J-to-MWh' },
  { name: 'Joule (J) to Gigawatt-hour (GWh)', path: './J-to-GWh' },
  { name: 'Joule (J) to Kilojoule (kJ)', path: './J-to-kJ' },
  { name: 'Joule (J) to Megajoule (MJ)', path: './J-to-MJ' },
  { name: 'Joule (J) to Gigajoule (GJ)', path: './J-to-GJ' },
  { name: 'Kilojoule (kJ) to Watt-second (Ws)', path: './kJ-to-Ws' },
  { name: 'Kilojoule (kJ) to Watt-minute (Wm)', path: './kJ-to-Wm' },
  { name: 'Kilojoule (kJ) to Watt-hour (Wh)', path: './kJ-to-Wh' },
  { name: 'Kilojoule (kJ) to Milliwatt-hour (mWh)', path: './kJ-to-mWh' },
  { name: 'Kilojoule (kJ) to Kilowatt-hour (kWh)', path: './kJ-to-kWh' },
  { name: 'Kilojoule (kJ) to Megawatt-hour (MWh)', path: './kJ-to-MWh' },
  { name: 'Kilojoule (kJ) to Gigawatt-hour (GWh)', path: './kJ-to-GWh' },
  { name: 'Kilojoule (kJ) to Joule (J)', path: './kJ-to-J' },
  { name: 'Kilojoule (kJ) to Megajoule (MJ)', path: './kJ-to-MJ' },
  { name: 'Kilojoule (kJ) to Gigajoule (GJ)', path: './kJ-to-GJ' },
  { name: 'Megajoule (MJ) to Watt-second (Ws)', path: './MJ-to-Ws' },
  { name: 'Megajoule (MJ) to Watt-minute (Wm)', path: './MJ-to-Wm' },
  { name: 'Megajoule (MJ) to Watt-hour (Wh)', path: './MJ-to-Wh' },
  { name: 'Megajoule (MJ) to Milliwatt-hour (mWh)', path: './MJ-to-mWh' },
  { name: 'Megajoule (MJ) to Kilowatt-hour (kWh)', path: './MJ-to-kWh' },
  { name: 'Megajoule (MJ) to Megawatt-hour (MWh)', path: './MJ-to-MWh' },
  { name: 'Megajoule (MJ) to Gigawatt-hour (GWh)', path: './MJ-to-GWh' },
  { name: 'Megajoule (MJ) to Joule (J)', path: './MJ-to-J' },
  { name: 'Megajoule (MJ) to Kilojoule (kJ)', path: './MJ-to-kJ' },
  { name: 'Megajoule (MJ) to Gigajoule (GJ)', path: './MJ-to-GJ' },
  { name: 'Gigajoule (GJ) to Watt-second (Ws)', path: './GJ-to-Ws' },
  { name: 'Gigajoule (GJ) to Watt-minute (Wm)', path: './GJ-to-Wm' },
  { name: 'Gigajoule (GJ) to Watt-hour (Wh)', path: './GJ-to-Wh' },
  { name: 'Gigajoule (GJ) to Milliwatt-hour (mWh)', path: './GJ-to-mWh' },
  { name: 'Gigajoule (GJ) to Kilowatt-hour (kWh)', path: './GJ-to-kWh' },
  { name: 'Gigajoule (GJ) to Megawatt-hour (MWh)', path: './GJ-to-MWh' },
  { name: 'Gigajoule (GJ) to Gigawatt-hour (GWh)', path: './GJ-to-GWh' },
  { name: 'Gigajoule (GJ) to Joule (J)', path: './GJ-to-J' },
  { name: 'Gigajoule (GJ) to Kilojoule (kJ)', path: './GJ-to-kJ' },
  { name: 'Gigajoule (GJ) to Megajoule (MJ)', path: './GJ-to-MJ' }
];
export const Angle = [
  { name: 'Degree (deg) to Radian (rad)', path: './deg-to-rad' },
  { name: 'Degree (deg) to Gradian (grad)', path: './deg-to-grad' },
  { name: 'Degree (deg) to Arcminute (arcmin)', path: './deg-to-arcmin' },
  { name: 'Degree (deg) to Arcsecond (arcsec)', path: './deg-to-arcsec' },
  { name: 'Radian (rad) to Degree (deg)', path: './rad-to-deg' },
  { name: 'Radian (rad) to Gradian (grad)', path: './rad-to-grad' },
  { name: 'Radian (rad) to Arcminute (arcmin)', path: './rad-to-arcmin' },
  { name: 'Radian (rad) to Arcsecond (arcsec)', path: './rad-to-arcsec' },
  { name: 'Gradian (grad) to Degree (deg)', path: './grad-to-deg' },
  { name: 'Gradian (grad) to Radian (rad)', path: './grad-to-rad' },
  { name: 'Gradian (grad) to Arcminute (arcmin)', path: './grad-to-arcmin' },
  { name: 'Gradian (grad) to Arcsecond (arcsec)', path: './grad-to-arcsec' },
  { name: 'Arcminute (arcmin) to Degree (deg)', path: './arcmin-to-deg' },
  { name: 'Arcminute (arcmin) to Radian (rad)', path: './arcmin-to-rad' },
  { name: 'Arcminute (arcmin) to Gradian (grad)', path: './arcmin-to-grad' },
  { name: 'Arcminute (arcmin) to Arcsecond (arcsec)', path: './arcmin-to-arcsec' },
  { name: 'Arcsecond (arcsec) to Degree (deg)', path: './arcsec-to-deg' },
  { name: 'Arcsecond (arcsec) to Radian (rad)', path: './arcsec-to-rad' },
  { name: 'Arcsecond (arcsec) to Gradian (grad)', path: './arcsec-to-grad' },
  { name: 'Arcsecond (arcsec) to Arcminute (arcmin)', path: './arcsec-to-arcmin' }
];
export const Force = [
  { name: 'Newton (N) to Kilonewton (kN)', path: './N-to-kN' },
  { name: 'Newton (N) to Pound-force (lbf)', path: './N-to-lbf' },
  { name: 'Newton (N) to Kilogram-force (kgf)', path: './N-to-kgf' },
  { name: 'Kilonewton (kN) to Newton (N)', path: './kN-to-N' },
  { name: 'Kilonewton (kN) to Pound-force (lbf)', path: './kN-to-lbf' },
  { name: 'Kilonewton (kN) to Kilogram-force (kgf)', path: './kN-to-kgf' },
  { name: 'Pound-force (lbf) to Newton (N)', path: './lbf-to-N' },
  { name: 'Pound-force (lbf) to Kilonewton (kN)', path: './lbf-to-kN' },
  { name: 'Pound-force (lbf) to Kilogram-force (kgf)', path: './lbf-to-kgf' },
  { name: 'Kilogram-force (kgf) to Newton (N)', path: './kgf-to-N' },
  { name: 'Kilogram-force (kgf) to Kilonewton (kN)', path: './kgf-to-kN' },
  { name: 'Kilogram-force (kgf) to Pound-force (lbf)', path: './kgf-to-lbf' }
];