export const Time = [
  { name: '天转换小时', path: './Day-to-Hour' },
  { name: '天转换微秒', path: './Day-to-Microsecond' },
  { name: '天转换毫秒', path: './Day-to-Millisecond' },
  { name: '天转换分钟', path: './Day-to-Minute' },
  { name: '天转换月', path: './Day-to-Month' },
  { name: '天转换纳秒', path: './Day-to-Nanosecond' },
  { name: '天转换秒', path: './Day-to-Second' },
  { name: '天转换周', path: './Day-to-Week' },
  { name: '天转换年', path: './Day-to-Year' },
  { name: '小时转换天', path: './Hour-to-Day' },
  { name: '小时转换微秒', path: './Hour-to-Microsecond' },
  { name: '小时转换毫秒', path: './Hour-to-Millisecond' },
  { name: '小时转换分钟', path: './Hour-to-Minute' },
  { name: '小时转换月', path: './Hour-to-Month' },
  { name: '小时转换纳秒', path: './Hour-to-Nanosecond' },
  { name: '小时转换秒', path: './Hour-to-Second' },
  { name: '小时转换周', path: './Hour-to-Week' },
  { name: '小时转换年', path: './Hour-to-Year' },
  { name: '微秒转换天', path: './Microsecond-to-Day' },
  { name: '微秒转换小时', path: './Microsecond-to-Hour' },
  { name: '微秒转换毫秒', path: './Microsecond-to-Millisecond' },
  { name: '微秒转换分钟', path: './Microsecond-to-Minute' },
  { name: '微秒转换月', path: './Microsecond-to-Month' },
  { name: '微秒转换纳秒', path: './Microsecond-to-Nanosecond' },
  { name: '微秒转换秒', path: './Microsecond-to-Second' },
  { name: '微秒转换周', path: './Microsecond-to-Week' },
  { name: '微秒转换年', path: './Microsecond-to-Year' },
  { name: '毫秒转换天', path: './Millisecond-to-Day' },
  { name: '毫秒转换小时', path: './Millisecond-to-Hour' },
  { name: '毫秒转换微秒', path: './Millisecond-to-Microsecond' },
  { name: '毫秒转换分钟', path: './Millisecond-to-Minute' },
  { name: '毫秒转换月', path: './Millisecond-to-Month' },
  { name: '毫秒转换纳秒', path: './Millisecond-to-Nanosecond' },
  { name: '毫秒转换秒', path: './Millisecond-to-Second' },
  { name: '毫秒转换周', path: './Millisecond-to-Week' },
  { name: '毫秒转换年', path: './Millisecond-to-Year' },
  { name: '分钟转换天', path: './Minute-to-Day' },
  { name: '分钟转换小时', path: './Minute-to-Hour' },
  { name: '分钟转换微秒', path: './Minute-to-Microsecond' },
  { name: '分钟转换毫秒', path: './Minute-to-Millisecond' },
  { name: '分钟转换月', path: './Minute-to-Month' },
  { name: '分钟转换纳秒', path: './Minute-to-Nanosecond' },
  { name: '分钟转换秒', path: './Minute-to-Second' },
  { name: '分钟转换周', path: './Minute-to-Week' },
  { name: '分钟转换年', path: './Minute-to-Year' },
  { name: '月转换微秒', path: './Month-to-Microsecond' },
  { name: '月转换纳秒', path: './Month-to-Nanosecond' },
  { name: '纳秒转换天', path: './Nanosecond-to-Day' },
  { name: '纳秒转换小时', path: './Nanosecond-to-Hour' },
  { name: '纳秒转换微秒', path: './Nanosecond-to-Microsecond' },
  { name: '纳秒转换毫秒', path: './Nanosecond-to-Millisecond' },
  { name: '纳秒转换分钟', path: './Nanosecond-to-Minute' },
  { name: '纳秒转换月', path: './Nanosecond-to-Month' },
  { name: '纳秒转换秒', path: './Nanosecond-to-Second' },
  { name: '纳秒转换周', path: './Nanosecond-to-Week' },
  { name: '纳秒转换年', path: './Nanosecond-to-Year' },
  { name: '秒转换天', path: './Second-to-Day' },
  { name: '秒转换小时', path: './Second-to-Hour' },
  { name: '秒转换微秒', path: './Second-to-Microsecond' },
  { name: '秒转换毫秒', path: './Second-to-Millisecond' },
  { name: '秒转换分钟', path: './Second-to-Minute' },
  { name: '秒转换月', path: './Second-to-Month' },
  { name: '秒转换纳秒', path: './Second-to-Nanosecond' },
  { name: '秒转换周', path: './Second-to-Week' },
  { name: '秒转换年', path: './Second-to-Year' },
  { name: '周转换天', path: './Week-to-Day' },
  { name: '周转换小时', path: './Week-to-Hour' },
  { name: '周转换微秒', path: './Week-to-Microsecond' },
  { name: '周转换毫秒', path: './Week-to-Millisecond' },
  { name: '周转换分钟', path: './Week-to-Minute' },
  { name: '周转换月', path: './Week-to-Month' },
  { name: '周转换纳秒', path: './Week-to-Nanosecond' },
  { name: '周转换秒', path: './Week-to-Second' },
  { name: '周转换年', path: './Week-to-Year' },
  { name: '年转换天', path: './Year-to-Day' },
  { name: '年转换小时', path: './Year-to-Hour' },
  { name: '年转换微秒', path: './Year-to-Microsecond' },
  { name: '年转换毫秒', path: './Year-to-Millisecond' },
  { name: '年转换分钟', path: './Year-to-Minute' },
  { name: '年转换月', path: './Year-to-Month' },
  { name: '年转换纳秒', path: './Year-to-Nanosecond' },
  { name: '年转换秒', path: './Year-to-Second' },
  { name: '年转换周', path: './Year-to-Week' }
];
export const Mass = [
  { name: '微克 (mcg) 转换 毫克 (mg)', path: './mcg-to-mg' },
  { name: '微克 (mcg) 转换 克 (g)', path: './mcg-to-g' },
  { name: '微克 (mcg) 转换 千克 (kg)', path: './mcg-to-kg' },
  { name: '微克 (mcg) 转换 盎司 (oz)', path: './mcg-to-oz' },
  { name: '微克 (mcg) 转换 磅 (lb)', path: './mcg-to-lb' },
  { name: '微克 (mcg) 转换 公吨 (mt)', path: './mcg-to-mt' },
  { name: '微克 (mcg) 转换 短吨 (st)', path: './mcg-to-st' },
  { name: '微克 (mcg) 转换 长吨 (t)', path: './mcg-to-t' },
  { name: '毫克 (mg) 转换 微克 (mcg)', path: './mg-to-mcg' },
  { name: '毫克 (mg) 转换 克 (g)', path: './mg-to-g' },
  { name: '毫克 (mg) 转换 千克 (kg)', path: './mg-to-kg' },
  { name: '毫克 (mg) 转换 盎司 (oz)', path: './mg-to-oz' },
  { name: '毫克 (mg) 转换 磅 (lb)', path: './mg-to-lb' },
  { name: '毫克 (mg) 转换 公吨 (mt)', path: './mg-to-mt' },
  { name: '毫克 (mg) 转换 短吨 (st)', path: './mg-to-st' },
  { name: '毫克 (mg) 转换 长吨 (t)', path: './mg-to-t' },
  { name: '克 (g) 转换 微克 (mcg)', path: './g-to-mcg' },
  { name: '克 (g) 转换 毫克 (mg)', path: './g-to-mg' },
  { name: '克 (g) 转换 千克 (kg)', path: './g-to-kg' },
  { name: '克 (g) 转换 盎司 (oz)', path: './g-to-oz' },
  { name: '克 (g) 转换 磅 (lb)', path: './g-to-lb' },
  { name: '克 (g) 转换 公吨 (mt)', path: './g-to-mt' },
  { name: '克 (g) 转换 短吨 (st)', path: './g-to-st' },
  { name: '克 (g) 转换 长吨 (t)', path: './g-to-t' },
  { name: '千克 (kg) 转换 微克 (mcg)', path: './kg-to-mcg' },
  { name: '千克 (kg) 转换 毫克 (mg)', path: './kg-to-mg' },
  { name: '千克 (kg) 转换 克 (g)', path: './kg-to-g' },
  { name: '千克 (kg) 转换 盎司 (oz)', path: './kg-to-oz' },
  { name: '千克 (kg) 转换 磅 (lb)', path: './kg-to-lb' },
  { name: '千克 (kg) 转换 公吨 (mt)', path: './kg-to-mt' },
  { name: '千克 (kg) 转换 短吨 (st)', path: './kg-to-st' },
  { name: '千克 (kg) 转换 长吨 (t)', path: './kg-to-t' },
  { name: '盎司 (oz) 转换 微克 (mcg)', path: './oz-to-mcg' },
  { name: '盎司 (oz) 转换 毫克 (mg)', path: './oz-to-mg' },
  { name: '盎司 (oz) 转换 克 (g)', path: './oz-to-g' },
  { name: '盎司 (oz) 转换 千克 (kg)', path: './oz-to-kg' },
  { name: '盎司 (oz) 转换 磅 (lb)', path: './oz-to-lb' },
  { name: '盎司 (oz) 转换 公吨 (mt)', path: './oz-to-mt' },
  { name: '盎司 (oz) 转换 短吨 (st)', path: './oz-to-st' },
  { name: '盎司 (oz) 转换 长吨 (t)', path: './oz-to-t' },
  { name: '磅 (lb) 转换 微克 (mcg)', path: './lb-to-mcg' },
  { name: '磅 (lb) 转换 毫克 (mg)', path: './lb-to-mg' },
  { name: '磅 (lb) 转换 克 (g)', path: './lb-to-g' },
  { name: '磅 (lb) 转换 千克 (kg)', path: './lb-to-kg' },
  { name: '磅 (lb) 转换 盎司 (oz)', path: './lb-to-oz' },
  { name: '磅 (lb) 转换 公吨 (mt)', path: './lb-to-mt' },
  { name: '磅 (lb) 转换 短吨 (st)', path: './lb-to-st' },
  { name: '磅 (lb) 转换 长吨 (t)', path: './lb-to-t' },
  { name: '公吨 (mt) 转换 微克 (mcg)', path: './mt-to-mcg' },
  { name: '公吨 (mt) 转换 毫克 (mg)', path: './mt-to-mg' },
  { name: '公吨 (mt) 转换 克 (g)', path: './mt-to-g' },
  { name: '公吨 (mt) 转换 千克 (kg)', path: './mt-to-kg' },
  { name: '公吨 (mt) 转换 盎司 (oz)', path: './mt-to-oz' },
  { name: '公吨 (mt) 转换 磅 (lb)', path: './mt-to-lb' },
  { name: '公吨 (mt) 转换 短吨 (st)', path: './mt-to-st' },
  { name: '公吨 (mt) 转换 长吨 (t)', path: './mt-to-t' },
  { name: '短吨 (st) 转换 微克 (mcg)', path: './st-to-mcg' },
  { name: '短吨 (st) 转换 毫克 (mg)', path: './st-to-mg' },
  { name: '短吨 (st) 转换 克 (g)', path: './st-to-g' },
  { name: '短吨 (st) 转换 千克 (kg)', path: './st-to-kg' },
  { name: '短吨 (st) 转换 盎司 (oz)', path: './st-to-oz' },
  { name: '短吨 (st) 转换 磅 (lb)', path: './st-to-lb' },
  { name: '短吨 (st) 转换 公吨 (mt)', path: './st-to-mt' },
  { name: '短吨 (st) 转换 长吨 (t)', path: './st-to-t' },
  { name: '长吨 (t) 转换 微克 (mcg)', path: './t-to-mcg' },
  { name: '长吨 (t) 转换 毫克 (mg)', path: './t-to-mg' },
  { name: '长吨 (t) 转换 克 (g)', path: './t-to-g' },
  { name: '长吨 (t) 转换 千克 (kg)', path: './t-to-kg' },
  { name: '长吨 (t) 转换 盎司 (oz)', path: './t-to-oz' },
  { name: '长吨 (t) 转换 磅 (lb)', path: './t-to-lb' },
  { name: '长吨 (t) 转换 公吨 (mt)', path: './t-to-mt' },
  { name: '长吨 (t) 转换 短吨 (st)', path: './t-to-st' }
];
export const Area = [
  { name: '平方毫米 (mm²) 转换 平方厘米 (cm²)', path: './SquareMillimeter-to-SquareCentimeter' },
  { name: '平方毫米 (mm²) 转换 平方米 (m²)', path: './SquareMillimeter-to-SquareMeter' },
  { name: '平方毫米 (mm²) 转换 公顷 (ha)', path: './SquareMillimeter-to-Hectare' },
  { name: '平方毫米 (mm²) 转换 平方千米 (km²)', path: './SquareMillimeter-to-SquareKilometer' },
  { name: '平方毫米 (mm²) 转换 平方英寸 (in²)', path: './SquareMillimeter-to-SquareInch' },
  { name: '平方毫米 (mm²) 转换 平方英尺 (ft²)', path: './SquareMillimeter-to-SquareFoot' },
  { name: '平方毫米 (mm²) 转换 英亩 (ac)', path: './SquareMillimeter-to-Acre' },
  { name: '平方毫米 (mm²) 转换 平方英里 (mi²)', path: './SquareMillimeter-to-SquareMile' },

  { name: '平方厘米 (cm²) 转换 平方毫米 (mm²)', path: './SquareCentimeter-to-SquareMillimeter' },
  { name: '平方厘米 (cm²) 转换 平方米 (m²)', path: './SquareCentimeter-to-SquareMeter' },
  { name: '平方厘米 (cm²) 转换 公顷 (ha)', path: './SquareCentimeter-to-Hectare' },
  { name: '平方厘米 (cm²) 转换 平方千米 (km²)', path: './SquareCentimeter-to-SquareKilometer' },
  { name: '平方厘米 (cm²) 转换 平方英寸 (in²)', path: './SquareCentimeter-to-SquareInch' },
  { name: '平方厘米 (cm²) 转换 平方英尺 (ft²)', path: './SquareCentimeter-to-SquareFoot' },
  { name: '平方厘米 (cm²) 转换 英亩 (ac)', path: './SquareCentimeter-to-Acre' },
  { name: '平方厘米 (cm²) 转换 平方英里 (mi²)', path: './SquareCentimeter-to-SquareMile' },

  { name: '平方米 (m²) 转换 平方毫米 (mm²)', path: './SquareMeter-to-SquareMillimeter' },
  { name: '平方米 (m²) 转换 平方厘米 (cm²)', path: './SquareMeter-to-SquareCentimeter' },
  { name: '平方米 (m²) 转换 公顷 (ha)', path: './SquareMeter-to-Hectare' },
  { name: '平方米 (m²) 转换 平方千米 (km²)', path: './SquareMeter-to-SquareKilometer' },
  { name: '平方米 (m²) 转换 平方英寸 (in²)', path: './SquareMeter-to-SquareInch' },
  { name: '平方米 (m²) 转换 平方英尺 (ft²)', path: './SquareMeter-to-SquareFoot' },
  { name: '平方米 (m²) 转换 英亩 (ac)', path: './SquareMeter-to-Acre' },
  { name: '平方米 (m²) 转换 平方英里 (mi²)', path: './SquareMeter-to-SquareMile' },

  { name: '公顷 (ha) 转换 平方毫米 (mm²)', path: './Hectare-to-SquareMillimeter' },
  { name: '公顷 (ha) 转换 平方厘米 (cm²)', path: './Hectare-to-SquareCentimeter' },
  { name: '公顷 (ha) 转换 平方米 (m²)', path: './Hectare-to-SquareMeter' },
  { name: '公顷 (ha) 转换 平方千米 (km²)', path: './Hectare-to-SquareKilometer' },
  { name: '公顷 (ha) 转换 平方英寸 (in²)', path: './Hectare-to-SquareInch' },
  { name: '公顷 (ha) 转换 平方英尺 (ft²)', path: './Hectare-to-SquareFoot' },
  { name: '公顷 (ha) 转换 英亩 (ac)', path: './Hectare-to-Acre' },
  { name: '公顷 (ha) 转换 平方英里 (mi²)', path: './Hectare-to-SquareMile' },

  { name: '平方千米 (km²) 转换 平方毫米 (mm²)', path: './SquareKilometer-to-SquareMillimeter' },
  { name: '平方千米 (km²) 转换 平方厘米 (cm²)', path: './SquareKilometer-to-SquareCentimeter' },
  { name: '平方千米 (km²) 转换 平方米 (m²)', path: './SquareKilometer-to-SquareMeter' },
  { name: '平方千米 (km²) 转换 公顷 (ha)', path: './SquareKilometer-to-Hectare' },
  { name: '平方千米 (km²) 转换 平方英寸 (in²)', path: './SquareKilometer-to-SquareInch' },
  { name: '平方千米 (km²) 转换 平方英尺 (ft²)', path: './SquareKilometer-to-SquareFoot' },
  { name: '平方千米 (km²) 转换 英亩 (ac)', path: './SquareKilometer-to-Acre' },
  { name: '平方千米 (km²) 转换 平方英里 (mi²)', path: './SquareKilometer-to-SquareMile' },

  { name: '平方英寸 (in²) 转换 平方毫米 (mm²)', path: './SquareInch-to-SquareMillimeter' },
  { name: '平方英寸 (in²) 转换 平方厘米 (cm²)', path: './SquareInch-to-SquareCentimeter' },
  { name: '平方英寸 (in²) 转换 平方米 (m²)', path: './SquareInch-to-SquareMeter' },
  { name: '平方英寸 (in²) 转换 公顷 (ha)', path: './SquareInch-to-Hectare' },
  { name: '平方英寸 (in²) 转换 平方千米 (km²)', path: './SquareInch-to-SquareKilometer' },
  { name: '平方英寸 (in²) 转换 平方英尺 (ft²)', path: './SquareInch-to-SquareFoot' },
  { name: '平方英寸 (in²) 转换 英亩 (ac)', path: './SquareInch-to-Acre' },
  { name: '平方英寸 (in²) 转换 平方英里 (mi²)', path: './SquareInch-to-SquareMile' },

  { name: '平方英尺 (ft²) 转换 平方毫米 (mm²)', path: './SquareFoot-to-SquareMillimeter' },
  { name: '平方英尺 (ft²) 转换 平方厘米 (cm²)', path: './SquareFoot-to-SquareCentimeter' },
  { name: '平方英尺 (ft²) 转换 平方米 (m²)', path: './SquareFoot-to-SquareMeter' },
  { name: '平方英尺 (ft²) 转换 公顷 (ha)', path: './SquareFoot-to-Hectare' },
  { name: '平方英尺 (ft²) 转换 平方千米 (km²)', path: './SquareFoot-to-SquareKilometer' },
  { name: '平方英尺 (ft²) 转换 平方英寸 (in²)', path: './SquareFoot-to-SquareInch' },
  { name: '平方英尺 (ft²) 转换 英亩 (ac)', path: './SquareFoot-to-Acre' },
  { name: '平方英尺 (ft²) 转换 平方英里 (mi²)', path: './SquareFoot-to-SquareMile' },

  { name: '英亩 (ac) 转换 平方毫米 (mm²)', path: './Acre-to-SquareMillimeter' },
  { name: '英亩 (ac) 转换 平方厘米 (cm²)', path: './Acre-to-SquareCentimeter' },
  { name: '英亩 (ac) 转换 平方米 (m²)', path: './Acre-to-SquareMeter' },
  { name: '英亩 (ac) 转换 公顷 (ha)', path: './Acre-to-Hectare' },
  { name: '英亩 (ac) 转换 平方千米 (km²)', path: './Acre-to-SquareKilometer' },
  { name: '英亩 (ac) 转换 平方英寸 (in²)', path: './Acre-to-SquareInch' },
  { name: '英亩 (ac) 转换 平方英尺 (ft²)', path: './Acre-to-SquareFoot' },
  { name: '英亩 (ac) 转换 平方英里 (mi²)', path: './Acre-to-SquareMile' },

  { name: '平方英里 (mi²) 转换 平方毫米 (mm²)', path: './SquareMile-to-SquareMillimeter' },
  { name: '平方英里 (mi²) 转换 平方厘米 (cm²)', path: './SquareMile-to-SquareCentimeter' },
  { name: '平方英里 (mi²) 转换 平方米 (m²)', path: './SquareMile-to-SquareMeter' },
  { name: '平方英里 (mi²) 转换 公顷 (ha)', path: './SquareMile-to-Hectare' },
  { name: '平方英里 (mi²) 转换 平方千米 (km²)', path: './SquareMile-to-SquareKilometer' },
  { name: '平方英里 (mi²) 转换 平方英寸 (in²)', path: './SquareMile-to-SquareInch' },
  { name: '平方英里 (mi²) 转换 平方英尺 (ft²)', path: './SquareMile-to-SquareFoot' },
  { name: '平方英里 (mi²) 转换 英亩 (ac)', path: './SquareMile-to-Acre' }
];
export const Temperature = [
  { name: '摄氏度 (°C) 转换 开尔文 (K)', path: './Celsius-to-Kelvin' },
  { name: '摄氏度 (°C) 转换 华氏度 (°F)', path: './Celsius-to-Fahrenheit' },
  { name: '摄氏度 (°C) 转换 兰金度 (R)', path: './Celsius-to-Rankine' },
  { name: '开尔文 (K) 转换 摄氏度 (°C)', path: './Kelvin-to-Celsius' },
  { name: '开尔文 (K) 转换 华氏度 (°F)', path: './Kelvin-to-Fahrenheit' },
  { name: '开尔文 (K) 转换 兰金度 (R)', path: './Kelvin-to-Rankine' },
  { name: '华氏度 (°F) 转换 摄氏度 (°C)', path: './Fahrenheit-to-Celsius' },
  { name: '华氏度 (°F) 转换 开尔文 (K)', path: './Fahrenheit-to-Kelvin' },
  { name: '华氏度 (°F) 转换 兰金度 (R)', path: './Fahrenheit-to-Rankine' },
  { name: '兰金度 (R) 转换 摄氏度 (°C)', path: './Rankine-to-Celsius' },
  { name: '兰金度 (R) 转换 开尔文 (K)', path: './Rankine-to-Kelvin' },
  { name: '兰金度 (R) 转换 华氏度 (°F)', path: './Rankine-to-Fahrenheit' }
];
export const Volume = [
  { name: '立方毫米 (mm³) 转换 立方厘米 (cm³)', path: './mm3-to-cm3' },
  { name: '立方毫米 (mm³) 转换 毫升 (ml)', path: './mm3-to-ml' },
  { name: '立方毫米 (mm³) 转换 升 (l)', path: './mm3-to-l' },
  { name: '立方毫米 (mm³) 转换 千升 (kl)', path: './mm3-to-kl' },
  { name: '立方毫米 (mm³) 转换 兆升 (Ml)', path: './mm3-to-Ml' },
  { name: '立方毫米 (mm³) 转换 吉升 (Gl)', path: './mm3-to-Gl' },
  { name: '立方毫米 (mm³) 转换 立方米 (m³)', path: './mm3-to-m3' },
  { name: '立方毫米 (mm³) 转换 立方公里 (km³)', path: './mm3-to-km3' },
  { name: '立方厘米 (cm³) 转换 立方毫米 (mm³)', path: './cm3-to-mm3' },
  { name: '立方厘米 (cm³) 转换 毫升 (ml)', path: './cm3-to-ml' },
  { name: '立方厘米 (cm³) 转换 升 (l)', path: './cm3-to-l' },
  { name: '立方厘米 (cm³) 转换 千升 (kl)', path: './cm3-to-kl' },
  { name: '立方厘米 (cm³) 转换 兆升 (Ml)', path: './cm3-to-Ml' },
  { name: '立方厘米 (cm³) 转换 吉升 (Gl)', path: './cm3-to-Gl' },
  { name: '立方厘米 (cm³) 转换 立方米 (m³)', path: './cm3-to-m3' },
  { name: '立方厘米 (cm³) 转换 立方公里 (km³)', path: './cm3-to-km3' },
  { name: '毫升 (ml) 转换 立方毫米 (mm³)', path: './ml-to-mm3' },
  { name: '毫升 (ml) 转换 立方厘米 (cm³)', path: './ml-to-cm3' },
  { name: '毫升 (ml) 转换 升 (l)', path: './ml-to-l' },
  { name: '毫升 (ml) 转换 千升 (kl)', path: './ml-to-kl' },
  { name: '毫升 (ml) 转换 兆升 (Ml)', path: './ml-to-Ml' },
  { name: '毫升 (ml) 转换 吉升 (Gl)', path: './ml-to-Gl' },
  { name: '毫升 (ml) 转换 立方米 (m³)', path: './ml-to-m3' },
  { name: '毫升 (ml) 转换 立方公里 (km³)', path: './ml-to-km3' },
  { name: '升 (l) 转换 立方毫米 (mm³)', path: './l-to-mm3' },
  { name: '升 (l) 转换 立方厘米 (cm³)', path: './l-to-cm3' },
  { name: '升 (l) 转换 毫升 (ml)', path: './l-to-ml' },
  { name: '升 (l) 转换 千升 (kl)', path: './l-to-kl' },
  { name: '升 (l) 转换 兆升 (Ml)', path: './l-to-Ml' },
  { name: '升 (l) 转换 吉升 (Gl)', path: './l-to-Gl' },
  { name: '升 (l) 转换 立方米 (m³)', path: './l-to-m3' },
  { name: '升 (l) 转换 立方公里 (km³)', path: './l-to-km3' },
  { name: '千升 (kl) 转换 立方毫米 (mm³)', path: './kl-to-mm3' },
  { name: '千升 (kl) 转换 立方厘米 (cm³)', path: './kl-to-cm3' },
  { name: '千升 (kl) 转换 毫升 (ml)', path: './kl-to-ml' },
  { name: '千升 (kl) 转换 升 (l)', path: './kl-to-l' },
  { name: '千升 (kl) 转换 兆升 (Ml)', path: './kl-to-Ml' },
  { name: '千升 (kl) 转换 吉升 (Gl)', path: './kl-to-Gl' },
  { name: '千升 (kl) 转换 立方米 (m³)', path: './kl-to-m3' },
  { name: '千升 (kl) 转换 立方公里 (km³)', path: './kl-to-km3' },
  { name: '兆升 (Ml) 转换 立方毫米 (mm³)', path: './Ml-to-mm3' },
  { name: '兆升 (Ml) 转换 立方厘米 (cm³)', path: './Ml-to-cm3' },
  { name: '兆升 (Ml) 转换 毫升 (ml)', path: './Ml-to-ml' },
  { name: '兆升 (Ml) 转换 升 (l)', path: './Ml-to-l' },
  { name: '兆升 (Ml) 转换 千升 (kl)', path: './Ml-to-kl' },
  { name: '兆升 (Ml) 转换 吉升 (Gl)', path: './Ml-to-Gl' },
  { name: '兆升 (Ml) 转换 立方米 (m³)', path: './Ml-to-m3' },
  { name: '兆升 (Ml) 转换 立方公里 (km³)', path: './Ml-to-km3' },
  { name: '吉升 (Gl) 转换 立方毫米 (mm³)', path: './Gl-to-mm3' },
  { name: '吉升 (Gl) 转换 立方厘米 (cm³)', path: './Gl-to-cm3' },
  { name: '吉升 (Gl) 转换 毫升 (ml)', path: './Gl-to-ml' },
  { name: '吉升 (Gl) 转换 升 (l)', path: './Gl-to-l' },
  { name: '吉升 (Gl) 转换 千升 (kl)', path: './Gl-to-kl' },
  { name: '吉升 (Gl) 转换 兆升 (Ml)', path: './Gl-to-Ml' },
  { name: '吉升 (Gl) 转换 立方米 (m³)', path: './Gl-to-m3' },
  { name: '吉升 (Gl) 转换 立方公里 (km³)', path: './Gl-to-km3' },
  { name: '立方米 (m³) 转换 立方毫米 (mm³)', path: './m3-to-mm3' },
  { name: '立方米 (m³) 转换 立方厘米 (cm³)', path: './m3-to-cm3' },
  { name: '立方米 (m³) 转换 毫升 (ml)', path: './m3-to-ml' },
  { name: '立方米 (m³) 转换 升 (l)', path: './m3-to-l' },
  { name: '立方米 (m³) 转换 千升 (kl)', path: './m3-to-kl' },
  { name: '立方米 (m³) 转换 兆升 (Ml)', path: './m3-to-Ml' },
  { name: '立方米 (m³) 转换 吉升 (Gl)', path: './m3-to-Gl' },
  { name: '立方米 (m³) 转换 立方公里 (km³)', path: './m3-to-km3' },
  { name: '立方公里 (km³) 转换 立方毫米 (mm³)', path: './km3-to-mm3' },
  { name: '立方公里 (km³) 转换 立方厘米 (cm³)', path: './km3-to-cm3' },
  { name: '立方公里 (km³) 转换 毫升 (ml)', path: './km3-to-ml' },
  { name: '立方公里 (km³) 转换 升 (l)', path: './km3-to-l' },
  { name: '立方公里 (km³) 转换 千升 (kl)', path: './km3-to-kl' },
  { name: '立方公里 (km³) 转换 兆升 (Ml)', path: './km3-to-Ml' },
  { name: '立方公里 (km³) 转换 吉升 (Gl)', path: './km3-to-Gl' },
  { name: '立方公里 (km³) 转换 立方米 (m³)', path: './km3-to-m3' },
  { name: '茶匙 (tsp) 转换 立方毫米 (mm³)', path: './tsp-to-mm3' },
  { name: '茶匙 (tsp) 转换 立方厘米 (cm³)', path: './tsp-to-cm3' },
  { name: '茶匙 (tsp) 转换 毫升 (ml)', path: './tsp-to-ml' },
  { name: '茶匙 (tsp) 转换 升 (l)', path: './tsp-to-l' },
  { name: '茶匙 (tsp) 转换 千升 (kl)', path: './tsp-to-kl' },
  { name: '茶匙 (tsp) 转换 兆升 (Ml)', path: './tsp-to-Ml' },
  { name: '茶匙 (tsp) 转换 吉升 (Gl)', path: './tsp-to-Gl' },
  { name: '茶匙 (tsp) 转换 立方米 (m³)', path: './tsp-to-m3' },
  { name: '茶匙 (tsp) 转换 立方公里 (km³)', path: './tsp-to-km3' },
  { name: '汤匙 (Tbs) 转换 立方毫米 (mm³)', path: './Tbs-to-mm3' },
  { name: '汤匙 (Tbs) 转换 立方厘米 (cm³)', path: './Tbs-to-cm3' },
  { name: '汤匙 (Tbs) 转换 毫升 (ml)', path: './Tbs-to-ml' },
  { name: '汤匙 (Tbs) 转换 升 (l)', path: './Tbs-to-l' },
  { name: '汤匙 (Tbs) 转换 千升 (kl)', path: './Tbs-to-kl' },
  { name: '汤匙 (Tbs) 转换 兆升 (Ml)', path: './Tbs-to-Ml' },
  { name: '汤匙 (Tbs) 转换 吉升 (Gl)', path: './Tbs-to-Gl' },
  { name: '汤匙 (Tbs) 转换 立方米 (m³)', path: './Tbs-to-m3' },
  { name: '汤匙 (Tbs) 转换 立方公里 (km³)', path: './Tbs-to-km3' },
  { name: '立方英寸 (in3) 转换 立方毫米 (mm³)', path: './in3-to-mm3' },
  { name: '立方英寸 (in3) 转换 立方厘米 (cm³)', path: './in3-to-cm3' },
  { name: '立方英寸 (in3) 转换 毫升 (ml)', path: './in3-to-ml' },
  { name: '立方英寸 (in3) 转换 升 (l)', path: './in3-to-l' },
  { name: '立方英寸 (in3) 转换 千升 (kl)', path: './in3-to-kl' },
  { name: '立方英寸 (in3) 转换 兆升 (Ml)', path: './in3-to-Ml' },
  { name: '立方英寸 (in3) 转换 吉升 (Gl)', path: './in3-to-Gl' },
  { name: '立方英寸 (in3) 转换 立方米 (m³)', path: './in3-to-m3' },
  { name: '立方英寸 (in3) 转换 立方公里 (km³)', path: './in3-to-km3' },
  { name: '液体盎司 (fl-oz) 转换 立方毫米 (mm³)', path: './fl-oz-to-mm3' },
  { name: '液体盎司 (fl-oz) 转换 立方厘米 (cm³)', path: './fl-oz-to-cm3' },
  { name: '液体盎司 (fl-oz) 转换 毫升 (ml)', path: './fl-oz-to-ml' },
  { name: '液体盎司 (fl-oz) 转换 升 (l)', path: './fl-oz-to-l' },
  { name: '液体盎司 (fl-oz) 转换 千升 (kl)', path: './fl-oz-to-kl' },
  { name: '液体盎司 (fl-oz) 转换 兆升 (Ml)', path: './fl-oz-to-Ml' },
  { name: '液体盎司 (fl-oz) 转换 吉升 (Gl)', path: './fl-oz-to-Gl' },
  { name: '液体盎司 (fl-oz) 转换 立方米 (m³)', path: './fl-oz-to-m3' },
  { name: '液体盎司 (fl-oz) 转换 立方公里 (km³)', path: './fl-oz-to-km3' },
  { name: '杯 (cup) 转换 立方毫米 (mm³)', path: './cup-to-mm3' },
  { name: '杯 (cup) 转换 立方厘米 (cm³)', path: './cup-to-cm3' },
  { name: '杯 (cup) 转换 毫升 (ml)', path: './cup-to-ml' },
  { name: '杯 (cup) 转换 升 (l)', path: './cup-to-l' },
  { name: '杯 (cup) 转换 千升 (kl)', path: './cup-to-kl' },
  { name: '杯 (cup) 转换 兆升 (Ml)', path: './cup-to-Ml' },
  { name: '杯 (cup) 转换 吉升 (Gl)', path: './cup-to-Gl' },
  { name: '杯 (cup) 转换 立方米 (m³)', path: './cup-to-m3' },
  { name: '杯 (cup) 转换 立方公里 (km³)', path: './cup-to-km3' },
  { name: '品脱 (pnt) 转换 立方毫米 (mm³)', path: './pnt-to-mm3' },
  { name: '品脱 (pnt) 转换 立方厘米 (cm³)', path: './pnt-to-cm3' },
  { name: '品脱 (pnt) 转换 毫升 (ml)', path: './pnt-to-ml' },
  { name: '品脱 (pnt) 转换 升 (l)', path: './pnt-to-l' },
  { name: '品脱 (pnt) 转换 千升 (kl)', path: './pnt-to-kl' },
  { name: '品脱 (pnt) 转换 兆升 (Ml)', path: './pnt-to-Ml' },
  { name: '品脱 (pnt) 转换 吉升 (Gl)', path: './pnt-to-Gl' },
  { name: '品脱 (pnt) 转换 立方米 (m³)', path: './pnt-to-m3' },
  { name: '品脱 (pnt) 转换 立方公里 (km³)', path: './pnt-to-km3' },
  { name: '夸脱 (qt) 转换 立方毫米 (mm³)', path: './qt-to-mm3' },
  { name: '夸脱 (qt) 转换 立方厘米 (cm³)', path: './qt-to-cm3' },
  { name: '夸脱 (qt) 转换 毫升 (ml)', path: './qt-to-ml' },
  { name: '夸脱 (qt) 转换 升 (l)', path: './qt-to-l' },
  { name: '夸脱 (qt) 转换 千升 (kl)', path: './qt-to-kl' },
  { name: '夸脱 (qt) 转换 兆升 (Ml)', path: './qt-to-Ml' },
  { name: '夸脱 (qt) 转换 吉升 (Gl)', path: './qt-to-Gl' },
  { name: '夸脱 (qt) 转换 立方米 (m³)', path: './qt-to-m3' },
  { name: '夸脱 (qt) 转换 立方公里 (km³)', path: './qt-to-km3' },
  { name: '加仑 (gal) 转换 立方毫米 (mm³)', path: './gal-to-mm3' },
  { name: '加仑 (gal) 转换 立方厘米 (cm³)', path: './gal-to-cm3' },
  { name: '加仑 (gal) 转换 毫升 (ml)', path: './gal-to-ml' },
  { name: '加仑 (gal) 转换 升 (l)', path: './gal-to-l' },
  { name: '加仑 (gal) 转换 千升 (kl)', path: './gal-to-kl' },
  { name: '加仑 (gal) 转换 兆升 (Ml)', path: './gal-to-Ml' },
  { name: '加仑 (gal) 转换 吉升 (Gl)', path: './gal-to-Gl' },
  { name: '加仑 (gal) 转换 立方米 (m³)', path: './gal-to-m3' },
  { name: '加仑 (gal) 转换 立方公里 (km³)', path: './gal-to-km3' },
  { name: '立方英尺 (ft3) 转换 立方毫米 (mm³)', path: './ft3-to-mm3' },
  { name: '立方英尺 (ft3) 转换 立方厘米 (cm³)', path: './ft3-to-cm3' },
  { name: '立方英尺 (ft3) 转换 毫升 (ml)', path: './ft3-to-ml' },
  { name: '立方英尺 (ft3) 转换 升 (l)', path: './ft3-to-l' },
  { name: '立方英尺 (ft3) 转换 千升 (kl)', path: './ft3-to-kl' },
  { name: '立方英尺 (ft3) 转换 兆升 (Ml)', path: './ft3-to-Ml' },
  { name: '立方英尺 (ft3) 转换 吉升 (Gl)', path: './ft3-to-Gl' },
  { name: '立方英尺 (ft3) 转换 立方米 (m³)', path: './ft3-to-m3' },
  { name: '立方英尺 (ft3) 转换 立方公里 (km³)', path: './ft3-to-km3' },
  { name: '立方码 (yd3) 转换 立方毫米 (mm³)', path: './yd3-to-mm3' },
  { name: '立方码 (yd3) 转换 立方厘米 (cm³)', path: './yd3-to-cm3' },
  { name: '立方码 (yd3) 转换 毫升 (ml)', path: './yd3-to-ml' },
  { name: '立方码 (yd3) 转换 升 (l)', path: './yd3-to-l' },
  { name: '立方码 (yd3) 转换 千升 (kl)', path: './yd3-to-kl' },
  { name: '立方码 (yd3) 转换 兆升 (Ml)', path: './yd3-to-Ml' },
  { name: '立方码 (yd3) 转换 吉升 (Gl)', path: './yd3-to-Gl' },
  { name: '立方码 (yd3) 转换 立方米 (m³)', path: './yd3-to-m3' },
  { name: '立方码 (yd3) 转换 立方公里 (km³)', path: './yd3-to-km3' }
];
export const Length = [
  { "name": "纳米 (nm) 转换 微米 (μm)", "path": "./Nanometer-to-Micrometer" },
  { "name": "纳米 (nm) 转换 毫米 (mm)", "path": "./Nanometer-to-Millimeter" },
  { "name": "纳米 (nm) 转换 厘米 (cm)", "path": "./Nanometer-to-Centimeter" },
  { "name": "纳米 (nm) 转换 米 (m)", "path": "./Nanometer-to-Meter" },
  { "name": "纳米 (nm) 转换 公里 (km)", "path": "./Nanometer-to-Kilometer" },
  { "name": "微米 (μm) 转换 毫米 (mm)", "path": "./Micrometer-to-Millimeter" },
  { "name": "微米 (μm) 转换 厘米 (cm)", "path": "./Micrometer-to-Centimeter" },
  { "name": "微米 (μm) 转换 米 (m)", "path": "./Micrometer-to-Meter" },
  { "name": "微米 (μm) 转换 公里 (km)", "path": "./Micrometer-to-Kilometer" },
  { "name": "毫米 (mm) 转换 厘米 (cm)", "path": "./Millimeter-to-Centimeter" },
  { "name": "毫米 (mm) 转换 米 (m)", "path": "./Millimeter-to-Meter" },
  { "name": "毫米 (mm) 转换 公里 (km)", "path": "./Millimeter-to-Kilometer" },
  { "name": "厘米 (cm) 转换 米 (m)", "path": "./Centimeter-to-Meter" },
  { "name": "厘米 (cm) 转换 公里 (km)", "path": "./Centimeter-to-Kilometer" },
  { "name": "米 (m) 转换 公里 (km)", "path": "./Meter-to-Kilometer" },
  { "name": "纳米 (nm) 转换 英寸 (in)", "path": "./Nanometer-to-Inch" },
  { "name": "纳米 (nm) 转换 码 (yd)", "path": "./Nanometer-to-Yard" },
  { "name": "纳米 (nm) 转换 英尺（美） (ft)", "path": "./Nanometer-to-Foot-us" },
  { "name": "纳米 (nm) 转换 英尺 (ft)", "path": "./Nanometer-to-Foot" },
  { "name": "纳米 (nm) 转换 寻 (fm)", "path": "./Nanometer-to-Fathom" },
  { "name": "纳米 (nm) 转换 英里 (mi)", "path": "./Nanometer-to-Mile" },
  { "name": "纳米 (nm) 转换 海里 (nmi)", "path": "./Nanometer-to-Nautical-mile" },
  { "name": "微米 (μm) 转换 英寸 (in)", "path": "./Micrometer-to-Inch" },
  { "name": "微米 (μm) 转换 码 (yd)", "path": "./Micrometer-to-Yard" },
  { "name": "微米 (μm) 转换 英尺（美） (ft)", "path": "./Micrometer-to-Foot-us" },
  { "name": "微米 (μm) 转换 英尺 (ft)", "path": "./Micrometer-to-Foot" },
  { "name": "微米 (μm) 转换 寻 (fm)", "path": "./Micrometer-to-Fathom" },
  { "name": "微米 (μm) 转换 英里 (mi)", "path": "./Micrometer-to-Mile" },
  { "name": "微米 (μm) 转换 海里 (nmi)", "path": "./Micrometer-to-Nautical-mile" },
  { "name": "毫米 (mm) 转换 英寸 (in)", "path": "./Millimeter-to-Inch" },
  { "name": "毫米 (mm) 转换 码 (yd)", "path": "./Millimeter-to-Yard" },
  { "name": "毫米 (mm) 转换 英尺（美） (ft)", "path": "./Millimeter-to-Foot-us" },
  { "name": "毫米 (mm) 转换 英尺 (ft)", "path": "./Millimeter-to-Foot" },
  { "name": "毫米 (mm) 转换 寻 (fm)", "path": "./Millimeter-to-Fathom" },
  { "name": "毫米 (mm) 转换 英里 (mi)", "path": "./Millimeter-to-Mile" },
  { "name": "毫米 (mm) 转换 海里 (nmi)", "path": "./Millimeter-to-Nautical-mile" },
  { "name": "厘米 (cm) 转换 英寸 (in)", "path": "./Centimeter-to-Inch" },
  { "name": "厘米 (cm) 转换 码 (yd)", "path": "./Centimeter-to-Yard" },
  { "name": "厘米 (cm) 转换 英尺（美） (ft)", "path": "./Centimeter-to-Foot-us" },
  { "name": "厘米 (cm) 转换 英尺 (ft)", "path": "./Centimeter-to-Foot" },
  { "name": "厘米 (cm) 转换 寻 (fm)", "path": "./Centimeter-to-Fathom" },
  { "name": "厘米 (cm) 转换 英里 (mi)", "path": "./Centimeter-to-Mile" },
  { "name": "厘米 (cm) 转换 海里 (nmi)", "path": "./Centimeter-to-Nautical-mile" },
  { "name": "米 (m) 转换 英寸 (in)", "path": "./Meter-to-Inch" },
  { "name": "米 (m) 转换 码 (yd)", "path": "./Meter-to-Yard" },
  { "name": "米 (m) 转换 英尺（美） (ft)", "path": "./Meter-to-Foot-us" },
  { "name": "米 (m) 转换 英尺 (ft)", "path": "./Meter-to-Foot" },
  { "name": "米 (m) 转换 寻 (fm)", "path": "./Meter-to-Fathom" },
  { "name": "米 (m) 转换 英里 (mi)", "path": "./Meter-to-Mile" },
  { "name": "米 (m) 转换 海里 (nmi)", "path": "./Meter-to-Nautical-mile" },
  { "name": "公里 (km) 转换 英寸 (in)", "path": "./Kilometer-to-Inch" },
  { "name": "公里 (km) 转换 码 (yd)", "path": "./Kilometer-to-Yard" },
  { "name": "公里 (km) 转换 英尺（美） (ft)", "path": "./Kilometer-to-Foot-us" },
  { "name": "公里 (km) 转换 英尺 (ft)", "path": "./Kilometer-to-Foot" },
  { "name": "公里 (km) 转换 寻 (fm)", "path": "./Kilometer-to-Fathom" },
  { "name": "公里 (km) 转换 英里 (mi)", "path": "./Kilometer-to-Mile" },
  { "name": "公里 (km) 转换 海里 (nmi)", "path": "./Kilometer-to-Nautical-mile" },
  { "name": "英寸 (in) 转换 码 (yd)", "path": "./Inch-to-Yard" },
  { "name": "英寸 (in) 转换 英尺（美） (ft)", "path": "./Inch-to-Foot-us" },
  { "name": "英寸 (in) 转换 英尺 (ft)", "path": "./Inch-to-Foot" },
  { "name": "英寸 (in) 转换 寻 (fm)", "path": "./Inch-to-Fathom" },
  { "name": "英寸 (in) 转换 英里 (mi)", "path": "./Inch-to-Mile" },
  { "name": "英寸 (in) 转换 海里 (nmi)", "path": "./Inch-to-Nautical-mile" },
  { "name": "码 (yd) 转换 英尺（美） (ft)", "path": "./Yard-to-Foot-us" },
  { "name": "码 (yd) 转换 英尺 (ft)", "path": "./Yard-to-Foot" },
  { "name": "码 (yd) 转换 寻 (fm)", "path": "./Yard-to-Fathom" },
  { "name": "码 (yd) 转换 英里 (mi)", "path": "./Yard-to-Mile" },
  { "name": "码 (yd) 转换 海里 (nmi)", "path": "./Yard-to-Nautical-mile" },
  { "name": "英尺（美） (ft) 转换 英尺 (ft)", "path": "./Foot-us-to-Foot" },
  { "name": "英尺（美） (ft) 转换 寻 (fm)", "path": "./Foot-us-to-Fathom" },
  { "name": "英尺（美） (ft) 转换 英里 (mi)", "path": "./Foot-us-to-Mile" },
  { "name": "英尺（美） (ft) 转换 海里 (nmi)", "path": "./Foot-us-to-Nautical-mile" },
  { "name": "英尺 (ft) 转换 寻 (fm)", "path": "./Foot-to-Fathom" },
  { "name": "英尺 (ft) 转换 英里 (mi)", "path": "./Foot-to-Mile" },
  { "name": "英尺 (ft) 转换 海里 (nmi)", "path": "./Foot-to-Nautical-mile" },
  { "name": "寻 (fm) 转换 英里 (mi)", "path": "./Fathom-to-Mile" },
  { "name": "寻 (fm) 转换 海里 (nmi)", "path": "./Fathom-to-Nautical-mile" },
  { "name": "英里 (mi) 转换 海里 (nmi)", "path": "./Mile-to-Nautical-mile" }
]
export const Speed = [
  { name: '米/秒 (m/s) 转换 千米/小时 (km/h)', path: './m_s-to-km_h' },
  { name: '米/秒 (m/s) 转换 英里/小时 (mph)', path: './m_s-to-mph' },
  { name: '米/秒 (m/s) 转换 节 (knot)', path: './m_s-to-knot' },
  { name: '米/秒 (m/s) 转换 英尺/秒 (ft/s)', path: './m_s-to-ft_s' },
  { name: '米/秒 (m/s) 转换 英寸/小时 (in/h)', path: './m_s-to-in_h' },
  { name: '米/秒 (m/s) 转换 毫米/小时 (mm/h)', path: './m_s-to-mm_h' },
  { name: '千米/小时 (km/h) 转换 米/秒 (m/s)', path: './km_h-to-m_s' },
  { name: '千米/小时 (km/h) 转换 英里/小时 (mph)', path: './km_h-to-mph' },
  { name: '千米/小时 (km/h) 转换 节 (knot)', path: './km_h-to-knot' },
  { name: '千米/小时 (km/h) 转换 英尺/秒 (ft/s)', path: './km_h-to-ft_s' },
  { name: '千米/小时 (km/h) 转换 英寸/小时 (in/h)', path: './km_h-to-in_h' },
  { name: '千米/小时 (km/h) 转换 毫米/小时 (mm/h)', path: './km_h-to-mm_h' },
  { name: '英里/小时 (mph) 转换 米/秒 (m/s)', path: './mph-to-m_s' },
  { name: '英里/小时 (mph) 转换 千米/小时 (km/h)', path: './mph-to-km_h' },
  { name: '英里/小时 (mph) 转换 节 (knot)', path: './mph-to-knot' },
  { name: '英里/小时 (mph) 转换 英尺/秒 (ft/s)', path: './mph-to-ft_s' },
  { name: '英里/小时 (mph) 转换 英寸/小时 (in/h)', path: './mph-to-in_h' },
  { name: '英里/小时 (mph) 转换 毫米/小时 (mm/h)', path: './mph-to-mm_h' },
  { name: '节 (knot) 转换 米/秒 (m/s)', path: './knot-to-m_s' },
  { name: '节 (knot) 转换 千米/小时 (km/h)', path: './knot-to-km_h' },
  { name: '节 (knot) 转换 英里/小时 (mph)', path: './knot-to-mph' },
  { name: '节 (knot) 转换 英尺/秒 (ft/s)', path: './knot-to-ft_s' },
  { name: '节 (knot) 转换 英寸/小时 (in/h)', path: './knot-to-in_h' },
  { name: '节 (knot) 转换 毫米/小时 (mm/h)', path: './knot-to-mm_h' },
  { name: '英尺/秒 (ft/s) 转换 米/秒 (m/s)', path: './ft_s-to-m_s' },
  { name: '英尺/秒 (ft/s) 转换 千米/小时 (km/h)', path: './ft_s-to-km_h' },
  { name: '英尺/秒 (ft/s) 转换 英里/小时 (mph)', path: './ft_s-to-mph' },
  { name: '英尺/秒 (ft/s) 转换 节 (knot)', path: './ft_s-to-knot' },
  { name: '英尺/秒 (ft/s) 转换 英寸/小时 (in/h)', path: './ft_s-to-in_h' },
  { name: '英尺/秒 (ft/s) 转换 毫米/小时 (mm/h)', path: './ft_s-to-mm_h' },
  { name: '英寸/小时 (in/h) 转换 米/秒 (m/s)', path: './in_h-to-m_s' },
  { name: '英寸/小时 (in/h) 转换 千米/小时 (km/h)', path: './in_h-to-km_h' },
  { name: '英寸/小时 (in/h) 转换 英里/小时 (mph)', path: './in_h-to-mph' },
  { name: '英寸/小时 (in/h) 转换 节 (knot)', path: './in_h-to-knot' },
  { name: '英寸/小时 (in/h) 转换 英尺/秒 (ft/s)', path: './in_h-to-ft_s' },
  { name: '英寸/小时 (in/h) 转换 毫米/小时 (mm/h)', path: './in_h-to-mm_h' },
  { name: '毫米/小时 (mm/h) 转换 米/秒 (m/s)', path: './mm_h-to-m_s' },
  { name: '毫米/小时 (mm/h) 转换 千米/小时 (km/h)', path: './mm_h-to-km_h' },
  { name: '毫米/小时 (mm/h) 转换 英里/小时 (mph)', path: './mm_h-to-mph' },
  { name: '毫米/小时 (mm/h) 转换 节 (knot)', path: './mm_h-to-knot' },
  { name: '毫米/小时 (mm/h) 转换 英尺/秒 (ft/s)', path: './mm_h-to-ft_s' },
  { name: '毫米/小时 (mm/h) 转换 英寸/小时 (in/h)', path: './mm_h-to-in_h' }
];
export const Pressure = [
  { name: '帕斯卡 (Pa) 转换 百帕 (hPa)', path: './Pa-to-hPa' },
  { name: '帕斯卡 (Pa) 转换 千帕 (kPa)', path: './Pa-to-kPa' },
  { name: '帕斯卡 (Pa) 转换 兆帕 (MPa)', path: './Pa-to-MPa' },
  { name: '帕斯卡 (Pa) 转换 巴 (bar)', path: './Pa-to-bar' },
  { name: '帕斯卡 (Pa) 转换 托 (torr)', path: './Pa-to-torr' },
  { name: '帕斯卡 (Pa) 转换 米水柱 (mH2O)', path: './Pa-to-mH2O' },
  { name: '帕斯卡 (Pa) 转换 毫米汞柱 (mmHg)', path: './Pa-to-mmHg' },
  { name: '帕斯卡 (Pa) 转换 磅力每平方英寸 (psi)', path: './Pa-to-psi' },
  { name: '帕斯卡 (Pa) 转换 千磅力每平方英寸 (ksi)', path: './Pa-to-ksi' },
  { name: '百帕 (hPa) 转换 帕斯卡 (Pa)', path: './hPa-to-Pa' },
  { name: '百帕 (hPa) 转换 千帕 (kPa)', path: './hPa-to-kPa' },
  { name: '百帕 (hPa) 转换 兆帕 (MPa)', path: './hPa-to-MPa' },
  { name: '百帕 (hPa) 转换 巴 (bar)', path: './hPa-to-bar' },
  { name: '百帕 (hPa) 转换 托 (torr)', path: './hPa-to-torr' },
  { name: '百帕 (hPa) 转换 米水柱 (mH2O)', path: './hPa-to-mH2O' },
  { name: '百帕 (hPa) 转换 毫米汞柱 (mmHg)', path: './hPa-to-mmHg' },
  { name: '百帕 (hPa) 转换 磅力每平方英寸 (psi)', path: './hPa-to-psi' },
  { name: '百帕 (hPa) 转换 千磅力每平方英寸 (ksi)', path: './hPa-to-ksi' },
  { name: '千帕 (kPa) 转换 帕斯卡 (Pa)', path: './kPa-to-Pa' },
  { name: '千帕 (kPa) 转换 百帕 (hPa)', path: './kPa-to-hPa' },
  { name: '千帕 (kPa) 转换 兆帕 (MPa)', path: './kPa-to-MPa' },
  { name: '千帕 (kPa) 转换 巴 (bar)', path: './kPa-to-bar' },
  { name: '千帕 (kPa) 转换 托 (torr)', path: './kPa-to-torr' },
  { name: '千帕 (kPa) 转换 米水柱 (mH2O)', path: './kPa-to-mH2O' },
  { name: '千帕 (kPa) 转换 毫米汞柱 (mmHg)', path: './kPa-to-mmHg' },
  { name: '千帕 (kPa) 转换 磅力每平方英寸 (psi)', path: './kPa-to-psi' },
  { name: '千帕 (kPa) 转换 千磅力每平方英寸 (ksi)', path: './kPa-to-ksi' },
  { name: '兆帕 (MPa) 转换 帕斯卡 (Pa)', path: './MPa-to-Pa' },
  { name: '兆帕 (MPa) 转换 百帕 (hPa)', path: './MPa-to-hPa' },
  { name: '兆帕 (MPa) 转换 千帕 (kPa)', path: './MPa-to-kPa' },
  { name: '兆帕 (MPa) 转换 巴 (bar)', path: './MPa-to-bar' },
  { name: '兆帕 (MPa) 转换 托 (torr)', path: './MPa-to-torr' },
  { name: '兆帕 (MPa) 转换 米水柱 (mH2O)', path: './MPa-to-mH2O' },
  { name: '兆帕 (MPa) 转换 毫米汞柱 (mmHg)', path: './MPa-to-mmHg' },
  { name: '兆帕 (MPa) 转换 磅力每平方英寸 (psi)', path: './MPa-to-psi' },
  { name: '兆帕 (MPa) 转换 千磅力每平方英寸 (ksi)', path: './MPa-to-ksi' },
  { name: '巴 (bar) 转换 帕斯卡 (Pa)', path: './bar-to-Pa' },
  { name: '巴 (bar) 转换 百帕 (hPa)', path: './bar-to-hPa' },
  { name: '巴 (bar) 转换 千帕 (kPa)', path: './bar-to-kPa' },
  { name: '巴 (bar) 转换 兆帕 (MPa)', path: './bar-to-MPa' },
  { name: '巴 (bar) 转换 托 (torr)', path: './bar-to-torr' },
  { name: '巴 (bar) 转换 米水柱 (mH2O)', path: './bar-to-mH2O' },
  { name: '巴 (bar) 转换 毫米汞柱 (mmHg)', path: './bar-to-mmHg' },
  { name: '巴 (bar) 转换 磅力每平方英寸 (psi)', path: './bar-to-psi' },
  { name: '巴 (bar) 转换 千磅力每平方英寸 (ksi)', path: './bar-to-ksi' },
  { name: '托 (torr) 转换 帕斯卡 (Pa)', path: './torr-to-Pa' },
  { name: '托 (torr) 转换 百帕 (hPa)', path: './torr-to-hPa' },
  { name: '托 (torr) 转换 千帕 (kPa)', path: './torr-to-kPa' },
  { name: '托 (torr) 转换 兆帕 (MPa)', path: './torr-to-MPa' },
  { name: '托 (torr) 转换 巴 (bar)', path: './torr-to-bar' },
  { name: '托 (torr) 转换 米水柱 (mH2O)', path: './torr-to-mH2O' },
  { name: '托 (torr) 转换 毫米汞柱 (mmHg)', path: './torr-to-mmHg' },
  { name: '托 (torr) 转换 磅力每平方英寸 (psi)', path: './torr-to-psi' },
  { name: '托 (torr) 转换 千磅力每平方英寸 (ksi)', path: './torr-to-ksi' },
  { name: '米水柱 (mH2O) 转换 帕斯卡 (Pa)', path: './mH2O-to-Pa' },
  { name: '米水柱 (mH2O) 转换 百帕 (hPa)', path: './mH2O-to-hPa' },
  { name: '米水柱 (mH2O) 转换 千帕 (kPa)', path: './mH2O-to-kPa' },
  { name: '米水柱 (mH2O) 转换 兆帕 (MPa)', path: './mH2O-to-MPa' },
  { name: '米水柱 (mH2O) 转换 巴 (bar)', path: './mH2O-to-bar' },
  { name: '米水柱 (mH2O) 转换 托 (torr)', path: './mH2O-to-torr' },
  { name: '米水柱 (mH2O) 转换 毫米汞柱 (mmHg)', path: './mH2O-to-mmHg' },
  { name: '米水柱 (mH2O) 转换 磅力每平方英寸 (psi)', path: './mH2O-to-psi' },
  { name: '米水柱 (mH2O) 转换 千磅力每平方英寸 (ksi)', path: './mH2O-to-ksi' },
  { name: '毫米汞柱 (mmHg) 转换 帕斯卡 (Pa)', path: './mmHg-to-Pa' },
  { name: '毫米汞柱 (mmHg) 转换 百帕 (hPa)', path: './mmHg-to-hPa' },
  { name: '毫米汞柱 (mmHg) 转换 千帕 (kPa)', path: './mmHg-to-kPa' },
  { name: '毫米汞柱 (mmHg) 转换 兆帕 (MPa)', path: './mmHg-to-MPa' },
  { name: '毫米汞柱 (mmHg) 转换 巴 (bar)', path: './mmHg-to-bar' },
  { name: '毫米汞柱 (mmHg) 转换 托 (torr)', path: './mmHg-to-torr' },
  { name: '毫米汞柱 (mmHg) 转换 米水柱 (mH2O)', path: './mmHg-to-mH2O' },
  { name: '毫米汞柱 (mmHg) 转换 磅力每平方英寸 (psi)', path: './mmHg-to-psi' },
  { name: '毫米汞柱 (mmHg) 转换 千磅力每平方英寸 (ksi)', path: './mmHg-to-ksi' },
  { name: '磅力每平方英寸 (psi) 转换 帕斯卡 (Pa)', path: './psi-to-Pa' },
  { name: '磅力每平方英寸 (psi) 转换 百帕 (hPa)', path: './psi-to-hPa' },
  { name: '磅力每平方英寸 (psi) 转换 千帕 (kPa)', path: './psi-to-kPa' },
  { name: '磅力每平方英寸 (psi) 转换 兆帕 (MPa)', path: './psi-to-MPa' },
  { name: '磅力每平方英寸 (psi) 转换 巴 (bar)', path: './psi-to-bar' },
  { name: '磅力每平方英寸 (psi) 转换 托 (torr)', path: './psi-to-torr' },
  { name: '磅力每平方英寸 (psi) 转换 米水柱 (mH2O)', path: './psi-to-mH2O' },
  { name: '磅力每平方英寸 (psi) 转换 毫米汞柱 (mmHg)', path: './psi-to-mmHg' },
  { name: '磅力每平方英寸 (psi) 转换 千磅力每平方英寸 (ksi)', path: './psi-to-ksi' },
  { name: '千磅力每平方英寸 (ksi) 转换 帕斯卡 (Pa)', path: './ksi-to-Pa' },
  { name: '千磅力每平方英寸 (ksi) 转换 百帕 (hPa)', path: './ksi-to-hPa' },
  { name: '千磅力每平方英寸 (ksi) 转换 千帕 (kPa)', path: './ksi-to-kPa' },
  { name: '千磅力每平方英寸 (ksi) 转换 兆帕 (MPa)', path: './ksi-to-MPa' },
  { name: '千磅力每平方英寸 (ksi) 转换 巴 (bar)', path: './ksi-to-bar' },
  { name: '千磅力每平方英寸 (ksi) 转换 托 (torr)', path: './ksi-to-torr' },
  { name: '千磅力每平方英寸 (ksi) 转换 米水柱 (mH2O)', path: './ksi-to-mH2O' },
  { name: '千磅力每平方英寸 (ksi) 转换 毫米汞柱 (mmHg)', path: './ksi-to-mmHg' },
  { name: '千磅力每平方英寸 (ksi) 转换 磅力每平方英寸 (psi)', path: './ksi-to-psi' }
];
export const Digital = [
  { name: '比特 (bit) 转换 字节 (byte)', path: './bit-to-byte' },
  { name: '比特 (bit) 转换 千比特 (kb)', path: './bit-to-kb' },
  { name: '比特 (bit) 转换 兆比特 (Mb)', path: './bit-to-Mb' },
  { name: '比特 (bit) 转换 吉比特 (Gb)', path: './bit-to-Gb' },
  { name: '比特 (bit) 转换 太比特 (Tb)', path: './bit-to-Tb' },
  { name: '比特 (bit) 转换 千字节 (kB)', path: './bit-to-kB' },
  { name: '比特 (bit) 转换 兆字节 (MB)', path: './bit-to-MB' },
  { name: '比特 (bit) 转换 吉字节 (GB)', path: './bit-to-GB' },
  { name: '比特 (bit) 转换 太字节 (TB)', path: './bit-to-TB' },
  { name: '比特 (bit) 转换 千字节 (KiB)', path: './bit-to-KiB' },
  { name: '比特 (bit) 转换 兆字节 (MiB)', path: './bit-to-MiB' },
  { name: '比特 (bit) 转换 吉字节 (GiB)', path: './bit-to-GiB' },
  { name: '比特 (bit) 转换 太字节 (TiB)', path: './bit-to-TiB' },
  { name: '字节 (byte) 转换 比特 (bit)', path: './byte-to-bit' },
  { name: '字节 (byte) 转换 千比特 (kb)', path: './byte-to-kb' },
  { name: '字节 (byte) 转换 兆比特 (Mb)', path: './byte-to-Mb' },
  { name: '字节 (byte) 转换 吉比特 (Gb)', path: './byte-to-Gb' },
  { name: '字节 (byte) 转换 太比特 (Tb)', path: './byte-to-Tb' },
  { name: '字节 (byte) 转换 千字节 (kB)', path: './byte-to-kB' },
  { name: '字节 (byte) 转换 兆字节 (MB)', path: './byte-to-MB' },
  { name: '字节 (byte) 转换 吉字节 (GB)', path: './byte-to-GB' },
  { name: '字节 (byte) 转换 太字节 (TB)', path: './byte-to-TB' },
  { name: '字节 (byte) 转换 千字节 (KiB)', path: './byte-to-KiB' },
  { name: '字节 (byte) 转换 兆字节 (MiB)', path: './byte-to-MiB' },
  { name: '字节 (byte) 转换 吉字节 (GiB)', path: './byte-to-GiB' },
  { name: '字节 (byte) 转换 太字节 (TiB)', path: './byte-to-TiB' },
  { name: '千比特 (kb) 转换 比特 (bit)', path: './kb-to-bit' },
  { name: '千比特 (kb) 转换 字节 (byte)', path: './kb-to-byte' },
  { name: '千比特 (kb) 转换 兆比特 (Mb)', path: './kb-to-Mb' },
  { name: '千比特 (kb) 转换 吉比特 (Gb)', path: './kb-to-Gb' },
  { name: '千比特 (kb) 转换 太比特 (Tb)', path: './kb-to-Tb' },
  { name: '千比特 (kb) 转换 千字节 (kB)', path: './kb-to-kB' },
  { name: '千比特 (kb) 转换 兆字节 (MB)', path: './kb-to-MB' },
  { name: '千比特 (kb) 转换 吉字节 (GB)', path: './kb-to-GB' },
  { name: '千比特 (kb) 转换 太字节 (TB)', path: './kb-to-TB' },
  { name: '千比特 (kb) 转换 千字节 (KiB)', path: './kb-to-KiB' },
  { name: '千比特 (kb) 转换 兆字节 (MiB)', path: './kb-to-MiB' },
  { name: '千比特 (kb) 转换 吉字节 (GiB)', path: './kb-to-GiB' },
  { name: '千比特 (kb) 转换 太字节 (TiB)', path: './kb-to-TiB' },
  { name: '兆比特 (Mb) 转换 比特 (bit)', path: './Mb-to-bit' },
  { name: '兆比特 (Mb) 转换 字节 (byte)', path: './Mb-to-byte' },
  { name: '兆比特 (Mb) 转换 千比特 (kb)', path: './Mb-to-kb' },
  { name: '兆比特 (Mb) 转换 吉比特 (Gb)', path: './Mb-to-Gb' },
  { name: '兆比特 (Mb) 转换 太比特 (Tb)', path: './Mb-to-Tb' },
  { name: '兆比特 (Mb) 转换 千字节 (kB)', path: './Mb-to-kB' },
  { name: '兆比特 (Mb) 转换 兆字节 (MB)', path: './Mb-to-MB' },
  { name: '兆比特 (Mb) 转换 吉字节 (GB)', path: './Mb-to-GB' },
  { name: '兆比特 (Mb) 转换 太字节 (TB)', path: './Mb-to-TB' },
  { name: '兆比特 (Mb) 转换 千字节 (KiB)', path: './Mb-to-KiB' },
  { name: '兆比特 (Mb) 转换 兆字节 (MiB)', path: './Mb-to-MiB' },
  { name: '兆比特 (Mb) 转换 吉字节 (GiB)', path: './Mb-to-GiB' },
  { name: '兆比特 (Mb) 转换 太字节 (TiB)', path: './Mb-to-TiB' },
  { name: '吉比特 (Gb) 转换 比特 (bit)', path: './Gb-to-bit' },
  { name: '吉比特 (Gb) 转换 字节 (byte)', path: './Gb-to-byte' },
  { name: '吉比特 (Gb) 转换 千比特 (kb)', path: './Gb-to-kb' },
  { name: '吉比特 (Gb) 转换 兆比特 (Mb)', path: './Gb-to-Mb' },
  { name: '吉比特 (Gb) 转换 太比特 (Tb)', path: './Gb-to-Tb' },
  { name: '吉比特 (Gb) 转换 千字节 (kB)', path: './Gb-to-kB' },
  { name: '吉比特 (Gb) 转换 兆字节 (MB)', path: './Gb-to-MB' },
  { name: '吉比特 (Gb) 转换 吉字节 (GB)', path: './Gb-to-GB' },
  { name: '吉比特 (Gb) 转换 太字节 (TB)', path: './Gb-to-TB' },
  { name: '吉比特 (Gb) 转换 千字节 (KiB)', path: './Gb-to-KiB' },
  { name: '吉比特 (Gb) 转换 兆字节 (MiB)', path: './Gb-to-MiB' },
  { name: '吉比特 (Gb) 转换 吉字节 (GiB)', path: './Gb-to-GiB' },
  { name: '吉比特 (Gb) 转换 太字节 (TiB)', path: './Gb-to-TiB' },
  { name: '太比特 (Tb) 转换 比特 (bit)', path: './Tb-to-bit' },
  { name: '太比特 (Tb) 转换 字节 (byte)', path: './Tb-to-byte' },
  { name: '太比特 (Tb) 转换 千比特 (kb)', path: './Tb-to-kb' },
  { name: '太比特 (Tb) 转换 兆比特 (Mb)', path: './Tb-to-Mb' },
  { name: '太比特 (Tb) 转换 吉比特 (Gb)', path: './Tb-to-Gb' },
  { name: '太比特 (Tb) 转换 千字节 (kB)', path: './Tb-to-kB' },
  { name: '太比特 (Tb) 转换 兆字节 (MB)', path: './Tb-to-MB' },
  { name: '太比特 (Tb) 转换 吉字节 (GB)', path: './Tb-to-GB' },
  { name: '太比特 (Tb) 转换 太字节 (TB)', path: './Tb-to-TB' },
  { name: '太比特 (Tb) 转换 千字节 (KiB)', path: './Tb-to-KiB' },
  { name: '太比特 (Tb) 转换 兆字节 (MiB)', path: './Tb-to-MiB' },
  { name: '太比特 (Tb) 转换 吉字节 (GiB)', path: './Tb-to-GiB' },
  { name: '太比特 (Tb) 转换 太字节 (TiB)', path: './Tb-to-TiB' },
  { name: '千字节 (kB) 转换 比特 (bit)', path: './kB-to-bit' },
  { name: '千字节 (kB) 转换 字节 (byte)', path: './kB-to-byte' },
  { name: '千字节 (kB) 转换 千比特 (kb)', path: './kB-to-kb' },
  { name: '千字节 (kB) 转换 兆比特 (Mb)', path: './kB-to-Mb' },
  { name: '千字节 (kB) 转换 吉比特 (Gb)', path: './kB-to-Gb' },
  { name: '千字节 (kB) 转换 太比特 (Tb)', path: './kB-to-Tb' },
  { name: '千字节 (kB) 转换 兆字节 (MB)', path: './kB-to-MB' },
  { name: '千字节 (kB) 转换 吉字节 (GB)', path: './kB-to-GB' },
  { name: '千字节 (kB) 转换 太字节 (TB)', path: './kB-to-TB' },
  { name: '千字节 (kB) 转换 千字节 (KiB)', path: './kB-to-KiB' },
  { name: '千字节 (kB) 转换 兆字节 (MiB)', path: './kB-to-MiB' },
  { name: '千字节 (kB) 转换 吉字节 (GiB)', path: './kB-to-GiB' },
  { name: '千字节 (kB) 转换 太字节 (TiB)', path: './kB-to-TiB' },
  { name: '兆字节 (MB) 转换 比特 (bit)', path: './MB-to-bit' },
  { name: '兆字节 (MB) 转换 字节 (byte)', path: './MB-to-byte' },
  { name: '兆字节 (MB) 转换 千比特 (kb)', path: './MB-to-kb' },
  { name: '兆字节 (MB) 转换 兆比特 (Mb)', path: './MB-to-Mb' },
  { name: '兆字节 (MB) 转换 吉比特 (Gb)', path: './MB-to-Gb' },
  { name: '兆字节 (MB) 转换 太比特 (Tb)', path: './MB-to-Tb' },
  { name: '兆字节 (MB) 转换 千字节 (kB)', path: './MB-to-kB' },
  { name: '兆字节 (MB) 转换 吉字节 (GB)', path: './MB-to-GB' },
  { name: '兆字节 (MB) 转换 太字节 (TB)', path: './MB-to-TB' },
  { name: '兆字节 (MB) 转换 千字节 (KiB)', path: './MB-to-KiB' },
  { name: '兆字节 (MB) 转换 兆字节 (MiB)', path: './MB-to-MiB' },
  { name: '兆字节 (MB) 转换 吉字节 (GiB)', path: './MB-to-GiB' },
  { name: '兆字节 (MB) 转换 太字节 (TiB)', path: './MB-to-TiB' },
  { name: '吉字节 (GB) 转换 比特 (bit)', path: './GB-to-bit' },
  { name: '吉字节 (GB) 转换 字节 (byte)', path: './GB-to-byte' },
  { name: '吉字节 (GB) 转换 千比特 (kb)', path: './GB-to-kb' },
  { name: '吉字节 (GB) 转换 兆比特 (Mb)', path: './GB-to-Mb' },
  { name: '吉字节 (GB) 转换 吉比特 (Gb)', path: './GB-to-Gb' },
  { name: '吉字节 (GB) 转换 太比特 (Tb)', path: './GB-to-Tb' },
  { name: '吉字节 (GB) 转换 千字节 (kB)', path: './GB-to-kB' },
  { name: '吉字节 (GB) 转换 兆字节 (MB)', path: './GB-to-MB' },
  { name: '吉字节 (GB) 转换 太字节 (TB)', path: './GB-to-TB' },
  { name: '吉字节 (GB) 转换 千字节 (KiB)', path: './GB-to-KiB' },
  { name: '吉字节 (GB) 转换 兆字节 (MiB)', path: './GB-to-MiB' },
  { name: '吉字节 (GB) 转换 吉字节 (GiB)', path: './GB-to-GiB' },
  { name: '吉字节 (GB) 转换 太字节 (TiB)', path: './GB-to-TiB' },
  { name: '太字节 (TB) 转换 比特 (bit)', path: './TB-to-bit' },
  { name: '太字节 (TB) 转换 字节 (byte)', path: './TB-to-byte' },
  { name: '太字节 (TB) 转换 千比特 (kb)', path: './TB-to-kb' },
  { name: '太字节 (TB) 转换 兆比特 (Mb)', path: './TB-to-Mb' },
  { name: '太字节 (TB) 转换 吉比特 (Gb)', path: './TB-to-Gb' },
  { name: '太字节 (TB) 转换 太比特 (Tb)', path: './TB-to-Tb' },
  { name: '太字节 (TB) 转换 千字节 (kB)', path: './TB-to-kB' },
  { name: '太字节 (TB) 转换 兆字节 (MB)', path: './TB-to-MB' },
  { name: '太字节 (TB) 转换 吉字节 (GB)', path: './TB-to-GB' },
  { name: '太字节 (TB) 转换 千字节 (KiB)', path: './TB-to-KiB' },
  { name: '太字节 (TB) 转换 兆字节 (MiB)', path: './TB-to-MiB' },
  { name: '太字节 (TB) 转换 吉字节 (GiB)', path: './TB-to-GiB' },
  { name: '太字节 (TB) 转换 太字节 (TiB)', path: './TB-to-TiB' },
  { name: '千字节 (KiB) 转换 比特 (bit)', path: './KiB-to-bit' },
  { name: '千字节 (KiB) 转换 字节 (byte)', path: './KiB-to-byte' },
  { name: '千字节 (KiB) 转换 千比特 (kb)', path: './KiB-to-kb' },
  { name: '千字节 (KiB) 转换 兆比特 (Mb)', path: './KiB-to-Mb' },
  { name: '千字节 (KiB) 转换 吉比特 (Gb)', path: './KiB-to-Gb' },
  { name: '千字节 (KiB) 转换 太比特 (Tb)', path: './KiB-to-Tb' },
  { name: '千字节 (KiB) 转换 千字节 (kB)', path: './KiB-to-kB' },
  { name: '千字节 (KiB) 转换 兆字节 (MB)', path: './KiB-to-MB' },
  { name: '千字节 (KiB) 转换 吉字节 (GB)', path: './KiB-to-GB' },
  { name: '千字节 (KiB) 转换 太字节 (TB)', path: './KiB-to-TB' },
  { name: '千字节 (KiB) 转换 兆字节 (MiB)', path: './KiB-to-MiB' },
  { name: '千字节 (KiB) 转换 吉字节 (GiB)', path: './KiB-to-GiB' },
  { name: '千字节 (KiB) 转换 太字节 (TiB)', path: './KiB-to-TiB' },
  { name: '兆字节 (MiB) 转换 比特 (bit)', path: './MiB-to-bit' },
  { name: '兆字节 (MiB) 转换 字节 (byte)', path: './MiB-to-byte' },
  { name: '兆字节 (MiB) 转换 千比特 (kb)', path: './MiB-to-kb' },
  { name: '兆字节 (MiB) 转换 兆比特 (Mb)', path: './MiB-to-Mb' },
  { name: '兆字节 (MiB) 转换 吉比特 (Gb)', path: './MiB-to-Gb' },
  { name: '兆字节 (MiB) 转换 太比特 (Tb)', path: './MiB-to-Tb' },
  { name: '兆字节 (MiB) 转换 千字节 (kB)', path: './MiB-to-kB' },
  { name: '兆字节 (MiB) 转换 兆字节 (MB)', path: './MiB-to-MB' },
  { name: '兆字节 (MiB) 转换 吉字节 (GB)', path: './MiB-to-GB' },
  { name: '兆字节 (MiB) 转换 太字节 (TB)', path: './MiB-to-TB' },
  { name: '兆字节 (MiB) 转换 千字节 (KiB)', path: './MiB-to-KiB' },
  { name: '兆字节 (MiB) 转换 吉字节 (GiB)', path: './MiB-to-GiB' },
  { name: '兆字节 (MiB) 转换 太字节 (TiB)', path: './MiB-to-TiB' },
  { name: '吉字节 (GiB) 转换 比特 (bit)', path: './GiB-to-bit' },
  { name: '吉字节 (GiB) 转换 字节 (byte)', path: './GiB-to-byte' },
  { name: '吉字节 (GiB) 转换 千比特 (kb)', path: './GiB-to-kb' },
  { name: '吉字节 (GiB) 转换 兆比特 (Mb)', path: './GiB-to-Mb' },
  { name: '吉字节 (GiB) 转换 吉比特 (Gb)', path: './GiB-to-Gb' },
  { name: '吉字节 (GiB) 转换 太比特 (Tb)', path: './GiB-to-Tb' },
  { name: '吉字节 (GiB) 转换 千字节 (kB)', path: './GiB-to-kB' },
  { name: '吉字节 (GiB) 转换 兆字节 (MB)', path: './GiB-to-MB' },
  { name: '吉字节 (GiB) 转换 吉字节 (GB)', path: './GiB-to-GB' },
  { name: '吉字节 (GiB) 转换 太字节 (TB)', path: './GiB-to-TB' },
  { name: '吉字节 (GiB) 转换 千字节 (KiB)', path: './GiB-to-KiB' },
  { name: '吉字节 (GiB) 转换 兆字节 (MiB)', path: './GiB-to-MiB' },
  { name: '吉字节 (GiB) 转换 太字节 (TiB)', path: './GiB-to-TiB' },
  { name: '太字节 (TiB) 转换 比特 (bit)', path: './TiB-to-bit' },
  { name: '太字节 (TiB) 转换 字节 (byte)', path: './TiB-to-byte' },
  { name: '太字节 (TiB) 转换 千比特 (kb)', path: './TiB-to-kb' },
  { name: '太字节 (TiB) 转换 兆比特 (Mb)', path: './TiB-to-Mb' },
  { name: '太字节 (TiB) 转换 吉比特 (Gb)', path: './TiB-to-Gb' },
  { name: '太字节 (TiB) 转换 太比特 (Tb)', path: './TiB-to-Tb' },
  { name: '太字节 (TiB) 转换 千字节 (kB)', path: './TiB-to-kB' },
  { name: '太字节 (TiB) 转换 兆字节 (MB)', path: './TiB-to-MB' },
  { name: '太字节 (TiB) 转换 吉字节 (GB)', path: './TiB-to-GB' },
  { name: '太字节 (TiB) 转换 太字节 (TB)', path: './TiB-to-TB' },
  { name: '太字节 (TiB) 转换 千字节 (KiB)', path: './TiB-to-KiB' },
  { name: '太字节 (TiB) 转换 兆字节 (MiB)', path: './TiB-to-MiB' },
  { name: '太字节 (TiB) 转换 吉字节 (GiB)', path: './TiB-to-GiB' }
];
export const Voltage = [
  { name: '伏特 (V) 转换 毫伏 (mV)', path: './V-to-mV' },
  { name: '伏特 (V) 转换 千伏 (kV)', path: './V-to-kV' },
  { name: '毫伏 (mV) 转换 伏特 (V)', path: './mV-to-V' },
  { name: '毫伏 (mV) 转换 千伏 (kV)', path: './mV-to-kV' },
  { name: '千伏 (kV) 转换 伏特 (V)', path: './kV-to-V' },
  { name: '千伏 (kV) 转换 毫伏 (mV)', path: './kV-to-mV' }
];
export const Current = [
  { name: '安培 (A) 转换 毫安 (mA)', path: './A-to-mA' },
  { name: '安培 (A) 转换 千安 (kA)', path: './A-to-kA' },
  { name: '毫安 (mA) 转换 安培 (A)', path: './mA-to-A' },
  { name: '毫安 (mA) 转换 千安 (kA)', path: './mA-to-kA' },
  { name: '千安 (kA) 转换 安培 (A)', path: './kA-to-A' },
  { name: '千安 (kA) 转换 毫安 (mA)', path: './kA-to-mA' }
];
export const Power = [
  { name: '瓦特 (W) 转换 毫瓦 (mW)', path: './W-to-mW' },
  { name: '瓦特 (W) 转换 千瓦 (kW)', path: './W-to-kW' },
  { name: '瓦特 (W) 转换 兆瓦 (MW)', path: './W-to-MW' },
  { name: '瓦特 (W) 转换 吉瓦 (GW)', path: './W-to-GW' },
  { name: '瓦特 (W) 转换 马力 (PS)', path: './W-to-PS' },
  { name: '瓦特 (W) 转换 英热单位/秒 (Btu/s)', path: './W-to-Btu_s' },
  { name: '瓦特 (W) 转换 英尺磅/秒 (ft-lb/s)', path: './W-to-ft-lb_s' },
  { name: '瓦特 (W) 转换 马力 (hp)', path: './W-to-hp' },
  { name: '毫瓦 (mW) 转换 瓦特 (W)', path: './mW-to-W' },
  { name: '毫瓦 (mW) 转换 千瓦 (kW)', path: './mW-to-kW' },
  { name: '毫瓦 (mW) 转换 兆瓦 (MW)', path: './mW-to-MW' },
  { name: '毫瓦 (mW) 转换 吉瓦 (GW)', path: './mW-to-GW' },
  { name: '毫瓦 (mW) 转换 马力 (PS)', path: './mW-to-PS' },
  { name: '毫瓦 (mW) 转换 英热单位/秒 (Btu/s)', path: './mW-to-Btu_s' },
  { name: '毫瓦 (mW) 转换 英尺磅/秒 (ft-lb/s)', path: './mW-to-ft-lb_s' },
  { name: '毫瓦 (mW) 转换 马力 (hp)', path: './mW-to-hp' },
  { name: '千瓦 (kW) 转换 瓦特 (W)', path: './kW-to-W' },
  { name: '千瓦 (kW) 转换 毫瓦 (mW)', path: './kW-to-mW' },
  { name: '千瓦 (kW) 转换 兆瓦 (MW)', path: './kW-to-MW' },
  { name: '千瓦 (kW) 转换 吉瓦 (GW)', path: './kW-to-GW' },
  { name: '千瓦 (kW) 转换 马力 (PS)', path: './kW-to-PS' },
  { name: '千瓦 (kW) 转换 英热单位/秒 (Btu/s)', path: './kW-to-Btu_s' },
  { name: '千瓦 (kW) 转换 英尺磅/秒 (ft-lb/s)', path: './kW-to-ft-lb_s' },
  { name: '千瓦 (kW) 转换 马力 (hp)', path: './kW-to-hp' },
  { name: '兆瓦 (MW) 转换 瓦特 (W)', path: './MW-to-W' },
  { name: '兆瓦 (MW) 转换 毫瓦 (mW)', path: './MW-to-mW' },
  { name: '兆瓦 (MW) 转换 千瓦 (kW)', path: './MW-to-kW' },
  { name: '兆瓦 (MW) 转换 吉瓦 (GW)', path: './MW-to-GW' },
  { name: '兆瓦 (MW) 转换 马力 (PS)', path: './MW-to-PS' },
  { name: '兆瓦 (MW) 转换 英热单位/秒 (Btu/s)', path: './MW-to-Btu_s' },
  { name: '兆瓦 (MW) 转换 英尺磅/秒 (ft-lb/s)', path: './MW-to-ft-lb_s' },
  { name: '兆瓦 (MW) 转换 马力 (hp)', path: './MW-to-hp' },
  { name: '吉瓦 (GW) 转换 瓦特 (W)', path: './GW-to-W' },
  { name: '吉瓦 (GW) 转换 毫瓦 (mW)', path: './GW-to-mW' },
  { name: '吉瓦 (GW) 转换 千瓦 (kW)', path: './GW-to-kW' },
  { name: '吉瓦 (GW) 转换 兆瓦 (MW)', path: './GW-to-MW' },
  { name: '吉瓦 (GW) 转换 马力 (PS)', path: './GW-to-PS' },
  { name: '吉瓦 (GW) 转换 英热单位/秒 (Btu/s)', path: './GW-to-Btu_s' },
  { name: '吉瓦 (GW) 转换 英尺磅/秒 (ft-lb/s)', path: './GW-to-ft-lb_s' },
  { name: '吉瓦 (GW) 转换 马力 (hp)', path: './GW-to-hp' },
  { name: '马力 (PS) 转换 瓦特 (W)', path: './PS-to-W' },
  { name: '马力 (PS) 转换 毫瓦 (mW)', path: './PS-to-mW' },
  { name: '马力 (PS) 转换 千瓦 (kW)', path: './PS-to-kW' },
  { name: '马力 (PS) 转换 兆瓦 (MW)', path: './PS-to-MW' },
  { name: '马力 (PS) 转换 吉瓦 (GW)', path: './PS-to-GW' },
  { name: '马力 (PS) 转换 英热单位/秒 (Btu/s)', path: './PS-to-Btu_s' },
  { name: '马力 (PS) 转换 英尺磅/秒 (ft-lb/s)', path: './PS-to-ft-lb_s' },
  { name: '马力 (PS) 转换 马力 (hp)', path: './PS-to-hp' },
  { name: '英热单位/秒 (Btu/s) 转换 瓦特 (W)', path: './Btu_s-to-W' },
  { name: '英热单位/秒 (Btu/s) 转换 毫瓦 (mW)', path: './Btu_s-to-mW' },
  { name: '英热单位/秒 (Btu/s) 转换 千瓦 (kW)', path: './Btu_s-to-kW' },
  { name: '英热单位/秒 (Btu/s) 转换 兆瓦 (MW)', path: './Btu_s-to-MW' },
  { name: '英热单位/秒 (Btu/s) 转换 吉瓦 (GW)', path: './Btu_s-to-GW' },
  { name: '英热单位/秒 (Btu/s) 转换 马力 (PS)', path: './Btu_s-to-PS' },
  { name: '英热单位/秒 (Btu/s) 转换 英尺磅/秒 (ft-lb/s)', path: './Btu_s-to-ft-lb_s' },
  { name: '英热单位/秒 (Btu/s) 转换 马力 (hp)', path: './Btu_s-to-hp' },
  { name: '英尺磅/秒 (ft-lb/s) 转换 瓦特 (W)', path: './ft-lb_s-to-W' },
  { name: '英尺磅/秒 (ft-lb/s) 转换 毫瓦 (mW)', path: './ft-lb_s-to-mW' },
  { name: '英尺磅/秒 (ft-lb/s) 转换 千瓦 (kW)', path: './ft-lb_s-to-kW' },
  { name: '英尺磅/秒 (ft-lb/s) 转换 兆瓦 (MW)', path: './ft-lb_s-to-MW' },
  { name: '英尺磅/秒 (ft-lb/s) 转换 吉瓦 (GW)', path: './ft-lb_s-to-GW' },
  { name: '英尺磅/秒 (ft-lb/s) 转换 马力 (PS)', path: './ft-lb_s-to-PS' },
  { name: '英尺磅/秒 (ft-lb/s) 转换 英热单位/秒 (Btu/s)', path: './ft-lb_s-to-Btu_s' },
  { name: '英尺磅/秒 (ft-lb/s) 转换 马力 (hp)', path: './ft-lb_s-to-hp' },
  { name: '马力 (hp) 转换 瓦特 (W)', path: './hp-to-W' },
  { name: '马力 (hp) 转换 毫瓦 (mW)', path: './hp-to-mW' },
  { name: '马力 (hp) 转换 千瓦 (kW)', path: './hp-to-kW' },
  { name: '马力 (hp) 转换 兆瓦 (MW)', path: './hp-to-MW' },
  { name: '马力 (hp) 转换 吉瓦 (GW)', path: './hp-to-GW' },
  { name: '马力 (hp) 转换 马力 (PS)', path: './hp-to-PS' },
  { name: '马力 (hp) 转换 英热单位/秒 (Btu/s)', path: './hp-to-Btu_s' },
  { name: '马力 (hp) 转换 英尺磅/秒 (ft-lb/s)', path: './hp-to-ft-lb_s' }
];
export const Energy = [
  { name: '瓦秒 (Ws) 转换 瓦米 (Wm)', path: './Ws-to-Wm' },
  { name: '瓦秒 (Ws) 转换 瓦时 (Wh)', path: './Ws-to-Wh' },
  { name: '瓦秒 (Ws) 转换 毫瓦时 (mWh)', path: './Ws-to-mWh' },
  { name: '瓦秒 (Ws) 转换 千瓦时 (kWh)', path: './Ws-to-kWh' },
  { name: '瓦秒 (Ws) 转换 兆瓦时 (MWh)', path: './Ws-to-MWh' },
  { name: '瓦秒 (Ws) 转换 吉瓦时 (GWh)', path: './Ws-to-GWh' },
  { name: '瓦秒 (Ws) 转换 焦耳 (J)', path: './Ws-to-J' },
  { name: '瓦秒 (Ws) 转换 千焦 (kJ)', path: './Ws-to-kJ' },
  { name: '瓦秒 (Ws) 转换 兆焦 (MJ)', path: './Ws-to-MJ' },
  { name: '瓦秒 (Ws) 转换 吉焦 (GJ)', path: './Ws-to-GJ' },
  { name: '瓦米 (Wm) 转换 瓦秒 (Ws)', path: './Wm-to-Ws' },
  { name: '瓦米 (Wm) 转换 瓦时 (Wh)', path: './Wm-to-Wh' },
  { name: '瓦米 (Wm) 转换 毫瓦时 (mWh)', path: './Wm-to-mWh' },
  { name: '瓦米 (Wm) 转换 千瓦时 (kWh)', path: './Wm-to-kWh' },
  { name: '瓦米 (Wm) 转换 兆瓦时 (MWh)', path: './Wm-to-MWh' },
  { name: '瓦米 (Wm) 转换 吉瓦时 (GWh)', path: './Wm-to-GWh' },
  { name: '瓦米 (Wm) 转换 焦耳 (J)', path: './Wm-to-J' },
  { name: '瓦米 (Wm) 转换 千焦 (kJ)', path: './Wm-to-kJ' },
  { name: '瓦米 (Wm) 转换 兆焦 (MJ)', path: './Wm-to-MJ' },
  { name: '瓦米 (Wm) 转换 吉焦 (GJ)', path: './Wm-to-GJ' },
  { name: '瓦时 (Wh) 转换 瓦秒 (Ws)', path: './Wh-to-Ws' },
  { name: '瓦时 (Wh) 转换 瓦米 (Wm)', path: './Wh-to-Wm' },
  { name: '瓦时 (Wh) 转换 毫瓦时 (mWh)', path: './Wh-to-mWh' },
  { name: '瓦时 (Wh) 转换 千瓦时 (kWh)', path: './Wh-to-kWh' },
  { name: '瓦时 (Wh) 转换 兆瓦时 (MWh)', path: './Wh-to-MWh' },
  { name: '瓦时 (Wh) 转换 吉瓦时 (GWh)', path: './Wh-to-GWh' },
  { name: '瓦时 (Wh) 转换 焦耳 (J)', path: './Wh-to-J' },
  { name: '瓦时 (Wh) 转换 千焦 (kJ)', path: './Wh-to-kJ' },
  { name: '瓦时 (Wh) 转换 兆焦 (MJ)', path: './Wh-to-MJ' },
  { name: '瓦时 (Wh) 转换 吉焦 (GJ)', path: './Wh-to-GJ' },
  { name: '毫瓦时 (mWh) 转换 瓦秒 (Ws)', path: './mWh-to-Ws' },
  { name: '毫瓦时 (mWh) 转换 瓦米 (Wm)', path: './mWh-to-Wm' },
  { name: '毫瓦时 (mWh) 转换 瓦时 (Wh)', path: './mWh-to-Wh' },
  { name: '毫瓦时 (mWh) 转换 千瓦时 (kWh)', path: './mWh-to-kWh' },
  { name: '毫瓦时 (mWh) 转换 兆瓦时 (MWh)', path: './mWh-to-MWh' },
  { name: '毫瓦时 (mWh) 转换 吉瓦时 (GWh)', path: './mWh-to-GWh' },
  { name: '毫瓦时 (mWh) 转换 焦耳 (J)', path: './mWh-to-J' },
  { name: '毫瓦时 (mWh) 转换 千焦 (kJ)', path: './mWh-to-kJ' },
  { name: '毫瓦时 (mWh) 转换 兆焦 (MJ)', path: './mWh-to-MJ' },
  { name: '毫瓦时 (mWh) 转换 吉焦 (GJ)', path: './mWh-to-GJ' },
  { name: '千瓦时 (kWh) 转换 瓦秒 (Ws)', path: './kWh-to-Ws' },
  { name: '千瓦时 (kWh) 转换 瓦米 (Wm)', path: './kWh-to-Wm' },
  { name: '千瓦时 (kWh) 转换 瓦时 (Wh)', path: './kWh-to-Wh' },
  { name: '千瓦时 (kWh) 转换 毫瓦时 (mWh)', path: './kWh-to-mWh' },
  { name: '千瓦时 (kWh) 转换 兆瓦时 (MWh)', path: './kWh-to-MWh' },
  { name: '千瓦时 (kWh) 转换 吉瓦时 (GWh)', path: './kWh-to-GWh' },
  { name: '千瓦时 (kWh) 转换 焦耳 (J)', path: './kWh-to-J' },
  { name: '千瓦时 (kWh) 转换 千焦 (kJ)', path: './kWh-to-kJ' },
  { name: '千瓦时 (kWh) 转换 兆焦 (MJ)', path: './kWh-to-MJ' },
  { name: '千瓦时 (kWh) 转换 吉焦 (GJ)', path: './kWh-to-GJ' },
  { name: '兆瓦时 (MWh) 转换 瓦秒 (Ws)', path: './MWh-to-Ws' },
  { name: '兆瓦时 (MWh) 转换 瓦米 (Wm)', path: './MWh-to-Wm' },
  { name: '兆瓦时 (MWh) 转换 瓦时 (Wh)', path: './MWh-to-Wh' },
  { name: '兆瓦时 (MWh) 转换 毫瓦时 (mWh)', path: './MWh-to-mWh' },
  { name: '兆瓦时 (MWh) 转换 千瓦时 (kWh)', path: './MWh-to-kWh' },
  { name: '兆瓦时 (MWh) 转换 吉瓦时 (GWh)', path: './MWh-to-GWh' },
  { name: '兆瓦时 (MWh) 转换 焦耳 (J)', path: './MWh-to-J' },
  { name: '兆瓦时 (MWh) 转换 千焦 (kJ)', path: './MWh-to-kJ' },
  { name: '兆瓦时 (MWh) 转换 兆焦 (MJ)', path: './MWh-to-MJ' },
  { name: '兆瓦时 (MWh) 转换 吉焦 (GJ)', path: './MWh-to-GJ' },
  { name: '吉瓦时 (GWh) 转换 瓦秒 (Ws)', path: './GWh-to-Ws' },
  { name: '吉瓦时 (GWh) 转换 瓦米 (Wm)', path: './GWh-to-Wm' },
  { name: '吉瓦时 (GWh) 转换 瓦时 (Wh)', path: './GWh-to-Wh' },
  { name: '吉瓦时 (GWh) 转换 毫瓦时 (mWh)', path: './GWh-to-mWh' },
  { name: '吉瓦时 (GWh) 转换 千瓦时 (kWh)', path: './GWh-to-kWh' },
  { name: '吉瓦时 (GWh) 转换 兆瓦时 (MWh)', path: './GWh-to-MWh' },
  { name: '吉瓦时 (GWh) 转换 焦耳 (J)', path: './GWh-to-J' },
  { name: '吉瓦时 (GWh) 转换 千焦 (kJ)', path: './GWh-to-kJ' },
  { name: '吉瓦时 (GWh) 转换 兆焦 (MJ)', path: './GWh-to-MJ' },
  { name: '吉瓦时 (GWh) 转换 吉焦 (GJ)', path: './GWh-to-GJ' },
  { name: '焦耳 (J) 转换 瓦秒 (Ws)', path: './J-to-Ws' },
  { name: '焦耳 (J) 转换 瓦米 (Wm)', path: './J-to-Wm' },
  { name: '焦耳 (J) 转换 瓦时 (Wh)', path: './J-to-Wh' },
  { name: '焦耳 (J) 转换 毫瓦时 (mWh)', path: './J-to-mWh' },
  { name: '焦耳 (J) 转换 千瓦时 (kWh)', path: './J-to-kWh' },
  { name: '焦耳 (J) 转换 兆瓦时 (MWh)', path: './J-to-MWh' },
  { name: '焦耳 (J) 转换 吉瓦时 (GWh)', path: './J-to-GWh' },
  { name: '焦耳 (J) 转换 千焦 (kJ)', path: './J-to-kJ' },
  { name: '焦耳 (J) 转换 兆焦 (MJ)', path: './J-to-MJ' },
  { name: '焦耳 (J) 转换 吉焦 (GJ)', path: './J-to-GJ' },
  { name: '千焦 (kJ) 转换 瓦秒 (Ws)', path: './kJ-to-Ws' },
  { name: '千焦 (kJ) 转换 瓦米 (Wm)', path: './kJ-to-Wm' },
  { name: '千焦 (kJ) 转换 瓦时 (Wh)', path: './kJ-to-Wh' },
  { name: '千焦 (kJ) 转换 毫瓦时 (mWh)', path: './kJ-to-mWh' },
  { name: '千焦 (kJ) 转换 千瓦时 (kWh)', path: './kJ-to-kWh' },
  { name: '千焦 (kJ) 转换 兆瓦时 (MWh)', path: './kJ-to-MWh' },
  { name: '千焦 (kJ) 转换 吉瓦时 (GWh)', path: './kJ-to-GWh' },
  { name: '千焦 (kJ) 转换 焦耳 (J)', path: './kJ-to-J' },
  { name: '千焦 (kJ) 转换 兆焦 (MJ)', path: './kJ-to-MJ' },
  { name: '千焦 (kJ) 转换 吉焦 (GJ)', path: './kJ-to-GJ' },
  { name: '兆焦 (MJ) 转换 瓦秒 (Ws)', path: './MJ-to-Ws' },
  { name: '兆焦 (MJ) 转换 瓦米 (Wm)', path: './MJ-to-Wm' },
  { name: '兆焦 (MJ) 转换 瓦时 (Wh)', path: './MJ-to-Wh' },
  { name: '兆焦 (MJ) 转换 毫瓦时 (mWh)', path: './MJ-to-mWh' },
  { name: '兆焦 (MJ) 转换 千瓦时 (kWh)', path: './MJ-to-kWh' },
  { name: '兆焦 (MJ) 转换 兆瓦时 (MWh)', path: './MJ-to-MWh' },
  { name: '兆焦 (MJ) 转换 吉瓦时 (GWh)', path: './MJ-to-GWh' },
  { name: '兆焦 (MJ) 转换 焦耳 (J)', path: './MJ-to-J' },
  { name: '兆焦 (MJ) 转换 千焦 (kJ)', path: './MJ-to-kJ' },
  { name: '兆焦 (MJ) 转换 吉焦 (GJ)', path: './MJ-to-GJ' },
  { name: '吉焦 (GJ) 转换 瓦秒 (Ws)', path: './GJ-to-Ws' },
  { name: '吉焦 (GJ) 转换 瓦米 (Wm)', path: './GJ-to-Wm' },
  { name: '吉焦 (GJ) 转换 瓦时 (Wh)', path: './GJ-to-Wh' },
  { name: '吉焦 (GJ) 转换 毫瓦时 (mWh)', path: './GJ-to-mWh' },
  { name: '吉焦 (GJ) 转换 千瓦时 (kWh)', path: './GJ-to-kWh' },
  { name: '吉焦 (GJ) 转换 兆瓦时 (MWh)', path: './GJ-to-MWh' },
  { name: '吉焦 (GJ) 转换 吉瓦时 (GWh)', path: './GJ-to-GWh' },
  { name: '吉焦 (GJ) 转换 焦耳 (J)', path: './GJ-to-J' },
  { name: '吉焦 (GJ) 转换 千焦 (kJ)', path: './GJ-to-kJ' },
  { name: '吉焦 (GJ) 转换 兆焦 (MJ)', path: './GJ-to-MJ' }
];
export const Angle = [
  { name: '度 (deg) 转换 弧度 (rad)', path: './deg-to-rad' },
  { name: '度 (deg) 转换 梯度 (grad)', path: './deg-to-grad' },
  { name: '度 (deg) 转换 角分 (arcmin)', path: './deg-to-arcmin' },
  { name: '度 (deg) 转换 角秒 (arcsec)', path: './deg-to-arcsec' },
  { name: '弧度 (rad) 转换 度 (deg)', path: './rad-to-deg' },
  { name: '弧度 (rad) 转换 梯度 (grad)', path: './rad-to-grad' },
  { name: '弧度 (rad) 转换 角分 (arcmin)', path: './rad-to-arcmin' },
  { name: '弧度 (rad) 转换 角秒 (arcsec)', path: './rad-to-arcsec' },
  { name: '梯度 (grad) 转换 度 (deg)', path: './grad-to-deg' },
  { name: '梯度 (grad) 转换 弧度 (rad)', path: './grad-to-rad' },
  { name: '梯度 (grad) 转换 角分 (arcmin)', path: './grad-to-arcmin' },
  { name: '梯度 (grad) 转换 角秒 (arcsec)', path: './grad-to-arcsec' },
  { name: '角分 (arcmin) 转换 度 (deg)', path: './arcmin-to-deg' },
  { name: '角分 (arcmin) 转换 弧度 (rad)', path: './arcmin-to-rad' },
  { name: '角分 (arcmin) 转换 梯度 (grad)', path: './arcmin-to-grad' },
  { name: '角分 (arcmin) 转换 角秒 (arcsec)', path: './arcmin-to-arcsec' },
  { name: '角秒 (arcsec) 转换 度 (deg)', path: './arcsec-to-deg' },
  { name: '角秒 (arcsec) 转换 弧度 (rad)', path: './arcsec-to-rad' },
  { name: '角秒 (arcsec) 转换 梯度 (grad)', path: './arcsec-to-grad' },
  { name: '角秒 (arcsec) 转换 角分 (arcmin)', path: './arcsec-to-arcmin' }
];
export const Force = [
  { name: '牛顿 (N) 转换 千牛 (kN)', path: './N-to-kN' },
  { name: '牛顿 (N) 转换 磅力 (lbf)', path: './N-to-lbf' },
  { name: '牛顿 (N) 转换 千克力 (kgf)', path: './N-to-kgf' },
  { name: '千牛 (kN) 转换 牛顿 (N)', path: './kN-to-N' },
  { name: '千牛 (kN) 转换 磅力 (lbf)', path: './kN-to-lbf' },
  { name: '千牛 (kN) 转换 千克力 (kgf)', path: './kN-to-kgf' },
  { name: '磅力 (lbf) 转换 牛顿 (N)', path: './lbf-to-N' },
  { name: '磅力 (lbf) 转换 千牛 (kN)', path: './lbf-to-kN' },
  { name: '磅力 (lbf) 转换 千克力 (kgf)', path: './lbf-to-kgf' },
  { name: '千克力 (kgf) 转换 牛顿 (N)', path: './kgf-to-N' },
  { name: '千克力 (kgf) 转换 千牛 (kN)', path: './kgf-to-kN' },
  { name: '千克力 (kgf) 转换 磅力 (lbf)', path: './kgf-to-lbf' }
];