export const Time = [
{ name: '天到小时', path: './Day-to-Hour' },
{ name: '天到微秒', path: './Day-to-Microsecond' },
{ name: '天到毫秒', path: './Day-to-Millisecond' },
{ name: '天到分钟', path: './Day-to-Minute' },
{ name: '天到月', path: './Day-to-Month' },
{ name: '天到纳秒', path: './Day-to-Nanosecond' },
{ name: '天到秒', path: './Day-to-Second' },
{ name: '天到周', path: './Day-to-Week' },
{ name: '天到年', path: './Day-to-Year' },
{ name: '小时到天', path: './Hour-to-Day' },
{ name: '小时到微秒', path: './Hour-to-Microsecond' },
{ name: '小时到毫秒', path: './Hour-to-Millisecond' },
{ name: '小时到分钟', path: './Hour-to-Minute' },
{ name: '小时到月', path: './Hour-to-Month' },
{ name: '小时到纳秒', path: './Hour-to-Nanosecond' },
{ name: '小时到秒', path: './Hour-to-Second' },
{ name: '小时到周', path: './Hour-to-Week' },
{ name: '小时到年', path: './Hour-to-Year' },
{ name: '微秒到天', path: './Microsecond-to-Day' },
{ name: '微秒到小时', path: './Microsecond-to-Hour' },
{ name: '微秒到毫秒', path: './Microsecond-to-Millisecond' },
{ name: '微秒到分钟', path: './Microsecond-to-Minute' },
{ name: '微秒到月', path: './Microsecond-to-Month' },
{ name: '微秒到纳秒', path: './Microsecond-to-Nanosecond' },
{ name: '微秒到秒', path: './Microsecond-to-Second' },
{ name: '微秒到周', path: './Microsecond-to-Week' },
{ name: '微秒到年', path: './Microsecond-to-Year' },
{ name: '毫秒到天', path: './Millisecond-to-Day' },
{ name: '毫秒到小时', path: './Millisecond-to-Hour' },
{ name: '毫秒到微秒', path: './Millisecond-to-Microsecond' },
{ name: '毫秒到分钟', path: './Millisecond-to-Minute' },
{ name: '毫秒到月', path: './Millisecond-to-Month' },
{ name: '毫秒到纳秒', path: './Millisecond-to-Nanosecond' },
{ name: '毫秒到秒', path: './Millisecond-to-Second' },
{ name: '毫秒到周', path: './Millisecond-to-Week' },
{ name: '毫秒到年', path: './Millisecond-to-Year' },
{ name: '分钟到天', path: './Minute-to-Day' },
{ name: '分钟到小时', path: './Minute-to-Hour' },
{ name: '分钟到微秒', path: './Minute-to-Microsecond' },
{ name: '分钟到毫秒', path: './Minute-to-Millisecond' },
{ name: '分钟到月', path: './Minute-to-Month' },
{ name: '分钟到纳秒', path: './Minute-to-Nanosecond' },
{ name: '分钟到秒', path: './Minute-to-Second' },
{ name: '分钟到周', path: './Minute-to-Week' },
{ name: '分钟到年', path: './Minute-to-Year' },
{ name: '月到微秒', path: './Month-to-Microsecond' },
{ name: '月到纳秒', path: './Month-to-Nanosecond' },
{ name: '纳秒到天', path: './Nanosecond-to-Day' },
{ name: '纳秒到小时', path: './Nanosecond-to-Hour' },
{ name: '纳秒到微秒', path: './Nanosecond-to-Microsecond' },
{ name: '纳秒到毫秒', path: './Nanosecond-to-Millisecond' },
{ name: '纳秒到分钟', path: './Nanosecond-to-Minute' },
{ name: '纳秒到月', path: './Nanosecond-to-Month' },
{ name: '纳秒到秒', path: './Nanosecond-to-Second' },
{ name: '纳秒到周', path: './Nanosecond-to-Week' },
{ name: '纳秒到年', path: './Nanosecond-to-Year' },
{ name: '秒到天', path: './Second-to-Day' },
{ name: '秒到小时', path: './Second-to-Hour' },
{ name: '秒到微秒', path: './Second-to-Microsecond' },
{ name: '秒到毫秒', path: './Second-to-Millisecond' },
{ name: '秒到分钟', path: './Second-to-Minute' },
{ name: '秒到月', path: './Second-to-Month' },
{ name: '秒到纳秒', path: './Second-to-Nanosecond' },
{ name: '秒到周', path: './Second-to-Week' },
{ name: '秒到年', path: './Second-to-Year' },
{ name: '周到天', path: './Week-to-Day' },
{ name: '周到小时', path: './Week-to-Hour' },
{ name: '周到微秒', path: './Week-to-Microsecond' },
{ name: '周到毫秒', path: './Week-to-Millisecond' },
{ name: '周到分钟', path: './Week-to-Minute' },
{ name: '周到月', path: './Week-to-Month' },
{ name: '周到纳秒', path: './Week-to-Nanosecond' },
{ name: '周到秒', path: './Week-to-Second' },
{ name: '周到年', path: './Week-to-Year' },
{ name: '年到天', path: './Year-to-Day' },
{ name: '年到小时', path: './Year-to-Hour' },
{ name: '年到微秒', path: './Year-to-Microsecond' },
{ name: '年到毫秒', path: './Year-to-Millisecond' },
{ name: '年到分钟', path: './Year-to-Minute' },
{ name: '年到月', path: './Year-to-Month' },
{ name: '年到纳秒', path: './Year-to-Nanosecond' },
{ name: '年到秒', path: './Year-to-Second' },
{ name: '年到周', path: './Year-to-Week' }
];

// 新增温度转换文件列表
export const temperatureFiles = [
  { name: '摄氏度 (°C) 到 开尔文 (K)', path: './Celsius-to-Kelvin' },
  { name: '摄氏度 (°C) 到 华氏度 (°F)', path: './Celsius-to-Fahrenheit' },
  { name: '摄氏度 (°C) 到 兰金度 (R)', path: './Celsius-to-Rankine' },
  { name: '开尔文 (K) 到 摄氏度 (°C)', path: './Kelvin-to-Celsius' },
  { name: '开尔文 (K) 到 华氏度 (°F)', path: './Kelvin-to-Fahrenheit' },
  { name: '开尔文 (K) 到 兰金度 (R)', path: './Kelvin-to-Rankine' },
  { name: '华氏度 (°F) 到 摄氏度 (°C)', path: './Fahrenheit-to-Celsius' },
  { name: '华氏度 (°F) 到 开尔文 (K)', path: './Fahrenheit-to-Kelvin' },
  { name: '华氏度 (°F) 到 兰金度 (R)', path: './Fahrenheit-to-Rankine' },
  { name: '兰金度 (R) 到 摄氏度 (°C)', path: './Rankine-to-Celsius' },
  { name: '兰金度 (R) 到 开尔文 (K)', path: './Rankine-to-Kelvin' },
  { name: '兰金度 (R) 到 华氏度 (°F)', path: './Rankine-to-Fahrenheit' }
];
